# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/fpga13/group_admi/fpga_project/fpga_project.runs/impl_1/.Xil/Vivado-146488-FPGA13L/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/u_ila_0/u_ila_0.xci
# IP: The module: 'u_ila_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fpga13/group_admi/fpga_project/fpga_project.runs/impl_1/.Xil/Vivado-146488-FPGA13L/dc_drv.0/dc/prj_ip.gen/sources_1/ip/u_ila_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'u_ila_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/fpga13/group_admi/fpga_project/fpga_project.runs/impl_1/.Xil/Vivado-146488-FPGA13L/dc_drv.0/dc/prj_ip.gen/sources_1/ip/u_ila_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'u_ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/fpga13/group_admi/fpga_project/fpga_project.runs/impl_1/.Xil/Vivado-146488-FPGA13L/dc_drv.0/dc/prj_ip.gen/sources_1/ip/u_ila_0/u_ila_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'u_ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/fpga13/group_admi/fpga_project/fpga_project.runs/impl_1/.Xil/Vivado-146488-FPGA13L/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/u_ila_0/u_ila_0.xci
# IP: The module: 'u_ila_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fpga13/group_admi/fpga_project/fpga_project.runs/impl_1/.Xil/Vivado-146488-FPGA13L/dc_drv.0/dc/prj_ip.gen/sources_1/ip/u_ila_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'u_ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/fpga13/group_admi/fpga_project/fpga_project.runs/impl_1/.Xil/Vivado-146488-FPGA13L/dc_drv.0/dc/prj_ip.gen/sources_1/ip/u_ila_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'u_ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/fpga13/group_admi/fpga_project/fpga_project.runs/impl_1/.Xil/Vivado-146488-FPGA13L/dc_drv.0/dc/prj_ip.gen/sources_1/ip/u_ila_0/u_ila_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'u_ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
