#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Oct 30 09:59:10 CET 2025
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim mic_tests_behav -key {Behavioral:sim_1:Functional:mic_tests} -tclbatch mic_tests.tcl -view /home/fpga13/group_admi/exp_1/exp_1.sim/mic_tests_behav.wcfg -log simulate.log"
xsim mic_tests_behav -key {Behavioral:sim_1:Functional:mic_tests} -tclbatch mic_tests.tcl -view /home/fpga13/group_admi/exp_1/exp_1.sim/mic_tests_behav.wcfg -log simulate.log

