-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_2_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 42
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_2_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "01010001", 1 => "00000010", 2 => "01100100", 3 => "00110111", 
    4 => "10101000", 5 => "10011000", 6 => "10010111", 7 => "10100100", 
    8 => "10111110", 9 => "11100011", 10 => "11101101", 11 => "11101011", 
    12 => "11001111", 13 => "11011001", 14 => "11010011", 15 => "11000000", 
    16 => "10100010", 17 => "10111101", 18 => "10000110", 19 => "10000101", 
    20 => "10110000", 21 => "10010001", 22 => "10011100", 23 => "01100110", 
    24 => "10000101", 25 => "01100110", 26 => "01100111", 27 => "01011001", 
    28 => "01100100", 29 => "01100000", 30 => "01001110", 31 => "01001111", 
    32 => "01000010", 33 => "01000101", 34 => "00111001", 35 => "00111001", 
    36 => "01000011", 37 => "00111110", 38 => "00101011", 39 => "00110100", 
    40 => "00101110", 41 => "00101100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

