-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mfcc_log_17_9_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    x_val : IN STD_LOGIC_VECTOR (16 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (14 downto 0) );
end;


architecture behav of mfcc_log_17_9_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv5_8 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_const_lv5_7 : STD_LOGIC_VECTOR (4 downto 0) := "00111";
    constant ap_const_lv5_6 : STD_LOGIC_VECTOR (4 downto 0) := "00110";
    constant ap_const_lv5_5 : STD_LOGIC_VECTOR (4 downto 0) := "00101";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv5_1E : STD_LOGIC_VECTOR (4 downto 0) := "11110";
    constant ap_const_lv5_1D : STD_LOGIC_VECTOR (4 downto 0) := "11101";
    constant ap_const_lv5_1C : STD_LOGIC_VECTOR (4 downto 0) := "11100";
    constant ap_const_lv5_1B : STD_LOGIC_VECTOR (4 downto 0) := "11011";
    constant ap_const_lv5_1A : STD_LOGIC_VECTOR (4 downto 0) := "11010";
    constant ap_const_lv5_19 : STD_LOGIC_VECTOR (4 downto 0) := "11001";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv17_1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv26_0 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000000";
    constant ap_const_lv28_C000000 : STD_LOGIC_VECTOR (27 downto 0) := "1100000000000000000000000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv19_0 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv20_0 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv21_0 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv22_0 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv25_0 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv27_0 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000000000";
    constant ap_const_lv29_10000000 : STD_LOGIC_VECTOR (28 downto 0) := "10000000000000000000000000000";
    constant ap_const_lv28_0 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000000000";
    constant ap_const_lv29_0 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000000000000000000";
    constant ap_const_lv5_18 : STD_LOGIC_VECTOR (4 downto 0) := "11000";
    constant ap_const_lv5_17 : STD_LOGIC_VECTOR (4 downto 0) := "10111";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv28_2C5C85 : STD_LOGIC_VECTOR (27 downto 0) := "0000001011000101110010000101";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv14_2000 : STD_LOGIC_VECTOR (13 downto 0) := "10000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal log_apfixed_reduce_log_inverse_lut_table_array_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal log_apfixed_reduce_log_inverse_lut_table_array_ce0 : STD_LOGIC;
    signal log_apfixed_reduce_log_inverse_lut_table_array_q0 : STD_LOGIC_VECTOR (5 downto 0);
    signal log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_ce0 : STD_LOGIC;
    signal log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_q0 : STD_LOGIC_VECTOR (21 downto 0);
    signal log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_ce0 : STD_LOGIC;
    signal log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal b_frac_05_reg_279 : STD_LOGIC_VECTOR (28 downto 0);
    signal b_frac_05_reg_279_pp0_iter2_reg : STD_LOGIC_VECTOR (28 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln703_fu_415_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln703_reg_1724 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln703_reg_1724_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln703_reg_1724_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln703_reg_1724_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln703_reg_1724_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln703_reg_1724_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln703_reg_1724_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln703_reg_1724_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln703_reg_1724_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln703_reg_1724_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal b_frac_fu_425_p4 : STD_LOGIC_VECTOR (28 downto 0);
    signal b_frac_1_fu_459_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal icmp_ln731_fu_453_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal b_frac_2_fu_525_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln731_fu_517_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal b_frac_3_fu_591_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln731_1_fu_583_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal b_frac_4_fu_657_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln731_2_fu_649_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal b_frac_5_fu_723_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln731_3_fu_715_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal b_frac_6_fu_789_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln731_4_fu_781_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal b_frac_7_fu_855_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln731_5_fu_847_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal b_frac_8_fu_921_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln731_6_fu_913_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal b_frac_9_fu_987_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln731_7_fu_979_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal b_frac_10_fu_1053_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln731_8_fu_1045_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal b_frac_11_fu_1119_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln731_9_fu_1111_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal b_frac_12_fu_1185_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln731_10_fu_1177_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal b_frac_13_fu_1251_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln731_11_fu_1243_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal b_frac_14_fu_1317_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln731_12_fu_1309_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal b_frac_15_fu_1373_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln731_13_fu_1365_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal b_frac_16_fu_1391_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal icmp_ln731_15_fu_1381_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln731_14_fu_1405_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal b_frac_tilde_inverse_reg_1879 : STD_LOGIC_VECTOR (5 downto 0);
    signal log_sum_reg_1884 : STD_LOGIC_VECTOR (21 downto 0);
    signal log_sum_reg_1884_pp0_iter3_reg : STD_LOGIC_VECTOR (21 downto 0);
    signal log_sum_reg_1884_pp0_iter4_reg : STD_LOGIC_VECTOR (21 downto 0);
    signal log_sum_reg_1884_pp0_iter5_reg : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_fu_410_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln761_reg_1894 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp_42_reg_1901 : STD_LOGIC_VECTOR (23 downto 0);
    signal a_reg_1907 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln184_fu_1540_p2 : STD_LOGIC_VECTOR (28 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of add_ln184_fu_1540_p2 : signal is "no";
    signal add_ln184_reg_1918 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln184_reg_1918_pp0_iter6_reg : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln779_fu_1557_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal add_ln779_reg_1933 : STD_LOGIC_VECTOR (21 downto 0);
    signal add_ln779_reg_1933_pp0_iter7_reg : STD_LOGIC_VECTOR (21 downto 0);
    signal add_ln779_reg_1933_pp0_iter8_reg : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_47_reg_1938 : STD_LOGIC_VECTOR (14 downto 0);
    signal lshr_ln_reg_1943 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_49_reg_1948 : STD_LOGIC_VECTOR (21 downto 0);
    signal log_base_fu_1674_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal log_base_reg_1953 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp_50_reg_1958 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_b_frac_05_reg_279 : STD_LOGIC_VECTOR (28 downto 0);
    signal ap_phi_reg_pp0_iter1_b_frac_05_reg_279 : STD_LOGIC_VECTOR (28 downto 0);
    signal ap_phi_mux_index0_2_phi_fu_322_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_phi_reg_pp0_iter1_index0_2_reg_319 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_41_fu_1413_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_b_exp_07_reg_328 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_phi_reg_pp0_iter1_b_exp_07_reg_328 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_phi_reg_pp0_iter2_b_exp_07_reg_328 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_phi_reg_pp0_iter3_b_exp_07_reg_328 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_phi_reg_pp0_iter4_b_exp_07_reg_328 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_phi_reg_pp0_iter5_b_exp_07_reg_328 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_phi_reg_pp0_iter6_b_exp_07_reg_328 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_phi_reg_pp0_iter7_b_exp_07_reg_328 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_phi_reg_pp0_iter8_b_exp_07_reg_328 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_phi_mux_r_1_phi_fu_403_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_phi_reg_pp0_iter10_r_1_reg_399 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_phi_reg_pp0_iter0_r_1_reg_399 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_phi_reg_pp0_iter1_r_1_reg_399 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_phi_reg_pp0_iter2_r_1_reg_399 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_phi_reg_pp0_iter3_r_1_reg_399 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_phi_reg_pp0_iter4_r_1_reg_399 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_phi_reg_pp0_iter5_r_1_reg_399 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_phi_reg_pp0_iter6_r_1_reg_399 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_phi_reg_pp0_iter7_r_1_reg_399 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_phi_reg_pp0_iter8_r_1_reg_399 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_phi_reg_pp0_iter9_r_1_reg_399 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln756_fu_1443_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln186_fu_1549_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_410_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln728_fu_421_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1_fu_435_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal and_ln_fu_445_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_3_fu_479_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal and_ln731_1_fu_489_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_2_fu_503_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_471_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln731_fu_511_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln731_1_fu_497_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln726_fu_467_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_6_fu_545_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal and_ln731_2_fu_555_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_5_fu_569_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_537_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln731_1_fu_577_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln731_2_fu_563_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln726_1_fu_533_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_9_fu_611_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal and_ln731_3_fu_621_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_8_fu_635_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_603_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln731_2_fu_643_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln731_3_fu_629_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln726_2_fu_599_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_s_fu_677_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal and_ln731_4_fu_687_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_11_fu_701_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_fu_669_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln731_3_fu_709_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln731_4_fu_695_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln726_3_fu_665_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_13_fu_743_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal and_ln731_5_fu_753_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_14_fu_767_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_735_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln731_4_fu_775_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln731_5_fu_761_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln726_4_fu_731_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_16_fu_809_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal and_ln731_6_fu_819_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_17_fu_833_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_15_fu_801_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln731_5_fu_841_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln731_6_fu_827_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln726_5_fu_797_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_19_fu_875_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal and_ln731_7_fu_885_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_20_fu_899_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_18_fu_867_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln731_6_fu_907_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln731_7_fu_893_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln726_6_fu_863_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_22_fu_941_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal and_ln731_8_fu_951_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_23_fu_965_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_fu_933_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln731_7_fu_973_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln731_8_fu_959_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln726_7_fu_929_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_25_fu_1007_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal and_ln731_9_fu_1017_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_26_fu_1031_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_24_fu_999_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln731_8_fu_1039_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln731_9_fu_1025_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln726_8_fu_995_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_28_fu_1073_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal and_ln731_s_fu_1083_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_29_fu_1097_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_27_fu_1065_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln731_9_fu_1105_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln731_10_fu_1091_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln726_9_fu_1061_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_31_fu_1139_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal and_ln731_10_fu_1149_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_32_fu_1163_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_fu_1131_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln731_10_fu_1171_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln731_11_fu_1157_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln726_10_fu_1127_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_34_fu_1205_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal and_ln731_11_fu_1215_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_35_fu_1229_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_33_fu_1197_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln731_11_fu_1237_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln731_12_fu_1223_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln726_11_fu_1193_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_37_fu_1271_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal and_ln731_12_fu_1281_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_38_fu_1295_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_36_fu_1263_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln731_12_fu_1303_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln731_13_fu_1289_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln726_13_fu_1259_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln726_14_fu_1325_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln726_s_fu_1329_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_40_fu_1351_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_39_fu_1337_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln731_13_fu_1359_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln731_14_fu_1345_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln733_fu_1387_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln731_16_fu_1399_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_44_fu_1483_p4 : STD_LOGIC_VECTOR (22 downto 0);
    signal zext_ln182_cast_fu_1492_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_43_fu_1476_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_45_fu_1500_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal zext_ln182_fu_1507_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp_46_fu_1519_p4 : STD_LOGIC_VECTOR (19 downto 0);
    signal shl_ln_fu_1528_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal zext_ln184_1_fu_1536_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln182_fu_1511_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal zext_ln251_fu_1553_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal mul_ln739_fu_1566_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal grp_fu_1715_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp_48_fu_1581_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln776_fu_1594_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln776_fu_1590_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln776_fu_1594_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln776_fu_1594_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln739_fu_1566_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal shl_ln1_fu_1620_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal zext_ln776_1_fu_1627_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal zext_ln776_2_fu_1631_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sub_ln776_fu_1634_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln776_1_fu_1640_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln2_fu_1654_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal sext_ln779_fu_1661_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln776_fu_1650_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln779_1_fu_1668_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln779_1_fu_1665_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal shl_ln3_fu_1688_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln786_fu_1695_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal log_base_1_fu_1699_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_1715_p0 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_fu_1715_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to9 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal grp_fu_1715_p00 : STD_LOGIC_VECTOR (27 downto 0);
    signal grp_fu_1715_p10 : STD_LOGIC_VECTOR (27 downto 0);
    signal grp_fu_410_p10 : STD_LOGIC_VECTOR (28 downto 0);
    signal ap_condition_222 : BOOLEAN;
    signal ap_condition_299 : BOOLEAN;
    signal ap_condition_302 : BOOLEAN;
    signal ap_condition_305 : BOOLEAN;
    signal ap_condition_308 : BOOLEAN;
    signal ap_condition_311 : BOOLEAN;
    signal ap_condition_314 : BOOLEAN;
    signal ap_condition_317 : BOOLEAN;
    signal ap_condition_320 : BOOLEAN;
    signal ap_condition_323 : BOOLEAN;
    signal ap_condition_326 : BOOLEAN;
    signal ap_condition_329 : BOOLEAN;
    signal ap_condition_332 : BOOLEAN;
    signal ap_condition_335 : BOOLEAN;
    signal ap_condition_338 : BOOLEAN;
    signal ap_condition_341 : BOOLEAN;
    signal ap_condition_289 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component mfcc_mul_29s_6ns_29_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (28 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component mfcc_mul_5s_23ns_28_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (22 downto 0);
        dout : OUT STD_LOGIC_VECTOR (27 downto 0) );
    end component;


    component mfcc_mul_9ns_9ns_18_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (8 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        dout : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;


    component mfcc_mac_mulsub_24ns_4ns_29ns_29_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (23 downto 0);
        din1 : IN STD_LOGIC_VECTOR (3 downto 0);
        din2 : IN STD_LOGIC_VECTOR (28 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component mfcc_log_17_9_s_log_apfixed_reduce_log_inverse_lut_table_array_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component mfcc_log_17_9_s_log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (21 downto 0) );
    end component;


    component mfcc_log_17_9_s_log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;



begin
    log_apfixed_reduce_log_inverse_lut_table_array_U : component mfcc_log_17_9_s_log_apfixed_reduce_log_inverse_lut_table_array_ROM_AUTO_1R
    generic map (
        DataWidth => 6,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => log_apfixed_reduce_log_inverse_lut_table_array_address0,
        ce0 => log_apfixed_reduce_log_inverse_lut_table_array_ce0,
        q0 => log_apfixed_reduce_log_inverse_lut_table_array_q0);

    log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_U : component mfcc_log_17_9_s_log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_ROM_AUTO_1R
    generic map (
        DataWidth => 22,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_address0,
        ce0 => log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_ce0,
        q0 => log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_q0);

    log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_U : component mfcc_log_17_9_s_log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_ROM_AUTO_1R
    generic map (
        DataWidth => 18,
        AddressRange => 16,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_address0,
        ce0 => log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_ce0,
        q0 => log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_q0);

    mul_29s_6ns_29_2_1_U73 : component mfcc_mul_29s_6ns_29_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 29,
        din1_WIDTH => 6,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => b_frac_05_reg_279_pp0_iter2_reg,
        din1 => grp_fu_410_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_410_p2);

    mul_5s_23ns_28_1_1_U74 : component mfcc_mul_5s_23ns_28_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 23,
        dout_WIDTH => 28)
    port map (
        din0 => ap_phi_reg_pp0_iter8_b_exp_07_reg_328,
        din1 => mul_ln739_fu_1566_p1,
        dout => mul_ln739_fu_1566_p2);

    mul_9ns_9ns_18_1_1_U75 : component mfcc_mul_9ns_9ns_18_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 9,
        din1_WIDTH => 9,
        dout_WIDTH => 18)
    port map (
        din0 => mul_ln776_fu_1594_p0,
        din1 => mul_ln776_fu_1594_p1,
        dout => mul_ln776_fu_1594_p2);

    mac_mulsub_24ns_4ns_29ns_29_4_1_U76 : component mfcc_mac_mulsub_24ns_4ns_29ns_29_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 24,
        din1_WIDTH => 4,
        din2_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_1715_p0,
        din1 => grp_fu_1715_p1,
        din2 => add_ln184_reg_1918_pp0_iter6_reg,
        ce => ap_const_logic_1,
        dout => grp_fu_1715_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_b_exp_07_reg_328_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_289)) then
                if ((ap_const_boolean_1 = ap_condition_341)) then 
                    ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= ap_const_lv5_19;
                elsif ((ap_const_boolean_1 = ap_condition_338)) then 
                    ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= ap_const_lv5_1A;
                elsif ((ap_const_boolean_1 = ap_condition_335)) then 
                    ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= ap_const_lv5_1B;
                elsif ((ap_const_boolean_1 = ap_condition_332)) then 
                    ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= ap_const_lv5_1C;
                elsif ((ap_const_boolean_1 = ap_condition_329)) then 
                    ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= ap_const_lv5_1D;
                elsif ((ap_const_boolean_1 = ap_condition_326)) then 
                    ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= ap_const_lv5_1E;
                elsif ((ap_const_boolean_1 = ap_condition_323)) then 
                    ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= ap_const_lv5_1F;
                elsif ((ap_const_boolean_1 = ap_condition_320)) then 
                    ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= ap_const_lv5_0;
                elsif ((ap_const_boolean_1 = ap_condition_317)) then 
                    ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= ap_const_lv5_1;
                elsif ((ap_const_boolean_1 = ap_condition_314)) then 
                    ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= ap_const_lv5_2;
                elsif ((ap_const_boolean_1 = ap_condition_311)) then 
                    ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= ap_const_lv5_3;
                elsif ((ap_const_boolean_1 = ap_condition_308)) then 
                    ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= ap_const_lv5_4;
                elsif ((ap_const_boolean_1 = ap_condition_305)) then 
                    ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= ap_const_lv5_5;
                elsif ((ap_const_boolean_1 = ap_condition_302)) then 
                    ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= ap_const_lv5_6;
                elsif ((ap_const_boolean_1 = ap_condition_299)) then 
                    ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= ap_const_lv5_7;
                elsif (((icmp_ln731_fu_453_p2 = ap_const_lv1_1) and (icmp_ln703_fu_415_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= ap_const_lv5_8;
                elsif ((ap_const_boolean_1 = ap_condition_222)) then 
                    ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= select_ln731_14_fu_1405_p3;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= ap_phi_reg_pp0_iter0_b_exp_07_reg_328;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_b_frac_05_reg_279_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_289)) then
                if ((ap_const_boolean_1 = ap_condition_341)) then 
                    ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_15_fu_1373_p3;
                elsif ((ap_const_boolean_1 = ap_condition_338)) then 
                    ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_14_fu_1317_p3;
                elsif ((ap_const_boolean_1 = ap_condition_335)) then 
                    ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_13_fu_1251_p3;
                elsif ((ap_const_boolean_1 = ap_condition_332)) then 
                    ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_12_fu_1185_p3;
                elsif ((ap_const_boolean_1 = ap_condition_329)) then 
                    ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_11_fu_1119_p3;
                elsif ((ap_const_boolean_1 = ap_condition_326)) then 
                    ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_10_fu_1053_p3;
                elsif ((ap_const_boolean_1 = ap_condition_323)) then 
                    ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_9_fu_987_p3;
                elsif ((ap_const_boolean_1 = ap_condition_320)) then 
                    ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_8_fu_921_p3;
                elsif ((ap_const_boolean_1 = ap_condition_317)) then 
                    ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_7_fu_855_p3;
                elsif ((ap_const_boolean_1 = ap_condition_314)) then 
                    ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_6_fu_789_p3;
                elsif ((ap_const_boolean_1 = ap_condition_311)) then 
                    ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_5_fu_723_p3;
                elsif ((ap_const_boolean_1 = ap_condition_308)) then 
                    ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_4_fu_657_p3;
                elsif ((ap_const_boolean_1 = ap_condition_305)) then 
                    ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_3_fu_591_p3;
                elsif ((ap_const_boolean_1 = ap_condition_302)) then 
                    ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_2_fu_525_p3;
                elsif ((ap_const_boolean_1 = ap_condition_299)) then 
                    ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_1_fu_459_p3;
                elsif (((icmp_ln731_fu_453_p2 = ap_const_lv1_1) and (icmp_ln703_fu_415_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_fu_425_p4;
                elsif ((ap_const_boolean_1 = ap_condition_222)) then 
                    ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_16_fu_1391_p3;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= ap_phi_reg_pp0_iter0_b_frac_05_reg_279;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_r_1_reg_399_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_289)) then
                if ((icmp_ln703_fu_415_p2 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_r_1_reg_399 <= ap_const_lv15_0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_r_1_reg_399 <= ap_phi_reg_pp0_iter0_r_1_reg_399;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln703_reg_1724_pp0_iter3_reg = ap_const_lv1_0))) then
                a_reg_1907 <= grp_fu_410_p2(28 downto 25);
                mul_ln761_reg_1894 <= grp_fu_410_p2;
                tmp_42_reg_1901 <= grp_fu_410_p2(28 downto 5);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln703_reg_1724_pp0_iter4_reg = ap_const_lv1_0))) then
                add_ln184_reg_1918 <= add_ln184_fu_1540_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln184_reg_1918_pp0_iter6_reg <= add_ln184_reg_1918;
                add_ln779_reg_1933_pp0_iter7_reg <= add_ln779_reg_1933;
                add_ln779_reg_1933_pp0_iter8_reg <= add_ln779_reg_1933_pp0_iter7_reg;
                b_frac_05_reg_279_pp0_iter2_reg <= b_frac_05_reg_279;
                icmp_ln703_reg_1724_pp0_iter2_reg <= icmp_ln703_reg_1724_pp0_iter1_reg;
                icmp_ln703_reg_1724_pp0_iter3_reg <= icmp_ln703_reg_1724_pp0_iter2_reg;
                icmp_ln703_reg_1724_pp0_iter4_reg <= icmp_ln703_reg_1724_pp0_iter3_reg;
                icmp_ln703_reg_1724_pp0_iter5_reg <= icmp_ln703_reg_1724_pp0_iter4_reg;
                icmp_ln703_reg_1724_pp0_iter6_reg <= icmp_ln703_reg_1724_pp0_iter5_reg;
                icmp_ln703_reg_1724_pp0_iter7_reg <= icmp_ln703_reg_1724_pp0_iter6_reg;
                icmp_ln703_reg_1724_pp0_iter8_reg <= icmp_ln703_reg_1724_pp0_iter7_reg;
                icmp_ln703_reg_1724_pp0_iter9_reg <= icmp_ln703_reg_1724_pp0_iter8_reg;
                log_sum_reg_1884_pp0_iter3_reg <= log_sum_reg_1884;
                log_sum_reg_1884_pp0_iter4_reg <= log_sum_reg_1884_pp0_iter3_reg;
                log_sum_reg_1884_pp0_iter5_reg <= log_sum_reg_1884_pp0_iter4_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln703_reg_1724_pp0_iter5_reg = ap_const_lv1_0))) then
                add_ln779_reg_1933 <= add_ln779_fu_1557_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter10_r_1_reg_399 <= ap_phi_reg_pp0_iter9_r_1_reg_399;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_phi_reg_pp0_iter2_b_exp_07_reg_328 <= ap_phi_reg_pp0_iter1_b_exp_07_reg_328;
                ap_phi_reg_pp0_iter2_r_1_reg_399 <= ap_phi_reg_pp0_iter1_r_1_reg_399;
                b_frac_05_reg_279 <= ap_phi_reg_pp0_iter1_b_frac_05_reg_279;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter3_b_exp_07_reg_328 <= ap_phi_reg_pp0_iter2_b_exp_07_reg_328;
                ap_phi_reg_pp0_iter3_r_1_reg_399 <= ap_phi_reg_pp0_iter2_r_1_reg_399;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter4_b_exp_07_reg_328 <= ap_phi_reg_pp0_iter3_b_exp_07_reg_328;
                ap_phi_reg_pp0_iter4_r_1_reg_399 <= ap_phi_reg_pp0_iter3_r_1_reg_399;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter5_b_exp_07_reg_328 <= ap_phi_reg_pp0_iter4_b_exp_07_reg_328;
                ap_phi_reg_pp0_iter5_r_1_reg_399 <= ap_phi_reg_pp0_iter4_r_1_reg_399;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter6_b_exp_07_reg_328 <= ap_phi_reg_pp0_iter5_b_exp_07_reg_328;
                ap_phi_reg_pp0_iter6_r_1_reg_399 <= ap_phi_reg_pp0_iter5_r_1_reg_399;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter7_b_exp_07_reg_328 <= ap_phi_reg_pp0_iter6_b_exp_07_reg_328;
                ap_phi_reg_pp0_iter7_r_1_reg_399 <= ap_phi_reg_pp0_iter6_r_1_reg_399;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter8_b_exp_07_reg_328 <= ap_phi_reg_pp0_iter7_b_exp_07_reg_328;
                ap_phi_reg_pp0_iter8_r_1_reg_399 <= ap_phi_reg_pp0_iter7_r_1_reg_399;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter9_r_1_reg_399 <= ap_phi_reg_pp0_iter8_r_1_reg_399;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln703_reg_1724_pp0_iter1_reg = ap_const_lv1_0))) then
                b_frac_tilde_inverse_reg_1879 <= log_apfixed_reduce_log_inverse_lut_table_array_q0;
                log_sum_reg_1884 <= log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln703_reg_1724 <= icmp_ln703_fu_415_p2;
                icmp_ln703_reg_1724_pp0_iter1_reg <= icmp_ln703_reg_1724;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln703_reg_1724_pp0_iter8_reg = ap_const_lv1_0))) then
                log_base_reg_1953 <= log_base_fu_1674_p2;
                tmp_50_reg_1958 <= log_base_fu_1674_p2(28 downto 28);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln703_reg_1724_pp0_iter7_reg = ap_const_lv1_0))) then
                lshr_ln_reg_1943 <= mul_ln776_fu_1594_p2(17 downto 1);
                tmp_47_reg_1938 <= grp_fu_1715_p3(28 downto 14);
                tmp_49_reg_1948 <= mul_ln739_fu_1566_p2(27 downto 6);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln184_fu_1540_p2 <= std_logic_vector(unsigned(zext_ln184_1_fu_1536_p1) + unsigned(select_ln182_fu_1511_p3));
    add_ln779_1_fu_1668_p2 <= std_logic_vector(signed(sext_ln779_fu_1661_p1) + signed(sext_ln776_fu_1650_p1));
    add_ln779_fu_1557_p2 <= std_logic_vector(unsigned(zext_ln251_fu_1553_p1) + unsigned(log_sum_reg_1884_pp0_iter5_reg));
    and_ln731_10_fu_1149_p3 <= (tmp_31_fu_1139_p4 & ap_const_lv26_0);
    and_ln731_11_fu_1215_p3 <= (tmp_34_fu_1205_p4 & ap_const_lv26_0);
    and_ln731_12_fu_1281_p3 <= (tmp_37_fu_1271_p4 & ap_const_lv26_0);
    and_ln731_1_fu_489_p3 <= (tmp_3_fu_479_p4 & ap_const_lv26_0);
    and_ln731_2_fu_555_p3 <= (tmp_6_fu_545_p4 & ap_const_lv26_0);
    and_ln731_3_fu_621_p3 <= (tmp_9_fu_611_p4 & ap_const_lv26_0);
    and_ln731_4_fu_687_p3 <= (tmp_s_fu_677_p4 & ap_const_lv26_0);
    and_ln731_5_fu_753_p3 <= (tmp_13_fu_743_p4 & ap_const_lv26_0);
    and_ln731_6_fu_819_p3 <= (tmp_16_fu_809_p4 & ap_const_lv26_0);
    and_ln731_7_fu_885_p3 <= (tmp_19_fu_875_p4 & ap_const_lv26_0);
    and_ln731_8_fu_951_p3 <= (tmp_22_fu_941_p4 & ap_const_lv26_0);
    and_ln731_9_fu_1017_p3 <= (tmp_25_fu_1007_p4 & ap_const_lv26_0);
    and_ln731_s_fu_1083_p3 <= (tmp_28_fu_1073_p4 & ap_const_lv26_0);
    and_ln_fu_445_p3 <= (tmp_1_fu_435_p4 & ap_const_lv26_0);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_222_assign_proc : process(icmp_ln703_fu_415_p2, icmp_ln731_fu_453_p2, select_ln731_fu_517_p3, select_ln731_1_fu_583_p3, select_ln731_2_fu_649_p3, select_ln731_3_fu_715_p3, select_ln731_4_fu_781_p3, select_ln731_5_fu_847_p3, select_ln731_6_fu_913_p3, select_ln731_7_fu_979_p3, select_ln731_8_fu_1045_p3, select_ln731_9_fu_1111_p3, select_ln731_10_fu_1177_p3, select_ln731_11_fu_1243_p3, select_ln731_12_fu_1309_p3, select_ln731_13_fu_1365_p3, icmp_ln731_15_fu_1381_p2)
    begin
                ap_condition_222 <= ((icmp_ln731_15_fu_1381_p2 = ap_const_lv1_0) and (select_ln731_13_fu_1365_p3 = ap_const_lv1_0) and (select_ln731_12_fu_1309_p3 = ap_const_lv1_0) and (select_ln731_11_fu_1243_p3 = ap_const_lv1_0) and (select_ln731_10_fu_1177_p3 = ap_const_lv1_0) and (select_ln731_9_fu_1111_p3 = ap_const_lv1_0) and (select_ln731_8_fu_1045_p3 = ap_const_lv1_0) and (select_ln731_7_fu_979_p3 = ap_const_lv1_0) and (select_ln731_6_fu_913_p3 = ap_const_lv1_0) and (select_ln731_5_fu_847_p3 = ap_const_lv1_0) and (select_ln731_4_fu_781_p3 = ap_const_lv1_0) and (select_ln731_3_fu_715_p3 = ap_const_lv1_0) and (select_ln731_2_fu_649_p3 = ap_const_lv1_0) and (select_ln731_1_fu_583_p3 = ap_const_lv1_0) and (select_ln731_fu_517_p3 = ap_const_lv1_0) and (icmp_ln731_fu_453_p2 = ap_const_lv1_0) and (icmp_ln703_fu_415_p2 = ap_const_lv1_0));
    end process;


    ap_condition_289_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_289 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_299_assign_proc : process(icmp_ln703_fu_415_p2, icmp_ln731_fu_453_p2, select_ln731_fu_517_p3)
    begin
                ap_condition_299 <= ((select_ln731_fu_517_p3 = ap_const_lv1_1) and (icmp_ln731_fu_453_p2 = ap_const_lv1_0) and (icmp_ln703_fu_415_p2 = ap_const_lv1_0));
    end process;


    ap_condition_302_assign_proc : process(icmp_ln703_fu_415_p2, icmp_ln731_fu_453_p2, select_ln731_fu_517_p3, select_ln731_1_fu_583_p3)
    begin
                ap_condition_302 <= ((select_ln731_1_fu_583_p3 = ap_const_lv1_1) and (select_ln731_fu_517_p3 = ap_const_lv1_0) and (icmp_ln731_fu_453_p2 = ap_const_lv1_0) and (icmp_ln703_fu_415_p2 = ap_const_lv1_0));
    end process;


    ap_condition_305_assign_proc : process(icmp_ln703_fu_415_p2, icmp_ln731_fu_453_p2, select_ln731_fu_517_p3, select_ln731_1_fu_583_p3, select_ln731_2_fu_649_p3)
    begin
                ap_condition_305 <= ((select_ln731_2_fu_649_p3 = ap_const_lv1_1) and (select_ln731_1_fu_583_p3 = ap_const_lv1_0) and (select_ln731_fu_517_p3 = ap_const_lv1_0) and (icmp_ln731_fu_453_p2 = ap_const_lv1_0) and (icmp_ln703_fu_415_p2 = ap_const_lv1_0));
    end process;


    ap_condition_308_assign_proc : process(icmp_ln703_fu_415_p2, icmp_ln731_fu_453_p2, select_ln731_fu_517_p3, select_ln731_1_fu_583_p3, select_ln731_2_fu_649_p3, select_ln731_3_fu_715_p3)
    begin
                ap_condition_308 <= ((select_ln731_3_fu_715_p3 = ap_const_lv1_1) and (select_ln731_2_fu_649_p3 = ap_const_lv1_0) and (select_ln731_1_fu_583_p3 = ap_const_lv1_0) and (select_ln731_fu_517_p3 = ap_const_lv1_0) and (icmp_ln731_fu_453_p2 = ap_const_lv1_0) and (icmp_ln703_fu_415_p2 = ap_const_lv1_0));
    end process;


    ap_condition_311_assign_proc : process(icmp_ln703_fu_415_p2, icmp_ln731_fu_453_p2, select_ln731_fu_517_p3, select_ln731_1_fu_583_p3, select_ln731_2_fu_649_p3, select_ln731_3_fu_715_p3, select_ln731_4_fu_781_p3)
    begin
                ap_condition_311 <= ((select_ln731_4_fu_781_p3 = ap_const_lv1_1) and (select_ln731_3_fu_715_p3 = ap_const_lv1_0) and (select_ln731_2_fu_649_p3 = ap_const_lv1_0) and (select_ln731_1_fu_583_p3 = ap_const_lv1_0) and (select_ln731_fu_517_p3 = ap_const_lv1_0) and (icmp_ln731_fu_453_p2 = ap_const_lv1_0) and (icmp_ln703_fu_415_p2 = ap_const_lv1_0));
    end process;


    ap_condition_314_assign_proc : process(icmp_ln703_fu_415_p2, icmp_ln731_fu_453_p2, select_ln731_fu_517_p3, select_ln731_1_fu_583_p3, select_ln731_2_fu_649_p3, select_ln731_3_fu_715_p3, select_ln731_4_fu_781_p3, select_ln731_5_fu_847_p3)
    begin
                ap_condition_314 <= ((select_ln731_5_fu_847_p3 = ap_const_lv1_1) and (select_ln731_4_fu_781_p3 = ap_const_lv1_0) and (select_ln731_3_fu_715_p3 = ap_const_lv1_0) and (select_ln731_2_fu_649_p3 = ap_const_lv1_0) and (select_ln731_1_fu_583_p3 = ap_const_lv1_0) and (select_ln731_fu_517_p3 = ap_const_lv1_0) and (icmp_ln731_fu_453_p2 = ap_const_lv1_0) and (icmp_ln703_fu_415_p2 = ap_const_lv1_0));
    end process;


    ap_condition_317_assign_proc : process(icmp_ln703_fu_415_p2, icmp_ln731_fu_453_p2, select_ln731_fu_517_p3, select_ln731_1_fu_583_p3, select_ln731_2_fu_649_p3, select_ln731_3_fu_715_p3, select_ln731_4_fu_781_p3, select_ln731_5_fu_847_p3, select_ln731_6_fu_913_p3)
    begin
                ap_condition_317 <= ((select_ln731_6_fu_913_p3 = ap_const_lv1_1) and (select_ln731_5_fu_847_p3 = ap_const_lv1_0) and (select_ln731_4_fu_781_p3 = ap_const_lv1_0) and (select_ln731_3_fu_715_p3 = ap_const_lv1_0) and (select_ln731_2_fu_649_p3 = ap_const_lv1_0) and (select_ln731_1_fu_583_p3 = ap_const_lv1_0) and (select_ln731_fu_517_p3 = ap_const_lv1_0) and (icmp_ln731_fu_453_p2 = ap_const_lv1_0) and (icmp_ln703_fu_415_p2 = ap_const_lv1_0));
    end process;


    ap_condition_320_assign_proc : process(icmp_ln703_fu_415_p2, icmp_ln731_fu_453_p2, select_ln731_fu_517_p3, select_ln731_1_fu_583_p3, select_ln731_2_fu_649_p3, select_ln731_3_fu_715_p3, select_ln731_4_fu_781_p3, select_ln731_5_fu_847_p3, select_ln731_6_fu_913_p3, select_ln731_7_fu_979_p3)
    begin
                ap_condition_320 <= ((select_ln731_7_fu_979_p3 = ap_const_lv1_1) and (select_ln731_6_fu_913_p3 = ap_const_lv1_0) and (select_ln731_5_fu_847_p3 = ap_const_lv1_0) and (select_ln731_4_fu_781_p3 = ap_const_lv1_0) and (select_ln731_3_fu_715_p3 = ap_const_lv1_0) and (select_ln731_2_fu_649_p3 = ap_const_lv1_0) and (select_ln731_1_fu_583_p3 = ap_const_lv1_0) and (select_ln731_fu_517_p3 = ap_const_lv1_0) and (icmp_ln731_fu_453_p2 = ap_const_lv1_0) and (icmp_ln703_fu_415_p2 = ap_const_lv1_0));
    end process;


    ap_condition_323_assign_proc : process(icmp_ln703_fu_415_p2, icmp_ln731_fu_453_p2, select_ln731_fu_517_p3, select_ln731_1_fu_583_p3, select_ln731_2_fu_649_p3, select_ln731_3_fu_715_p3, select_ln731_4_fu_781_p3, select_ln731_5_fu_847_p3, select_ln731_6_fu_913_p3, select_ln731_7_fu_979_p3, select_ln731_8_fu_1045_p3)
    begin
                ap_condition_323 <= ((select_ln731_8_fu_1045_p3 = ap_const_lv1_1) and (select_ln731_7_fu_979_p3 = ap_const_lv1_0) and (select_ln731_6_fu_913_p3 = ap_const_lv1_0) and (select_ln731_5_fu_847_p3 = ap_const_lv1_0) and (select_ln731_4_fu_781_p3 = ap_const_lv1_0) and (select_ln731_3_fu_715_p3 = ap_const_lv1_0) and (select_ln731_2_fu_649_p3 = ap_const_lv1_0) and (select_ln731_1_fu_583_p3 = ap_const_lv1_0) and (select_ln731_fu_517_p3 = ap_const_lv1_0) and (icmp_ln731_fu_453_p2 = ap_const_lv1_0) and (icmp_ln703_fu_415_p2 = ap_const_lv1_0));
    end process;


    ap_condition_326_assign_proc : process(icmp_ln703_fu_415_p2, icmp_ln731_fu_453_p2, select_ln731_fu_517_p3, select_ln731_1_fu_583_p3, select_ln731_2_fu_649_p3, select_ln731_3_fu_715_p3, select_ln731_4_fu_781_p3, select_ln731_5_fu_847_p3, select_ln731_6_fu_913_p3, select_ln731_7_fu_979_p3, select_ln731_8_fu_1045_p3, select_ln731_9_fu_1111_p3)
    begin
                ap_condition_326 <= ((select_ln731_9_fu_1111_p3 = ap_const_lv1_1) and (select_ln731_8_fu_1045_p3 = ap_const_lv1_0) and (select_ln731_7_fu_979_p3 = ap_const_lv1_0) and (select_ln731_6_fu_913_p3 = ap_const_lv1_0) and (select_ln731_5_fu_847_p3 = ap_const_lv1_0) and (select_ln731_4_fu_781_p3 = ap_const_lv1_0) and (select_ln731_3_fu_715_p3 = ap_const_lv1_0) and (select_ln731_2_fu_649_p3 = ap_const_lv1_0) and (select_ln731_1_fu_583_p3 = ap_const_lv1_0) and (select_ln731_fu_517_p3 = ap_const_lv1_0) and (icmp_ln731_fu_453_p2 = ap_const_lv1_0) and (icmp_ln703_fu_415_p2 = ap_const_lv1_0));
    end process;


    ap_condition_329_assign_proc : process(icmp_ln703_fu_415_p2, icmp_ln731_fu_453_p2, select_ln731_fu_517_p3, select_ln731_1_fu_583_p3, select_ln731_2_fu_649_p3, select_ln731_3_fu_715_p3, select_ln731_4_fu_781_p3, select_ln731_5_fu_847_p3, select_ln731_6_fu_913_p3, select_ln731_7_fu_979_p3, select_ln731_8_fu_1045_p3, select_ln731_9_fu_1111_p3, select_ln731_10_fu_1177_p3)
    begin
                ap_condition_329 <= ((select_ln731_10_fu_1177_p3 = ap_const_lv1_1) and (select_ln731_9_fu_1111_p3 = ap_const_lv1_0) and (select_ln731_8_fu_1045_p3 = ap_const_lv1_0) and (select_ln731_7_fu_979_p3 = ap_const_lv1_0) and (select_ln731_6_fu_913_p3 = ap_const_lv1_0) and (select_ln731_5_fu_847_p3 = ap_const_lv1_0) and (select_ln731_4_fu_781_p3 = ap_const_lv1_0) and (select_ln731_3_fu_715_p3 = ap_const_lv1_0) and (select_ln731_2_fu_649_p3 = ap_const_lv1_0) and (select_ln731_1_fu_583_p3 = ap_const_lv1_0) and (select_ln731_fu_517_p3 = ap_const_lv1_0) and (icmp_ln731_fu_453_p2 = ap_const_lv1_0) and (icmp_ln703_fu_415_p2 = ap_const_lv1_0));
    end process;


    ap_condition_332_assign_proc : process(icmp_ln703_fu_415_p2, icmp_ln731_fu_453_p2, select_ln731_fu_517_p3, select_ln731_1_fu_583_p3, select_ln731_2_fu_649_p3, select_ln731_3_fu_715_p3, select_ln731_4_fu_781_p3, select_ln731_5_fu_847_p3, select_ln731_6_fu_913_p3, select_ln731_7_fu_979_p3, select_ln731_8_fu_1045_p3, select_ln731_9_fu_1111_p3, select_ln731_10_fu_1177_p3, select_ln731_11_fu_1243_p3)
    begin
                ap_condition_332 <= ((select_ln731_11_fu_1243_p3 = ap_const_lv1_1) and (select_ln731_10_fu_1177_p3 = ap_const_lv1_0) and (select_ln731_9_fu_1111_p3 = ap_const_lv1_0) and (select_ln731_8_fu_1045_p3 = ap_const_lv1_0) and (select_ln731_7_fu_979_p3 = ap_const_lv1_0) and (select_ln731_6_fu_913_p3 = ap_const_lv1_0) and (select_ln731_5_fu_847_p3 = ap_const_lv1_0) and (select_ln731_4_fu_781_p3 = ap_const_lv1_0) and (select_ln731_3_fu_715_p3 = ap_const_lv1_0) and (select_ln731_2_fu_649_p3 = ap_const_lv1_0) and (select_ln731_1_fu_583_p3 = ap_const_lv1_0) and (select_ln731_fu_517_p3 = ap_const_lv1_0) and (icmp_ln731_fu_453_p2 = ap_const_lv1_0) and (icmp_ln703_fu_415_p2 = ap_const_lv1_0));
    end process;


    ap_condition_335_assign_proc : process(icmp_ln703_fu_415_p2, icmp_ln731_fu_453_p2, select_ln731_fu_517_p3, select_ln731_1_fu_583_p3, select_ln731_2_fu_649_p3, select_ln731_3_fu_715_p3, select_ln731_4_fu_781_p3, select_ln731_5_fu_847_p3, select_ln731_6_fu_913_p3, select_ln731_7_fu_979_p3, select_ln731_8_fu_1045_p3, select_ln731_9_fu_1111_p3, select_ln731_10_fu_1177_p3, select_ln731_11_fu_1243_p3, select_ln731_12_fu_1309_p3)
    begin
                ap_condition_335 <= ((select_ln731_12_fu_1309_p3 = ap_const_lv1_1) and (select_ln731_11_fu_1243_p3 = ap_const_lv1_0) and (select_ln731_10_fu_1177_p3 = ap_const_lv1_0) and (select_ln731_9_fu_1111_p3 = ap_const_lv1_0) and (select_ln731_8_fu_1045_p3 = ap_const_lv1_0) and (select_ln731_7_fu_979_p3 = ap_const_lv1_0) and (select_ln731_6_fu_913_p3 = ap_const_lv1_0) and (select_ln731_5_fu_847_p3 = ap_const_lv1_0) and (select_ln731_4_fu_781_p3 = ap_const_lv1_0) and (select_ln731_3_fu_715_p3 = ap_const_lv1_0) and (select_ln731_2_fu_649_p3 = ap_const_lv1_0) and (select_ln731_1_fu_583_p3 = ap_const_lv1_0) and (select_ln731_fu_517_p3 = ap_const_lv1_0) and (icmp_ln731_fu_453_p2 = ap_const_lv1_0) and (icmp_ln703_fu_415_p2 = ap_const_lv1_0));
    end process;


    ap_condition_338_assign_proc : process(icmp_ln703_fu_415_p2, icmp_ln731_fu_453_p2, select_ln731_fu_517_p3, select_ln731_1_fu_583_p3, select_ln731_2_fu_649_p3, select_ln731_3_fu_715_p3, select_ln731_4_fu_781_p3, select_ln731_5_fu_847_p3, select_ln731_6_fu_913_p3, select_ln731_7_fu_979_p3, select_ln731_8_fu_1045_p3, select_ln731_9_fu_1111_p3, select_ln731_10_fu_1177_p3, select_ln731_11_fu_1243_p3, select_ln731_12_fu_1309_p3, select_ln731_13_fu_1365_p3)
    begin
                ap_condition_338 <= ((select_ln731_13_fu_1365_p3 = ap_const_lv1_1) and (select_ln731_12_fu_1309_p3 = ap_const_lv1_0) and (select_ln731_11_fu_1243_p3 = ap_const_lv1_0) and (select_ln731_10_fu_1177_p3 = ap_const_lv1_0) and (select_ln731_9_fu_1111_p3 = ap_const_lv1_0) and (select_ln731_8_fu_1045_p3 = ap_const_lv1_0) and (select_ln731_7_fu_979_p3 = ap_const_lv1_0) and (select_ln731_6_fu_913_p3 = ap_const_lv1_0) and (select_ln731_5_fu_847_p3 = ap_const_lv1_0) and (select_ln731_4_fu_781_p3 = ap_const_lv1_0) and (select_ln731_3_fu_715_p3 = ap_const_lv1_0) and (select_ln731_2_fu_649_p3 = ap_const_lv1_0) and (select_ln731_1_fu_583_p3 = ap_const_lv1_0) and (select_ln731_fu_517_p3 = ap_const_lv1_0) and (icmp_ln731_fu_453_p2 = ap_const_lv1_0) and (icmp_ln703_fu_415_p2 = ap_const_lv1_0));
    end process;


    ap_condition_341_assign_proc : process(icmp_ln703_fu_415_p2, icmp_ln731_fu_453_p2, select_ln731_fu_517_p3, select_ln731_1_fu_583_p3, select_ln731_2_fu_649_p3, select_ln731_3_fu_715_p3, select_ln731_4_fu_781_p3, select_ln731_5_fu_847_p3, select_ln731_6_fu_913_p3, select_ln731_7_fu_979_p3, select_ln731_8_fu_1045_p3, select_ln731_9_fu_1111_p3, select_ln731_10_fu_1177_p3, select_ln731_11_fu_1243_p3, select_ln731_12_fu_1309_p3, select_ln731_13_fu_1365_p3, icmp_ln731_15_fu_1381_p2)
    begin
                ap_condition_341 <= ((icmp_ln731_15_fu_1381_p2 = ap_const_lv1_1) and (select_ln731_13_fu_1365_p3 = ap_const_lv1_0) and (select_ln731_12_fu_1309_p3 = ap_const_lv1_0) and (select_ln731_11_fu_1243_p3 = ap_const_lv1_0) and (select_ln731_10_fu_1177_p3 = ap_const_lv1_0) and (select_ln731_9_fu_1111_p3 = ap_const_lv1_0) and (select_ln731_8_fu_1045_p3 = ap_const_lv1_0) and (select_ln731_7_fu_979_p3 = ap_const_lv1_0) and (select_ln731_6_fu_913_p3 = ap_const_lv1_0) and (select_ln731_5_fu_847_p3 = ap_const_lv1_0) and (select_ln731_4_fu_781_p3 = ap_const_lv1_0) and (select_ln731_3_fu_715_p3 = ap_const_lv1_0) and (select_ln731_2_fu_649_p3 = ap_const_lv1_0) and (select_ln731_1_fu_583_p3 = ap_const_lv1_0) and (select_ln731_fu_517_p3 = ap_const_lv1_0) and (icmp_ln731_fu_453_p2 = ap_const_lv1_0) and (icmp_ln703_fu_415_p2 = ap_const_lv1_0));
    end process;


    ap_done_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to9_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to9 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to9 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_index0_2_phi_fu_322_p4_assign_proc : process(icmp_ln703_reg_1724, ap_phi_reg_pp0_iter1_b_frac_05_reg_279, ap_phi_reg_pp0_iter1_index0_2_reg_319, tmp_41_fu_1413_p3)
    begin
        if ((icmp_ln703_reg_1724 = ap_const_lv1_0)) then
            if ((tmp_41_fu_1413_p3 = ap_const_lv1_0)) then 
                ap_phi_mux_index0_2_phi_fu_322_p4 <= ap_phi_reg_pp0_iter1_b_frac_05_reg_279(26 downto 21);
            elsif ((tmp_41_fu_1413_p3 = ap_const_lv1_1)) then 
                ap_phi_mux_index0_2_phi_fu_322_p4 <= ap_phi_reg_pp0_iter1_b_frac_05_reg_279(27 downto 22);
            else 
                ap_phi_mux_index0_2_phi_fu_322_p4 <= ap_phi_reg_pp0_iter1_index0_2_reg_319;
            end if;
        else 
            ap_phi_mux_index0_2_phi_fu_322_p4 <= ap_phi_reg_pp0_iter1_index0_2_reg_319;
        end if; 
    end process;


    ap_phi_mux_r_1_phi_fu_403_p4_assign_proc : process(icmp_ln703_reg_1724_pp0_iter9_reg, ap_phi_reg_pp0_iter10_r_1_reg_399, log_base_1_fu_1699_p2)
    begin
        if ((icmp_ln703_reg_1724_pp0_iter9_reg = ap_const_lv1_0)) then 
            ap_phi_mux_r_1_phi_fu_403_p4 <= log_base_1_fu_1699_p2(28 downto 14);
        else 
            ap_phi_mux_r_1_phi_fu_403_p4 <= ap_phi_reg_pp0_iter10_r_1_reg_399;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_b_exp_07_reg_328 <= "XXXXX";
    ap_phi_reg_pp0_iter0_b_frac_05_reg_279 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_r_1_reg_399 <= "XXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_index0_2_reg_319 <= "XXXXXX";

    ap_ready_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to9)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to9 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= ap_phi_mux_r_1_phi_fu_403_p4;
    b_frac_10_fu_1053_p3 <= (trunc_ln726_8_fu_995_p1 & ap_const_lv22_0);
    b_frac_11_fu_1119_p3 <= (trunc_ln726_9_fu_1061_p1 & ap_const_lv23_0);
    b_frac_12_fu_1185_p3 <= (trunc_ln726_10_fu_1127_p1 & ap_const_lv24_0);
    b_frac_13_fu_1251_p3 <= (trunc_ln726_11_fu_1193_p1 & ap_const_lv25_0);
    b_frac_14_fu_1317_p3 <= (trunc_ln726_13_fu_1259_p1 & ap_const_lv26_0);
    b_frac_15_fu_1373_p3 <= (trunc_ln726_14_fu_1325_p1 & ap_const_lv27_0);
    b_frac_16_fu_1391_p3 <= (trunc_ln733_fu_1387_p1 & ap_const_lv28_0);
    b_frac_1_fu_459_p3 <= (trunc_ln728_fu_421_p1 & ap_const_lv13_0);
    b_frac_2_fu_525_p3 <= (trunc_ln726_fu_467_p1 & ap_const_lv14_0);
    b_frac_3_fu_591_p3 <= (trunc_ln726_1_fu_533_p1 & ap_const_lv15_0);
    b_frac_4_fu_657_p3 <= (trunc_ln726_2_fu_599_p1 & ap_const_lv16_0);
    b_frac_5_fu_723_p3 <= (trunc_ln726_3_fu_665_p1 & ap_const_lv17_0);
    b_frac_6_fu_789_p3 <= (trunc_ln726_4_fu_731_p1 & ap_const_lv18_0);
    b_frac_7_fu_855_p3 <= (trunc_ln726_5_fu_797_p1 & ap_const_lv19_0);
    b_frac_8_fu_921_p3 <= (trunc_ln726_6_fu_863_p1 & ap_const_lv20_0);
    b_frac_9_fu_987_p3 <= (trunc_ln726_7_fu_929_p1 & ap_const_lv21_0);
    b_frac_fu_425_p4 <= ((ap_const_lv1_0 & trunc_ln728_fu_421_p1) & ap_const_lv12_0);
    grp_fu_1715_p0 <= grp_fu_1715_p00(24 - 1 downto 0);
    grp_fu_1715_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_42_reg_1901),28));
    grp_fu_1715_p1 <= grp_fu_1715_p10(4 - 1 downto 0);
    grp_fu_1715_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a_reg_1907),28));
    grp_fu_410_p1 <= grp_fu_410_p10(6 - 1 downto 0);
    grp_fu_410_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_frac_tilde_inverse_reg_1879),29));
    icmp_ln703_fu_415_p2 <= "1" when (signed(x_val) < signed(ap_const_lv17_1)) else "0";
    icmp_ln731_10_fu_1091_p2 <= "1" when (and_ln731_s_fu_1083_p3 = ap_const_lv28_C000000) else "0";
    icmp_ln731_11_fu_1157_p2 <= "1" when (and_ln731_10_fu_1149_p3 = ap_const_lv28_C000000) else "0";
    icmp_ln731_12_fu_1223_p2 <= "1" when (and_ln731_11_fu_1215_p3 = ap_const_lv28_C000000) else "0";
    icmp_ln731_13_fu_1289_p2 <= "1" when (and_ln731_12_fu_1281_p3 = ap_const_lv28_C000000) else "0";
    icmp_ln731_14_fu_1345_p2 <= "1" when (trunc_ln726_s_fu_1329_p3 = ap_const_lv28_C000000) else "0";
    icmp_ln731_15_fu_1381_p2 <= "1" when (b_frac_15_fu_1373_p3 = ap_const_lv29_10000000) else "0";
    icmp_ln731_16_fu_1399_p2 <= "0" when (b_frac_16_fu_1391_p3 = ap_const_lv29_0) else "1";
    icmp_ln731_1_fu_497_p2 <= "1" when (and_ln731_1_fu_489_p3 = ap_const_lv28_C000000) else "0";
    icmp_ln731_2_fu_563_p2 <= "1" when (and_ln731_2_fu_555_p3 = ap_const_lv28_C000000) else "0";
    icmp_ln731_3_fu_629_p2 <= "1" when (and_ln731_3_fu_621_p3 = ap_const_lv28_C000000) else "0";
    icmp_ln731_4_fu_695_p2 <= "1" when (and_ln731_4_fu_687_p3 = ap_const_lv28_C000000) else "0";
    icmp_ln731_5_fu_761_p2 <= "1" when (and_ln731_5_fu_753_p3 = ap_const_lv28_C000000) else "0";
    icmp_ln731_6_fu_827_p2 <= "1" when (and_ln731_6_fu_819_p3 = ap_const_lv28_C000000) else "0";
    icmp_ln731_7_fu_893_p2 <= "1" when (and_ln731_7_fu_885_p3 = ap_const_lv28_C000000) else "0";
    icmp_ln731_8_fu_959_p2 <= "1" when (and_ln731_8_fu_951_p3 = ap_const_lv28_C000000) else "0";
    icmp_ln731_9_fu_1025_p2 <= "1" when (and_ln731_9_fu_1017_p3 = ap_const_lv28_C000000) else "0";
    icmp_ln731_fu_453_p2 <= "1" when (and_ln_fu_445_p3 = ap_const_lv28_C000000) else "0";
    log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_address0 <= zext_ln756_fu_1443_p1(6 - 1 downto 0);

    log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_ce0 <= ap_const_logic_1;
        else 
            log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    log_apfixed_reduce_log_inverse_lut_table_array_address0 <= zext_ln756_fu_1443_p1(6 - 1 downto 0);

    log_apfixed_reduce_log_inverse_lut_table_array_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            log_apfixed_reduce_log_inverse_lut_table_array_ce0 <= ap_const_logic_1;
        else 
            log_apfixed_reduce_log_inverse_lut_table_array_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_address0 <= zext_ln186_fu_1549_p1(4 - 1 downto 0);

    log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_ce0_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_ce0 <= ap_const_logic_1;
        else 
            log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    log_base_1_fu_1699_p2 <= std_logic_vector(unsigned(log_base_reg_1953) + unsigned(sext_ln786_fu_1695_p1));
    log_base_fu_1674_p2 <= std_logic_vector(unsigned(add_ln779_1_fu_1668_p2) + unsigned(sext_ln779_1_fu_1665_p1));
    mul_ln739_fu_1566_p1 <= ap_const_lv28_2C5C85(23 - 1 downto 0);
    mul_ln776_fu_1594_p0 <= zext_ln776_fu_1590_p1(9 - 1 downto 0);
    mul_ln776_fu_1594_p1 <= zext_ln776_fu_1590_p1(9 - 1 downto 0);
    select_ln182_fu_1511_p3 <= 
        tmp_45_fu_1500_p3 when (tmp_43_fu_1476_p3(0) = '1') else 
        zext_ln182_fu_1507_p1;
    select_ln731_10_fu_1177_p3 <= 
        xor_ln731_10_fu_1171_p2 when (tmp_30_fu_1131_p3(0) = '1') else 
        icmp_ln731_11_fu_1157_p2;
    select_ln731_11_fu_1243_p3 <= 
        xor_ln731_11_fu_1237_p2 when (tmp_33_fu_1197_p3(0) = '1') else 
        icmp_ln731_12_fu_1223_p2;
    select_ln731_12_fu_1309_p3 <= 
        xor_ln731_12_fu_1303_p2 when (tmp_36_fu_1263_p3(0) = '1') else 
        icmp_ln731_13_fu_1289_p2;
    select_ln731_13_fu_1365_p3 <= 
        xor_ln731_13_fu_1359_p2 when (tmp_39_fu_1337_p3(0) = '1') else 
        icmp_ln731_14_fu_1345_p2;
    select_ln731_14_fu_1405_p3 <= 
        ap_const_lv5_18 when (icmp_ln731_16_fu_1399_p2(0) = '1') else 
        ap_const_lv5_17;
    select_ln731_1_fu_583_p3 <= 
        xor_ln731_1_fu_577_p2 when (tmp_4_fu_537_p3(0) = '1') else 
        icmp_ln731_2_fu_563_p2;
    select_ln731_2_fu_649_p3 <= 
        xor_ln731_2_fu_643_p2 when (tmp_7_fu_603_p3(0) = '1') else 
        icmp_ln731_3_fu_629_p2;
    select_ln731_3_fu_715_p3 <= 
        xor_ln731_3_fu_709_p2 when (tmp_10_fu_669_p3(0) = '1') else 
        icmp_ln731_4_fu_695_p2;
    select_ln731_4_fu_781_p3 <= 
        xor_ln731_4_fu_775_p2 when (tmp_12_fu_735_p3(0) = '1') else 
        icmp_ln731_5_fu_761_p2;
    select_ln731_5_fu_847_p3 <= 
        xor_ln731_5_fu_841_p2 when (tmp_15_fu_801_p3(0) = '1') else 
        icmp_ln731_6_fu_827_p2;
    select_ln731_6_fu_913_p3 <= 
        xor_ln731_6_fu_907_p2 when (tmp_18_fu_867_p3(0) = '1') else 
        icmp_ln731_7_fu_893_p2;
    select_ln731_7_fu_979_p3 <= 
        xor_ln731_7_fu_973_p2 when (tmp_21_fu_933_p3(0) = '1') else 
        icmp_ln731_8_fu_959_p2;
    select_ln731_8_fu_1045_p3 <= 
        xor_ln731_8_fu_1039_p2 when (tmp_24_fu_999_p3(0) = '1') else 
        icmp_ln731_9_fu_1025_p2;
    select_ln731_9_fu_1111_p3 <= 
        xor_ln731_9_fu_1105_p2 when (tmp_27_fu_1065_p3(0) = '1') else 
        icmp_ln731_10_fu_1091_p2;
    select_ln731_fu_517_p3 <= 
        xor_ln731_fu_511_p2 when (tmp_fu_471_p3(0) = '1') else 
        icmp_ln731_1_fu_497_p2;
        sext_ln776_fu_1650_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln776_1_fu_1640_p4),29));

        sext_ln779_1_fu_1665_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln779_reg_1933_pp0_iter8_reg),29));

        sext_ln779_fu_1661_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln2_fu_1654_p3),29));

        sext_ln786_fu_1695_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln3_fu_1688_p3),29));

    shl_ln1_fu_1620_p3 <= (tmp_47_reg_1938 & ap_const_lv10_0);
    shl_ln2_fu_1654_p3 <= (tmp_49_reg_1948 & ap_const_lv6_0);
    shl_ln3_fu_1688_p3 <= (tmp_50_reg_1958 & ap_const_lv14_2000);
    shl_ln_fu_1528_p3 <= (tmp_46_fu_1519_p4 & ap_const_lv8_0);
    sub_ln776_fu_1634_p2 <= std_logic_vector(unsigned(zext_ln776_1_fu_1627_p1) - unsigned(zext_ln776_2_fu_1631_p1));
    tmp_10_fu_669_p3 <= x_val(12 downto 12);
    tmp_11_fu_701_p3 <= x_val(11 downto 11);
    tmp_12_fu_735_p3 <= x_val(11 downto 11);
    tmp_13_fu_743_p4 <= x_val(10 downto 9);
    tmp_14_fu_767_p3 <= x_val(10 downto 10);
    tmp_15_fu_801_p3 <= x_val(10 downto 10);
    tmp_16_fu_809_p4 <= x_val(9 downto 8);
    tmp_17_fu_833_p3 <= x_val(9 downto 9);
    tmp_18_fu_867_p3 <= x_val(9 downto 9);
    tmp_19_fu_875_p4 <= x_val(8 downto 7);
    tmp_1_fu_435_p4 <= x_val(15 downto 14);
    tmp_20_fu_899_p3 <= x_val(8 downto 8);
    tmp_21_fu_933_p3 <= x_val(8 downto 8);
    tmp_22_fu_941_p4 <= x_val(7 downto 6);
    tmp_23_fu_965_p3 <= x_val(7 downto 7);
    tmp_24_fu_999_p3 <= x_val(7 downto 7);
    tmp_25_fu_1007_p4 <= x_val(6 downto 5);
    tmp_26_fu_1031_p3 <= x_val(6 downto 6);
    tmp_27_fu_1065_p3 <= x_val(6 downto 6);
    tmp_28_fu_1073_p4 <= x_val(5 downto 4);
    tmp_29_fu_1097_p3 <= x_val(5 downto 5);
    tmp_2_fu_503_p3 <= x_val(14 downto 14);
    tmp_30_fu_1131_p3 <= x_val(5 downto 5);
    tmp_31_fu_1139_p4 <= x_val(4 downto 3);
    tmp_32_fu_1163_p3 <= x_val(4 downto 4);
    tmp_33_fu_1197_p3 <= x_val(4 downto 4);
    tmp_34_fu_1205_p4 <= x_val(3 downto 2);
    tmp_35_fu_1229_p3 <= x_val(3 downto 3);
    tmp_36_fu_1263_p3 <= x_val(3 downto 3);
    tmp_37_fu_1271_p4 <= x_val(2 downto 1);
    tmp_38_fu_1295_p3 <= x_val(2 downto 2);
    tmp_39_fu_1337_p3 <= x_val(2 downto 2);
    tmp_3_fu_479_p4 <= x_val(14 downto 13);
    tmp_40_fu_1351_p3 <= x_val(1 downto 1);
    tmp_41_fu_1413_p3 <= ap_phi_reg_pp0_iter1_b_frac_05_reg_279(28 downto 28);
    tmp_43_fu_1476_p3 <= mul_ln761_reg_1894(28 downto 28);
    tmp_44_fu_1483_p4 <= mul_ln761_reg_1894(28 downto 6);
    tmp_45_fu_1500_p3 <= (ap_const_lv5_10 & tmp_42_reg_1901);
    tmp_46_fu_1519_p4 <= mul_ln761_reg_1894(24 downto 5);
    tmp_48_fu_1581_p4 <= grp_fu_1715_p3(28 downto 20);
    tmp_4_fu_537_p3 <= x_val(14 downto 14);
    tmp_5_fu_569_p3 <= x_val(13 downto 13);
    tmp_6_fu_545_p4 <= x_val(13 downto 12);
    tmp_7_fu_603_p3 <= x_val(13 downto 13);
    tmp_8_fu_635_p3 <= x_val(12 downto 12);
    tmp_9_fu_611_p4 <= x_val(12 downto 11);
    tmp_fu_471_p3 <= x_val(15 downto 15);
    tmp_s_fu_677_p4 <= x_val(11 downto 10);
    trunc_ln726_10_fu_1127_p1 <= x_val(5 - 1 downto 0);
    trunc_ln726_11_fu_1193_p1 <= x_val(4 - 1 downto 0);
    trunc_ln726_13_fu_1259_p1 <= x_val(3 - 1 downto 0);
    trunc_ln726_14_fu_1325_p1 <= x_val(2 - 1 downto 0);
    trunc_ln726_1_fu_533_p1 <= x_val(14 - 1 downto 0);
    trunc_ln726_2_fu_599_p1 <= x_val(13 - 1 downto 0);
    trunc_ln726_3_fu_665_p1 <= x_val(12 - 1 downto 0);
    trunc_ln726_4_fu_731_p1 <= x_val(11 - 1 downto 0);
    trunc_ln726_5_fu_797_p1 <= x_val(10 - 1 downto 0);
    trunc_ln726_6_fu_863_p1 <= x_val(9 - 1 downto 0);
    trunc_ln726_7_fu_929_p1 <= x_val(8 - 1 downto 0);
    trunc_ln726_8_fu_995_p1 <= x_val(7 - 1 downto 0);
    trunc_ln726_9_fu_1061_p1 <= x_val(6 - 1 downto 0);
    trunc_ln726_fu_467_p1 <= x_val(15 - 1 downto 0);
    trunc_ln726_s_fu_1329_p3 <= (trunc_ln726_14_fu_1325_p1 & ap_const_lv26_0);
    trunc_ln728_fu_421_p1 <= x_val(16 - 1 downto 0);
    trunc_ln733_fu_1387_p1 <= x_val(1 - 1 downto 0);
    trunc_ln776_1_fu_1640_p4 <= sub_ln776_fu_1634_p2(25 downto 10);
    xor_ln731_10_fu_1171_p2 <= (tmp_32_fu_1163_p3 xor ap_const_lv1_1);
    xor_ln731_11_fu_1237_p2 <= (tmp_35_fu_1229_p3 xor ap_const_lv1_1);
    xor_ln731_12_fu_1303_p2 <= (tmp_38_fu_1295_p3 xor ap_const_lv1_1);
    xor_ln731_13_fu_1359_p2 <= (tmp_40_fu_1351_p3 xor ap_const_lv1_1);
    xor_ln731_1_fu_577_p2 <= (tmp_5_fu_569_p3 xor ap_const_lv1_1);
    xor_ln731_2_fu_643_p2 <= (tmp_8_fu_635_p3 xor ap_const_lv1_1);
    xor_ln731_3_fu_709_p2 <= (tmp_11_fu_701_p3 xor ap_const_lv1_1);
    xor_ln731_4_fu_775_p2 <= (tmp_14_fu_767_p3 xor ap_const_lv1_1);
    xor_ln731_5_fu_841_p2 <= (tmp_17_fu_833_p3 xor ap_const_lv1_1);
    xor_ln731_6_fu_907_p2 <= (tmp_20_fu_899_p3 xor ap_const_lv1_1);
    xor_ln731_7_fu_973_p2 <= (tmp_23_fu_965_p3 xor ap_const_lv1_1);
    xor_ln731_8_fu_1039_p2 <= (tmp_26_fu_1031_p3 xor ap_const_lv1_1);
    xor_ln731_9_fu_1105_p2 <= (tmp_29_fu_1097_p3 xor ap_const_lv1_1);
    xor_ln731_fu_511_p2 <= (tmp_2_fu_503_p3 xor ap_const_lv1_1);
    zext_ln182_cast_fu_1492_p3 <= (ap_const_lv5_10 & tmp_44_fu_1483_p4);
    zext_ln182_fu_1507_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln182_cast_fu_1492_p3),29));
    zext_ln184_1_fu_1536_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_1528_p3),29));
    zext_ln186_fu_1549_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a_reg_1907),64));
    zext_ln251_fu_1553_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_q0),22));
    zext_ln756_fu_1443_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_index0_2_phi_fu_322_p4),64));
    zext_ln776_1_fu_1627_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln1_fu_1620_p3),26));
    zext_ln776_2_fu_1631_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_reg_1943),26));
    zext_ln776_fu_1590_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_48_fu_1581_p4),18));
end behav;
