-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_15_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 42
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_15_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00000000", 1 => "00000000", 2 => "00000000", 3 => "00000000", 
    4 => "00000000", 5 => "00000000", 6 => "00000000", 7 => "00000000", 
    8 => "00000000", 9 => "00000000", 10 => "00000000", 11 => "00000000", 
    12 => "00000000", 13 => "00000000", 14 => "00000000", 15 => "00000000", 
    16 => "00000000", 17 => "00000000", 18 => "00000000", 19 => "00000000", 
    20 => "00000000", 21 => "00000000", 22 => "00000000", 23 => "00000000", 
    24 => "00000000", 25 => "00000000", 26 => "00000000", 27 => "00000000", 
    28 => "00000000", 29 => "00000000", 30 => "00010111", 31 => "00101100", 
    32 => "01001101", 33 => "01011111", 34 => "01111101", 35 => "10001110", 
    36 => "10010110", 37 => "10101011", 38 => "11001100", 39 => "11010010", 
    40 => "11100110", 41 => "11110101");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

