# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/the5t/OneDrive/Documents/GitHub/rwth-lab-fpga-WIP/fpga_project/fpga_project.srcs/sources_1/ip/mfcc_1/mfcc_1.xci
# IP: The module: 'mfcc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/the5t/OneDrive/Documents/GitHub/rwth-lab-fpga-WIP/fpga_project/fpga_project.gen/sources_1/ip/mfcc_1/constraints/mfcc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mfcc_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/the5t/OneDrive/Documents/GitHub/rwth-lab-fpga-WIP/fpga_project/fpga_project.srcs/sources_1/ip/mfcc_1/mfcc_1.xci
# IP: The module: 'mfcc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/the5t/OneDrive/Documents/GitHub/rwth-lab-fpga-WIP/fpga_project/fpga_project.gen/sources_1/ip/mfcc_1/constraints/mfcc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mfcc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
