# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/fpga13/group_admi/fpga_project/fpga_project.srcs/sources_1/ip/fft/fft.xci
# IP: The module: 'fft' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fpga13/group_admi/fpga_project/fpga_project.gen/sources_1/ip/fft/fft_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/fpga13/group_admi/fpga_project/fpga_project.srcs/sources_1/ip/fft/fft.xci
# IP: The module: 'fft' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fpga13/group_admi/fpga_project/fpga_project.gen/sources_1/ip/fft/fft_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
