-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_0_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 42
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_0_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "01000100", 1 => "10101111", 2 => "01011001", 3 => "10011100", 
    4 => "00110101", 5 => "01011000", 6 => "01101000", 7 => "01101001", 
    8 => "01011100", 9 => "01000010", 10 => "00011101", 11 => "01010010", 
    12 => "00010101", 13 => "00101001", 14 => "00101110", 15 => "00100100", 
    16 => "00001101", 17 => "00110001", 18 => "00000001", 19 => "00000111", 
    20 => "00111010", 21 => "00100010", 22 => "00110011", 23 => "00000010", 
    24 => "00100111", 25 => "00001110", 26 => "00010011", 27 => "00001010", 
    28 => "00011001", 29 => "00011001", 30 => "00001011", 31 => "00010000", 
    32 => "00000111", 33 => "00001101", 34 => "00000100", 35 => "00000111", 
    36 => "00010100", 37 => "00010001", 38 => "00000001", 39 => "00001100", 
    40 => "00001000", 41 => "00001000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

