#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Nov 18 10:44:17 CET 2025
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim fft_test_behav -key {Behavioral:sim_1:Functional:fft_test} -tclbatch fft_test.tcl -view /home/fpga13/group_admi/exp_2/fft_test_behav.wcfg -log simulate.log"
xsim fft_test_behav -key {Behavioral:sim_1:Functional:fft_test} -tclbatch fft_test.tcl -view /home/fpga13/group_admi/exp_2/fft_test_behav.wcfg -log simulate.log

