// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mfcc_log_17_9_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_val,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [16:0] x_val;
output  [14:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_pp0_stage0_subdone;
wire   [5:0] log_apfixed_reduce_log_inverse_lut_table_array_address0;
reg    log_apfixed_reduce_log_inverse_lut_table_array_ce0;
wire   [5:0] log_apfixed_reduce_log_inverse_lut_table_array_q0;
wire   [5:0] log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_address0;
reg    log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_ce0;
wire   [21:0] log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_q0;
wire   [3:0] log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_address0;
reg    log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_ce0;
wire   [17:0] log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_q0;
reg  signed [28:0] b_frac_05_reg_279;
reg  signed [28:0] b_frac_05_reg_279_pp0_iter2_reg;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln703_fu_415_p2;
reg   [0:0] icmp_ln703_reg_1724;
reg   [0:0] icmp_ln703_reg_1724_pp0_iter1_reg;
reg   [0:0] icmp_ln703_reg_1724_pp0_iter2_reg;
reg   [0:0] icmp_ln703_reg_1724_pp0_iter3_reg;
reg   [0:0] icmp_ln703_reg_1724_pp0_iter4_reg;
reg   [0:0] icmp_ln703_reg_1724_pp0_iter5_reg;
reg   [0:0] icmp_ln703_reg_1724_pp0_iter6_reg;
reg   [0:0] icmp_ln703_reg_1724_pp0_iter7_reg;
reg   [0:0] icmp_ln703_reg_1724_pp0_iter8_reg;
reg   [0:0] icmp_ln703_reg_1724_pp0_iter9_reg;
wire   [28:0] b_frac_fu_425_p4;
wire   [28:0] b_frac_1_fu_459_p3;
wire   [0:0] icmp_ln731_fu_453_p2;
wire   [28:0] b_frac_2_fu_525_p3;
wire   [0:0] select_ln731_fu_517_p3;
wire   [28:0] b_frac_3_fu_591_p3;
wire   [0:0] select_ln731_1_fu_583_p3;
wire   [28:0] b_frac_4_fu_657_p3;
wire   [0:0] select_ln731_2_fu_649_p3;
wire   [28:0] b_frac_5_fu_723_p3;
wire   [0:0] select_ln731_3_fu_715_p3;
wire   [28:0] b_frac_6_fu_789_p3;
wire   [0:0] select_ln731_4_fu_781_p3;
wire   [28:0] b_frac_7_fu_855_p3;
wire   [0:0] select_ln731_5_fu_847_p3;
wire   [28:0] b_frac_8_fu_921_p3;
wire   [0:0] select_ln731_6_fu_913_p3;
wire   [28:0] b_frac_9_fu_987_p3;
wire   [0:0] select_ln731_7_fu_979_p3;
wire   [28:0] b_frac_10_fu_1053_p3;
wire   [0:0] select_ln731_8_fu_1045_p3;
wire   [28:0] b_frac_11_fu_1119_p3;
wire   [0:0] select_ln731_9_fu_1111_p3;
wire   [28:0] b_frac_12_fu_1185_p3;
wire   [0:0] select_ln731_10_fu_1177_p3;
wire   [28:0] b_frac_13_fu_1251_p3;
wire   [0:0] select_ln731_11_fu_1243_p3;
wire   [28:0] b_frac_14_fu_1317_p3;
wire   [0:0] select_ln731_12_fu_1309_p3;
wire   [28:0] b_frac_15_fu_1373_p3;
wire   [0:0] select_ln731_13_fu_1365_p3;
wire   [28:0] b_frac_16_fu_1391_p3;
wire   [0:0] icmp_ln731_15_fu_1381_p2;
wire   [4:0] select_ln731_14_fu_1405_p3;
reg   [5:0] b_frac_tilde_inverse_reg_1879;
reg   [21:0] log_sum_reg_1884;
reg   [21:0] log_sum_reg_1884_pp0_iter3_reg;
reg   [21:0] log_sum_reg_1884_pp0_iter4_reg;
reg   [21:0] log_sum_reg_1884_pp0_iter5_reg;
wire   [28:0] grp_fu_410_p2;
reg   [28:0] mul_ln761_reg_1894;
reg   [23:0] tmp_42_reg_1901;
reg   [3:0] a_reg_1907;
(* use_dsp48 = "no" *) wire   [28:0] add_ln184_fu_1540_p2;
reg   [28:0] add_ln184_reg_1918;
reg   [28:0] add_ln184_reg_1918_pp0_iter6_reg;
wire   [21:0] add_ln779_fu_1557_p2;
reg   [21:0] add_ln779_reg_1933;
reg   [21:0] add_ln779_reg_1933_pp0_iter7_reg;
reg   [21:0] add_ln779_reg_1933_pp0_iter8_reg;
reg   [14:0] tmp_47_reg_1938;
reg   [16:0] lshr_ln_reg_1943;
reg   [21:0] tmp_49_reg_1948;
wire   [28:0] log_base_fu_1674_p2;
reg   [28:0] log_base_reg_1953;
reg   [0:0] tmp_50_reg_1958;
wire  signed [28:0] ap_phi_reg_pp0_iter0_b_frac_05_reg_279;
reg  signed [28:0] ap_phi_reg_pp0_iter1_b_frac_05_reg_279;
reg   [5:0] ap_phi_mux_index0_2_phi_fu_322_p4;
wire   [5:0] ap_phi_reg_pp0_iter1_index0_2_reg_319;
wire   [0:0] tmp_41_fu_1413_p3;
wire   [4:0] ap_phi_reg_pp0_iter0_b_exp_07_reg_328;
reg   [4:0] ap_phi_reg_pp0_iter1_b_exp_07_reg_328;
reg   [4:0] ap_phi_reg_pp0_iter2_b_exp_07_reg_328;
reg   [4:0] ap_phi_reg_pp0_iter3_b_exp_07_reg_328;
reg   [4:0] ap_phi_reg_pp0_iter4_b_exp_07_reg_328;
reg   [4:0] ap_phi_reg_pp0_iter5_b_exp_07_reg_328;
reg   [4:0] ap_phi_reg_pp0_iter6_b_exp_07_reg_328;
reg   [4:0] ap_phi_reg_pp0_iter7_b_exp_07_reg_328;
reg  signed [4:0] ap_phi_reg_pp0_iter8_b_exp_07_reg_328;
reg   [14:0] ap_phi_mux_r_1_phi_fu_403_p4;
reg   [14:0] ap_phi_reg_pp0_iter10_r_1_reg_399;
wire   [14:0] ap_phi_reg_pp0_iter0_r_1_reg_399;
reg   [14:0] ap_phi_reg_pp0_iter1_r_1_reg_399;
reg   [14:0] ap_phi_reg_pp0_iter2_r_1_reg_399;
reg   [14:0] ap_phi_reg_pp0_iter3_r_1_reg_399;
reg   [14:0] ap_phi_reg_pp0_iter4_r_1_reg_399;
reg   [14:0] ap_phi_reg_pp0_iter5_r_1_reg_399;
reg   [14:0] ap_phi_reg_pp0_iter6_r_1_reg_399;
reg   [14:0] ap_phi_reg_pp0_iter7_r_1_reg_399;
reg   [14:0] ap_phi_reg_pp0_iter8_r_1_reg_399;
reg   [14:0] ap_phi_reg_pp0_iter9_r_1_reg_399;
wire   [63:0] zext_ln756_fu_1443_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln186_fu_1549_p1;
wire   [5:0] grp_fu_410_p1;
wire   [15:0] trunc_ln728_fu_421_p1;
wire   [1:0] tmp_1_fu_435_p4;
wire   [27:0] and_ln_fu_445_p3;
wire   [1:0] tmp_3_fu_479_p4;
wire   [27:0] and_ln731_1_fu_489_p3;
wire   [0:0] tmp_2_fu_503_p3;
wire   [0:0] tmp_fu_471_p3;
wire   [0:0] xor_ln731_fu_511_p2;
wire   [0:0] icmp_ln731_1_fu_497_p2;
wire   [14:0] trunc_ln726_fu_467_p1;
wire   [1:0] tmp_6_fu_545_p4;
wire   [27:0] and_ln731_2_fu_555_p3;
wire   [0:0] tmp_5_fu_569_p3;
wire   [0:0] tmp_4_fu_537_p3;
wire   [0:0] xor_ln731_1_fu_577_p2;
wire   [0:0] icmp_ln731_2_fu_563_p2;
wire   [13:0] trunc_ln726_1_fu_533_p1;
wire   [1:0] tmp_9_fu_611_p4;
wire   [27:0] and_ln731_3_fu_621_p3;
wire   [0:0] tmp_8_fu_635_p3;
wire   [0:0] tmp_7_fu_603_p3;
wire   [0:0] xor_ln731_2_fu_643_p2;
wire   [0:0] icmp_ln731_3_fu_629_p2;
wire   [12:0] trunc_ln726_2_fu_599_p1;
wire   [1:0] tmp_s_fu_677_p4;
wire   [27:0] and_ln731_4_fu_687_p3;
wire   [0:0] tmp_11_fu_701_p3;
wire   [0:0] tmp_10_fu_669_p3;
wire   [0:0] xor_ln731_3_fu_709_p2;
wire   [0:0] icmp_ln731_4_fu_695_p2;
wire   [11:0] trunc_ln726_3_fu_665_p1;
wire   [1:0] tmp_13_fu_743_p4;
wire   [27:0] and_ln731_5_fu_753_p3;
wire   [0:0] tmp_14_fu_767_p3;
wire   [0:0] tmp_12_fu_735_p3;
wire   [0:0] xor_ln731_4_fu_775_p2;
wire   [0:0] icmp_ln731_5_fu_761_p2;
wire   [10:0] trunc_ln726_4_fu_731_p1;
wire   [1:0] tmp_16_fu_809_p4;
wire   [27:0] and_ln731_6_fu_819_p3;
wire   [0:0] tmp_17_fu_833_p3;
wire   [0:0] tmp_15_fu_801_p3;
wire   [0:0] xor_ln731_5_fu_841_p2;
wire   [0:0] icmp_ln731_6_fu_827_p2;
wire   [9:0] trunc_ln726_5_fu_797_p1;
wire   [1:0] tmp_19_fu_875_p4;
wire   [27:0] and_ln731_7_fu_885_p3;
wire   [0:0] tmp_20_fu_899_p3;
wire   [0:0] tmp_18_fu_867_p3;
wire   [0:0] xor_ln731_6_fu_907_p2;
wire   [0:0] icmp_ln731_7_fu_893_p2;
wire   [8:0] trunc_ln726_6_fu_863_p1;
wire   [1:0] tmp_22_fu_941_p4;
wire   [27:0] and_ln731_8_fu_951_p3;
wire   [0:0] tmp_23_fu_965_p3;
wire   [0:0] tmp_21_fu_933_p3;
wire   [0:0] xor_ln731_7_fu_973_p2;
wire   [0:0] icmp_ln731_8_fu_959_p2;
wire   [7:0] trunc_ln726_7_fu_929_p1;
wire   [1:0] tmp_25_fu_1007_p4;
wire   [27:0] and_ln731_9_fu_1017_p3;
wire   [0:0] tmp_26_fu_1031_p3;
wire   [0:0] tmp_24_fu_999_p3;
wire   [0:0] xor_ln731_8_fu_1039_p2;
wire   [0:0] icmp_ln731_9_fu_1025_p2;
wire   [6:0] trunc_ln726_8_fu_995_p1;
wire   [1:0] tmp_28_fu_1073_p4;
wire   [27:0] and_ln731_s_fu_1083_p3;
wire   [0:0] tmp_29_fu_1097_p3;
wire   [0:0] tmp_27_fu_1065_p3;
wire   [0:0] xor_ln731_9_fu_1105_p2;
wire   [0:0] icmp_ln731_10_fu_1091_p2;
wire   [5:0] trunc_ln726_9_fu_1061_p1;
wire   [1:0] tmp_31_fu_1139_p4;
wire   [27:0] and_ln731_10_fu_1149_p3;
wire   [0:0] tmp_32_fu_1163_p3;
wire   [0:0] tmp_30_fu_1131_p3;
wire   [0:0] xor_ln731_10_fu_1171_p2;
wire   [0:0] icmp_ln731_11_fu_1157_p2;
wire   [4:0] trunc_ln726_10_fu_1127_p1;
wire   [1:0] tmp_34_fu_1205_p4;
wire   [27:0] and_ln731_11_fu_1215_p3;
wire   [0:0] tmp_35_fu_1229_p3;
wire   [0:0] tmp_33_fu_1197_p3;
wire   [0:0] xor_ln731_11_fu_1237_p2;
wire   [0:0] icmp_ln731_12_fu_1223_p2;
wire   [3:0] trunc_ln726_11_fu_1193_p1;
wire   [1:0] tmp_37_fu_1271_p4;
wire   [27:0] and_ln731_12_fu_1281_p3;
wire   [0:0] tmp_38_fu_1295_p3;
wire   [0:0] tmp_36_fu_1263_p3;
wire   [0:0] xor_ln731_12_fu_1303_p2;
wire   [0:0] icmp_ln731_13_fu_1289_p2;
wire   [2:0] trunc_ln726_13_fu_1259_p1;
wire   [1:0] trunc_ln726_14_fu_1325_p1;
wire   [27:0] trunc_ln726_s_fu_1329_p3;
wire   [0:0] tmp_40_fu_1351_p3;
wire   [0:0] tmp_39_fu_1337_p3;
wire   [0:0] xor_ln731_13_fu_1359_p2;
wire   [0:0] icmp_ln731_14_fu_1345_p2;
wire   [0:0] trunc_ln733_fu_1387_p1;
wire   [0:0] icmp_ln731_16_fu_1399_p2;
wire   [22:0] tmp_44_fu_1483_p4;
wire   [27:0] zext_ln182_cast_fu_1492_p3;
wire   [0:0] tmp_43_fu_1476_p3;
wire   [28:0] tmp_45_fu_1500_p3;
wire   [28:0] zext_ln182_fu_1507_p1;
wire   [19:0] tmp_46_fu_1519_p4;
wire   [27:0] shl_ln_fu_1528_p3;
wire   [28:0] zext_ln184_1_fu_1536_p1;
wire   [28:0] select_ln182_fu_1511_p3;
wire   [21:0] zext_ln251_fu_1553_p1;
wire   [22:0] mul_ln739_fu_1566_p1;
wire   [28:0] grp_fu_1715_p3;
wire   [8:0] tmp_48_fu_1581_p4;
wire   [8:0] mul_ln776_fu_1594_p0;
wire   [17:0] zext_ln776_fu_1590_p1;
wire   [8:0] mul_ln776_fu_1594_p1;
wire   [17:0] mul_ln776_fu_1594_p2;
wire   [27:0] mul_ln739_fu_1566_p2;
wire   [24:0] shl_ln1_fu_1620_p3;
wire   [25:0] zext_ln776_1_fu_1627_p1;
wire   [25:0] zext_ln776_2_fu_1631_p1;
wire   [25:0] sub_ln776_fu_1634_p2;
wire   [15:0] trunc_ln776_1_fu_1640_p4;
wire   [27:0] shl_ln2_fu_1654_p3;
wire  signed [28:0] sext_ln779_fu_1661_p1;
wire  signed [28:0] sext_ln776_fu_1650_p1;
wire   [28:0] add_ln779_1_fu_1668_p2;
wire  signed [28:0] sext_ln779_1_fu_1665_p1;
wire   [14:0] shl_ln3_fu_1688_p3;
wire  signed [28:0] sext_ln786_fu_1695_p1;
wire   [28:0] log_base_1_fu_1699_p2;
wire   [23:0] grp_fu_1715_p0;
wire   [3:0] grp_fu_1715_p1;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to9;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire   [27:0] grp_fu_1715_p00;
wire   [27:0] grp_fu_1715_p10;
wire   [28:0] grp_fu_410_p10;
reg    ap_condition_222;
reg    ap_condition_299;
reg    ap_condition_302;
reg    ap_condition_305;
reg    ap_condition_308;
reg    ap_condition_311;
reg    ap_condition_314;
reg    ap_condition_317;
reg    ap_condition_320;
reg    ap_condition_323;
reg    ap_condition_326;
reg    ap_condition_329;
reg    ap_condition_332;
reg    ap_condition_335;
reg    ap_condition_338;
reg    ap_condition_341;
reg    ap_condition_289;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
end

mfcc_log_17_9_s_log_apfixed_reduce_log_inverse_lut_table_array_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
log_apfixed_reduce_log_inverse_lut_table_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(log_apfixed_reduce_log_inverse_lut_table_array_address0),
    .ce0(log_apfixed_reduce_log_inverse_lut_table_array_ce0),
    .q0(log_apfixed_reduce_log_inverse_lut_table_array_q0)
);

mfcc_log_17_9_s_log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_ROM_AUTO_1R #(
    .DataWidth( 22 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_address0),
    .ce0(log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_ce0),
    .q0(log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_q0)
);

mfcc_log_17_9_s_log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_ROM_AUTO_1R #(
    .DataWidth( 18 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_address0),
    .ce0(log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_ce0),
    .q0(log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_q0)
);

mfcc_mul_29s_6ns_29_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 29 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 29 ))
mul_29s_6ns_29_2_1_U73(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(b_frac_05_reg_279_pp0_iter2_reg),
    .din1(grp_fu_410_p1),
    .ce(1'b1),
    .dout(grp_fu_410_p2)
);

mfcc_mul_5s_23ns_28_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 23 ),
    .dout_WIDTH( 28 ))
mul_5s_23ns_28_1_1_U74(
    .din0(ap_phi_reg_pp0_iter8_b_exp_07_reg_328),
    .din1(mul_ln739_fu_1566_p1),
    .dout(mul_ln739_fu_1566_p2)
);

mfcc_mul_9ns_9ns_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 18 ))
mul_9ns_9ns_18_1_1_U75(
    .din0(mul_ln776_fu_1594_p0),
    .din1(mul_ln776_fu_1594_p1),
    .dout(mul_ln776_fu_1594_p2)
);

mfcc_mac_mulsub_24ns_4ns_29ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_mulsub_24ns_4ns_29ns_29_4_1_U76(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1715_p0),
    .din1(grp_fu_1715_p1),
    .din2(add_ln184_reg_1918_pp0_iter6_reg),
    .ce(1'b1),
    .dout(grp_fu_1715_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_289)) begin
        if ((1'b1 == ap_condition_341)) begin
            ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= 5'd25;
        end else if ((1'b1 == ap_condition_338)) begin
            ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= 5'd26;
        end else if ((1'b1 == ap_condition_335)) begin
            ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= 5'd27;
        end else if ((1'b1 == ap_condition_332)) begin
            ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= 5'd28;
        end else if ((1'b1 == ap_condition_329)) begin
            ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= 5'd29;
        end else if ((1'b1 == ap_condition_326)) begin
            ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= 5'd30;
        end else if ((1'b1 == ap_condition_323)) begin
            ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= 5'd31;
        end else if ((1'b1 == ap_condition_320)) begin
            ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= 5'd0;
        end else if ((1'b1 == ap_condition_317)) begin
            ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= 5'd1;
        end else if ((1'b1 == ap_condition_314)) begin
            ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= 5'd2;
        end else if ((1'b1 == ap_condition_311)) begin
            ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= 5'd3;
        end else if ((1'b1 == ap_condition_308)) begin
            ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= 5'd4;
        end else if ((1'b1 == ap_condition_305)) begin
            ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= 5'd5;
        end else if ((1'b1 == ap_condition_302)) begin
            ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= 5'd6;
        end else if ((1'b1 == ap_condition_299)) begin
            ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= 5'd7;
        end else if (((icmp_ln731_fu_453_p2 == 1'd1) & (icmp_ln703_fu_415_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= 5'd8;
        end else if ((1'b1 == ap_condition_222)) begin
            ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= select_ln731_14_fu_1405_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_b_exp_07_reg_328 <= ap_phi_reg_pp0_iter0_b_exp_07_reg_328;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_289)) begin
        if ((1'b1 == ap_condition_341)) begin
            ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_15_fu_1373_p3;
        end else if ((1'b1 == ap_condition_338)) begin
            ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_14_fu_1317_p3;
        end else if ((1'b1 == ap_condition_335)) begin
            ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_13_fu_1251_p3;
        end else if ((1'b1 == ap_condition_332)) begin
            ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_12_fu_1185_p3;
        end else if ((1'b1 == ap_condition_329)) begin
            ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_11_fu_1119_p3;
        end else if ((1'b1 == ap_condition_326)) begin
            ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_10_fu_1053_p3;
        end else if ((1'b1 == ap_condition_323)) begin
            ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_9_fu_987_p3;
        end else if ((1'b1 == ap_condition_320)) begin
            ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_8_fu_921_p3;
        end else if ((1'b1 == ap_condition_317)) begin
            ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_7_fu_855_p3;
        end else if ((1'b1 == ap_condition_314)) begin
            ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_6_fu_789_p3;
        end else if ((1'b1 == ap_condition_311)) begin
            ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_5_fu_723_p3;
        end else if ((1'b1 == ap_condition_308)) begin
            ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_4_fu_657_p3;
        end else if ((1'b1 == ap_condition_305)) begin
            ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_3_fu_591_p3;
        end else if ((1'b1 == ap_condition_302)) begin
            ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_2_fu_525_p3;
        end else if ((1'b1 == ap_condition_299)) begin
            ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_1_fu_459_p3;
        end else if (((icmp_ln731_fu_453_p2 == 1'd1) & (icmp_ln703_fu_415_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_fu_425_p4;
        end else if ((1'b1 == ap_condition_222)) begin
            ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= b_frac_16_fu_1391_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_b_frac_05_reg_279 <= ap_phi_reg_pp0_iter0_b_frac_05_reg_279;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_289)) begin
        if ((icmp_ln703_fu_415_p2 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_r_1_reg_399 <= 15'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_r_1_reg_399 <= ap_phi_reg_pp0_iter0_r_1_reg_399;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln703_reg_1724_pp0_iter3_reg == 1'd0))) begin
        a_reg_1907 <= {{grp_fu_410_p2[28:25]}};
        mul_ln761_reg_1894 <= grp_fu_410_p2;
        tmp_42_reg_1901 <= {{grp_fu_410_p2[28:5]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln703_reg_1724_pp0_iter4_reg == 1'd0))) begin
        add_ln184_reg_1918 <= add_ln184_fu_1540_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln184_reg_1918_pp0_iter6_reg <= add_ln184_reg_1918;
        add_ln779_reg_1933_pp0_iter7_reg <= add_ln779_reg_1933;
        add_ln779_reg_1933_pp0_iter8_reg <= add_ln779_reg_1933_pp0_iter7_reg;
        b_frac_05_reg_279_pp0_iter2_reg <= b_frac_05_reg_279;
        icmp_ln703_reg_1724_pp0_iter2_reg <= icmp_ln703_reg_1724_pp0_iter1_reg;
        icmp_ln703_reg_1724_pp0_iter3_reg <= icmp_ln703_reg_1724_pp0_iter2_reg;
        icmp_ln703_reg_1724_pp0_iter4_reg <= icmp_ln703_reg_1724_pp0_iter3_reg;
        icmp_ln703_reg_1724_pp0_iter5_reg <= icmp_ln703_reg_1724_pp0_iter4_reg;
        icmp_ln703_reg_1724_pp0_iter6_reg <= icmp_ln703_reg_1724_pp0_iter5_reg;
        icmp_ln703_reg_1724_pp0_iter7_reg <= icmp_ln703_reg_1724_pp0_iter6_reg;
        icmp_ln703_reg_1724_pp0_iter8_reg <= icmp_ln703_reg_1724_pp0_iter7_reg;
        icmp_ln703_reg_1724_pp0_iter9_reg <= icmp_ln703_reg_1724_pp0_iter8_reg;
        log_sum_reg_1884_pp0_iter3_reg <= log_sum_reg_1884;
        log_sum_reg_1884_pp0_iter4_reg <= log_sum_reg_1884_pp0_iter3_reg;
        log_sum_reg_1884_pp0_iter5_reg <= log_sum_reg_1884_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln703_reg_1724_pp0_iter5_reg == 1'd0))) begin
        add_ln779_reg_1933 <= add_ln779_fu_1557_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        ap_phi_reg_pp0_iter10_r_1_reg_399 <= ap_phi_reg_pp0_iter9_r_1_reg_399;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_b_exp_07_reg_328 <= ap_phi_reg_pp0_iter1_b_exp_07_reg_328;
        ap_phi_reg_pp0_iter2_r_1_reg_399 <= ap_phi_reg_pp0_iter1_r_1_reg_399;
        b_frac_05_reg_279 <= ap_phi_reg_pp0_iter1_b_frac_05_reg_279;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_b_exp_07_reg_328 <= ap_phi_reg_pp0_iter2_b_exp_07_reg_328;
        ap_phi_reg_pp0_iter3_r_1_reg_399 <= ap_phi_reg_pp0_iter2_r_1_reg_399;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_phi_reg_pp0_iter4_b_exp_07_reg_328 <= ap_phi_reg_pp0_iter3_b_exp_07_reg_328;
        ap_phi_reg_pp0_iter4_r_1_reg_399 <= ap_phi_reg_pp0_iter3_r_1_reg_399;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_phi_reg_pp0_iter5_b_exp_07_reg_328 <= ap_phi_reg_pp0_iter4_b_exp_07_reg_328;
        ap_phi_reg_pp0_iter5_r_1_reg_399 <= ap_phi_reg_pp0_iter4_r_1_reg_399;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_phi_reg_pp0_iter6_b_exp_07_reg_328 <= ap_phi_reg_pp0_iter5_b_exp_07_reg_328;
        ap_phi_reg_pp0_iter6_r_1_reg_399 <= ap_phi_reg_pp0_iter5_r_1_reg_399;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        ap_phi_reg_pp0_iter7_b_exp_07_reg_328 <= ap_phi_reg_pp0_iter6_b_exp_07_reg_328;
        ap_phi_reg_pp0_iter7_r_1_reg_399 <= ap_phi_reg_pp0_iter6_r_1_reg_399;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_phi_reg_pp0_iter8_b_exp_07_reg_328 <= ap_phi_reg_pp0_iter7_b_exp_07_reg_328;
        ap_phi_reg_pp0_iter8_r_1_reg_399 <= ap_phi_reg_pp0_iter7_r_1_reg_399;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        ap_phi_reg_pp0_iter9_r_1_reg_399 <= ap_phi_reg_pp0_iter8_r_1_reg_399;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln703_reg_1724_pp0_iter1_reg == 1'd0))) begin
        b_frac_tilde_inverse_reg_1879 <= log_apfixed_reduce_log_inverse_lut_table_array_q0;
        log_sum_reg_1884 <= log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln703_reg_1724 <= icmp_ln703_fu_415_p2;
        icmp_ln703_reg_1724_pp0_iter1_reg <= icmp_ln703_reg_1724;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln703_reg_1724_pp0_iter8_reg == 1'd0))) begin
        log_base_reg_1953 <= log_base_fu_1674_p2;
        tmp_50_reg_1958 <= log_base_fu_1674_p2[32'd28];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln703_reg_1724_pp0_iter7_reg == 1'd0))) begin
        lshr_ln_reg_1943 <= {{mul_ln776_fu_1594_p2[17:1]}};
        tmp_47_reg_1938 <= {{grp_fu_1715_p3[28:14]}};
        tmp_49_reg_1948 <= {{mul_ln739_fu_1566_p2[27:6]}};
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to9 = 1'b1;
    end else begin
        ap_idle_pp0_0to9 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln703_reg_1724 == 1'd0)) begin
        if ((tmp_41_fu_1413_p3 == 1'd0)) begin
            ap_phi_mux_index0_2_phi_fu_322_p4 = {{ap_phi_reg_pp0_iter1_b_frac_05_reg_279[26:21]}};
        end else if ((tmp_41_fu_1413_p3 == 1'd1)) begin
            ap_phi_mux_index0_2_phi_fu_322_p4 = {{ap_phi_reg_pp0_iter1_b_frac_05_reg_279[27:22]}};
        end else begin
            ap_phi_mux_index0_2_phi_fu_322_p4 = ap_phi_reg_pp0_iter1_index0_2_reg_319;
        end
    end else begin
        ap_phi_mux_index0_2_phi_fu_322_p4 = ap_phi_reg_pp0_iter1_index0_2_reg_319;
    end
end

always @ (*) begin
    if ((icmp_ln703_reg_1724_pp0_iter9_reg == 1'd0)) begin
        ap_phi_mux_r_1_phi_fu_403_p4 = {{log_base_1_fu_1699_p2[28:14]}};
    end else begin
        ap_phi_mux_r_1_phi_fu_403_p4 = ap_phi_reg_pp0_iter10_r_1_reg_399;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to9 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_ce0 = 1'b1;
    end else begin
        log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        log_apfixed_reduce_log_inverse_lut_table_array_ce0 = 1'b1;
    end else begin
        log_apfixed_reduce_log_inverse_lut_table_array_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_ce0 = 1'b1;
    end else begin
        log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln184_fu_1540_p2 = (zext_ln184_1_fu_1536_p1 + select_ln182_fu_1511_p3);

assign add_ln779_1_fu_1668_p2 = ($signed(sext_ln779_fu_1661_p1) + $signed(sext_ln776_fu_1650_p1));

assign add_ln779_fu_1557_p2 = (zext_ln251_fu_1553_p1 + log_sum_reg_1884_pp0_iter5_reg);

assign and_ln731_10_fu_1149_p3 = {{tmp_31_fu_1139_p4}, {26'd0}};

assign and_ln731_11_fu_1215_p3 = {{tmp_34_fu_1205_p4}, {26'd0}};

assign and_ln731_12_fu_1281_p3 = {{tmp_37_fu_1271_p4}, {26'd0}};

assign and_ln731_1_fu_489_p3 = {{tmp_3_fu_479_p4}, {26'd0}};

assign and_ln731_2_fu_555_p3 = {{tmp_6_fu_545_p4}, {26'd0}};

assign and_ln731_3_fu_621_p3 = {{tmp_9_fu_611_p4}, {26'd0}};

assign and_ln731_4_fu_687_p3 = {{tmp_s_fu_677_p4}, {26'd0}};

assign and_ln731_5_fu_753_p3 = {{tmp_13_fu_743_p4}, {26'd0}};

assign and_ln731_6_fu_819_p3 = {{tmp_16_fu_809_p4}, {26'd0}};

assign and_ln731_7_fu_885_p3 = {{tmp_19_fu_875_p4}, {26'd0}};

assign and_ln731_8_fu_951_p3 = {{tmp_22_fu_941_p4}, {26'd0}};

assign and_ln731_9_fu_1017_p3 = {{tmp_25_fu_1007_p4}, {26'd0}};

assign and_ln731_s_fu_1083_p3 = {{tmp_28_fu_1073_p4}, {26'd0}};

assign and_ln_fu_445_p3 = {{tmp_1_fu_435_p4}, {26'd0}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_222 = ((icmp_ln731_15_fu_1381_p2 == 1'd0) & (select_ln731_13_fu_1365_p3 == 1'd0) & (select_ln731_12_fu_1309_p3 == 1'd0) & (select_ln731_11_fu_1243_p3 == 1'd0) & (select_ln731_10_fu_1177_p3 == 1'd0) & (select_ln731_9_fu_1111_p3 == 1'd0) & (select_ln731_8_fu_1045_p3 == 1'd0) & (select_ln731_7_fu_979_p3 == 1'd0) & (select_ln731_6_fu_913_p3 == 1'd0) & (select_ln731_5_fu_847_p3 == 1'd0) & (select_ln731_4_fu_781_p3 == 1'd0) & (select_ln731_3_fu_715_p3 == 1'd0) & (select_ln731_2_fu_649_p3 == 1'd0) & (select_ln731_1_fu_583_p3 == 1'd0) & (select_ln731_fu_517_p3 == 1'd0) & (icmp_ln731_fu_453_p2 == 1'd0) & (icmp_ln703_fu_415_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_289 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_299 = ((select_ln731_fu_517_p3 == 1'd1) & (icmp_ln731_fu_453_p2 == 1'd0) & (icmp_ln703_fu_415_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_302 = ((select_ln731_1_fu_583_p3 == 1'd1) & (select_ln731_fu_517_p3 == 1'd0) & (icmp_ln731_fu_453_p2 == 1'd0) & (icmp_ln703_fu_415_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_305 = ((select_ln731_2_fu_649_p3 == 1'd1) & (select_ln731_1_fu_583_p3 == 1'd0) & (select_ln731_fu_517_p3 == 1'd0) & (icmp_ln731_fu_453_p2 == 1'd0) & (icmp_ln703_fu_415_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_308 = ((select_ln731_3_fu_715_p3 == 1'd1) & (select_ln731_2_fu_649_p3 == 1'd0) & (select_ln731_1_fu_583_p3 == 1'd0) & (select_ln731_fu_517_p3 == 1'd0) & (icmp_ln731_fu_453_p2 == 1'd0) & (icmp_ln703_fu_415_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_311 = ((select_ln731_4_fu_781_p3 == 1'd1) & (select_ln731_3_fu_715_p3 == 1'd0) & (select_ln731_2_fu_649_p3 == 1'd0) & (select_ln731_1_fu_583_p3 == 1'd0) & (select_ln731_fu_517_p3 == 1'd0) & (icmp_ln731_fu_453_p2 == 1'd0) & (icmp_ln703_fu_415_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_314 = ((select_ln731_5_fu_847_p3 == 1'd1) & (select_ln731_4_fu_781_p3 == 1'd0) & (select_ln731_3_fu_715_p3 == 1'd0) & (select_ln731_2_fu_649_p3 == 1'd0) & (select_ln731_1_fu_583_p3 == 1'd0) & (select_ln731_fu_517_p3 == 1'd0) & (icmp_ln731_fu_453_p2 == 1'd0) & (icmp_ln703_fu_415_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_317 = ((select_ln731_6_fu_913_p3 == 1'd1) & (select_ln731_5_fu_847_p3 == 1'd0) & (select_ln731_4_fu_781_p3 == 1'd0) & (select_ln731_3_fu_715_p3 == 1'd0) & (select_ln731_2_fu_649_p3 == 1'd0) & (select_ln731_1_fu_583_p3 == 1'd0) & (select_ln731_fu_517_p3 == 1'd0) & (icmp_ln731_fu_453_p2 == 1'd0) & (icmp_ln703_fu_415_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_320 = ((select_ln731_7_fu_979_p3 == 1'd1) & (select_ln731_6_fu_913_p3 == 1'd0) & (select_ln731_5_fu_847_p3 == 1'd0) & (select_ln731_4_fu_781_p3 == 1'd0) & (select_ln731_3_fu_715_p3 == 1'd0) & (select_ln731_2_fu_649_p3 == 1'd0) & (select_ln731_1_fu_583_p3 == 1'd0) & (select_ln731_fu_517_p3 == 1'd0) & (icmp_ln731_fu_453_p2 == 1'd0) & (icmp_ln703_fu_415_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_323 = ((select_ln731_8_fu_1045_p3 == 1'd1) & (select_ln731_7_fu_979_p3 == 1'd0) & (select_ln731_6_fu_913_p3 == 1'd0) & (select_ln731_5_fu_847_p3 == 1'd0) & (select_ln731_4_fu_781_p3 == 1'd0) & (select_ln731_3_fu_715_p3 == 1'd0) & (select_ln731_2_fu_649_p3 == 1'd0) & (select_ln731_1_fu_583_p3 == 1'd0) & (select_ln731_fu_517_p3 == 1'd0) & (icmp_ln731_fu_453_p2 == 1'd0) & (icmp_ln703_fu_415_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_326 = ((select_ln731_9_fu_1111_p3 == 1'd1) & (select_ln731_8_fu_1045_p3 == 1'd0) & (select_ln731_7_fu_979_p3 == 1'd0) & (select_ln731_6_fu_913_p3 == 1'd0) & (select_ln731_5_fu_847_p3 == 1'd0) & (select_ln731_4_fu_781_p3 == 1'd0) & (select_ln731_3_fu_715_p3 == 1'd0) & (select_ln731_2_fu_649_p3 == 1'd0) & (select_ln731_1_fu_583_p3 == 1'd0) & (select_ln731_fu_517_p3 == 1'd0) & (icmp_ln731_fu_453_p2 == 1'd0) & (icmp_ln703_fu_415_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_329 = ((select_ln731_10_fu_1177_p3 == 1'd1) & (select_ln731_9_fu_1111_p3 == 1'd0) & (select_ln731_8_fu_1045_p3 == 1'd0) & (select_ln731_7_fu_979_p3 == 1'd0) & (select_ln731_6_fu_913_p3 == 1'd0) & (select_ln731_5_fu_847_p3 == 1'd0) & (select_ln731_4_fu_781_p3 == 1'd0) & (select_ln731_3_fu_715_p3 == 1'd0) & (select_ln731_2_fu_649_p3 == 1'd0) & (select_ln731_1_fu_583_p3 == 1'd0) & (select_ln731_fu_517_p3 == 1'd0) & (icmp_ln731_fu_453_p2 == 1'd0) & (icmp_ln703_fu_415_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_332 = ((select_ln731_11_fu_1243_p3 == 1'd1) & (select_ln731_10_fu_1177_p3 == 1'd0) & (select_ln731_9_fu_1111_p3 == 1'd0) & (select_ln731_8_fu_1045_p3 == 1'd0) & (select_ln731_7_fu_979_p3 == 1'd0) & (select_ln731_6_fu_913_p3 == 1'd0) & (select_ln731_5_fu_847_p3 == 1'd0) & (select_ln731_4_fu_781_p3 == 1'd0) & (select_ln731_3_fu_715_p3 == 1'd0) & (select_ln731_2_fu_649_p3 == 1'd0) & (select_ln731_1_fu_583_p3 == 1'd0) & (select_ln731_fu_517_p3 == 1'd0) & (icmp_ln731_fu_453_p2 == 1'd0) & (icmp_ln703_fu_415_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_335 = ((select_ln731_12_fu_1309_p3 == 1'd1) & (select_ln731_11_fu_1243_p3 == 1'd0) & (select_ln731_10_fu_1177_p3 == 1'd0) & (select_ln731_9_fu_1111_p3 == 1'd0) & (select_ln731_8_fu_1045_p3 == 1'd0) & (select_ln731_7_fu_979_p3 == 1'd0) & (select_ln731_6_fu_913_p3 == 1'd0) & (select_ln731_5_fu_847_p3 == 1'd0) & (select_ln731_4_fu_781_p3 == 1'd0) & (select_ln731_3_fu_715_p3 == 1'd0) & (select_ln731_2_fu_649_p3 == 1'd0) & (select_ln731_1_fu_583_p3 == 1'd0) & (select_ln731_fu_517_p3 == 1'd0) & (icmp_ln731_fu_453_p2 == 1'd0) & (icmp_ln703_fu_415_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_338 = ((select_ln731_13_fu_1365_p3 == 1'd1) & (select_ln731_12_fu_1309_p3 == 1'd0) & (select_ln731_11_fu_1243_p3 == 1'd0) & (select_ln731_10_fu_1177_p3 == 1'd0) & (select_ln731_9_fu_1111_p3 == 1'd0) & (select_ln731_8_fu_1045_p3 == 1'd0) & (select_ln731_7_fu_979_p3 == 1'd0) & (select_ln731_6_fu_913_p3 == 1'd0) & (select_ln731_5_fu_847_p3 == 1'd0) & (select_ln731_4_fu_781_p3 == 1'd0) & (select_ln731_3_fu_715_p3 == 1'd0) & (select_ln731_2_fu_649_p3 == 1'd0) & (select_ln731_1_fu_583_p3 == 1'd0) & (select_ln731_fu_517_p3 == 1'd0) & (icmp_ln731_fu_453_p2 == 1'd0) & (icmp_ln703_fu_415_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_341 = ((icmp_ln731_15_fu_1381_p2 == 1'd1) & (select_ln731_13_fu_1365_p3 == 1'd0) & (select_ln731_12_fu_1309_p3 == 1'd0) & (select_ln731_11_fu_1243_p3 == 1'd0) & (select_ln731_10_fu_1177_p3 == 1'd0) & (select_ln731_9_fu_1111_p3 == 1'd0) & (select_ln731_8_fu_1045_p3 == 1'd0) & (select_ln731_7_fu_979_p3 == 1'd0) & (select_ln731_6_fu_913_p3 == 1'd0) & (select_ln731_5_fu_847_p3 == 1'd0) & (select_ln731_4_fu_781_p3 == 1'd0) & (select_ln731_3_fu_715_p3 == 1'd0) & (select_ln731_2_fu_649_p3 == 1'd0) & (select_ln731_1_fu_583_p3 == 1'd0) & (select_ln731_fu_517_p3 == 1'd0) & (icmp_ln731_fu_453_p2 == 1'd0) & (icmp_ln703_fu_415_p2 == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_b_exp_07_reg_328 = 'bx;

assign ap_phi_reg_pp0_iter0_b_frac_05_reg_279 = 'bx;

assign ap_phi_reg_pp0_iter0_r_1_reg_399 = 'bx;

assign ap_phi_reg_pp0_iter1_index0_2_reg_319 = 'bx;

assign ap_return = ap_phi_mux_r_1_phi_fu_403_p4;

assign b_frac_10_fu_1053_p3 = {{trunc_ln726_8_fu_995_p1}, {22'd0}};

assign b_frac_11_fu_1119_p3 = {{trunc_ln726_9_fu_1061_p1}, {23'd0}};

assign b_frac_12_fu_1185_p3 = {{trunc_ln726_10_fu_1127_p1}, {24'd0}};

assign b_frac_13_fu_1251_p3 = {{trunc_ln726_11_fu_1193_p1}, {25'd0}};

assign b_frac_14_fu_1317_p3 = {{trunc_ln726_13_fu_1259_p1}, {26'd0}};

assign b_frac_15_fu_1373_p3 = {{trunc_ln726_14_fu_1325_p1}, {27'd0}};

assign b_frac_16_fu_1391_p3 = {{trunc_ln733_fu_1387_p1}, {28'd0}};

assign b_frac_1_fu_459_p3 = {{trunc_ln728_fu_421_p1}, {13'd0}};

assign b_frac_2_fu_525_p3 = {{trunc_ln726_fu_467_p1}, {14'd0}};

assign b_frac_3_fu_591_p3 = {{trunc_ln726_1_fu_533_p1}, {15'd0}};

assign b_frac_4_fu_657_p3 = {{trunc_ln726_2_fu_599_p1}, {16'd0}};

assign b_frac_5_fu_723_p3 = {{trunc_ln726_3_fu_665_p1}, {17'd0}};

assign b_frac_6_fu_789_p3 = {{trunc_ln726_4_fu_731_p1}, {18'd0}};

assign b_frac_7_fu_855_p3 = {{trunc_ln726_5_fu_797_p1}, {19'd0}};

assign b_frac_8_fu_921_p3 = {{trunc_ln726_6_fu_863_p1}, {20'd0}};

assign b_frac_9_fu_987_p3 = {{trunc_ln726_7_fu_929_p1}, {21'd0}};

assign b_frac_fu_425_p4 = {{{{1'd0}, {trunc_ln728_fu_421_p1}}}, {12'd0}};

assign grp_fu_1715_p0 = grp_fu_1715_p00;

assign grp_fu_1715_p00 = tmp_42_reg_1901;

assign grp_fu_1715_p1 = grp_fu_1715_p10;

assign grp_fu_1715_p10 = a_reg_1907;

assign grp_fu_410_p1 = grp_fu_410_p10;

assign grp_fu_410_p10 = b_frac_tilde_inverse_reg_1879;

assign icmp_ln703_fu_415_p2 = (($signed(x_val) < $signed(17'd1)) ? 1'b1 : 1'b0);

assign icmp_ln731_10_fu_1091_p2 = ((and_ln731_s_fu_1083_p3 == 28'd201326592) ? 1'b1 : 1'b0);

assign icmp_ln731_11_fu_1157_p2 = ((and_ln731_10_fu_1149_p3 == 28'd201326592) ? 1'b1 : 1'b0);

assign icmp_ln731_12_fu_1223_p2 = ((and_ln731_11_fu_1215_p3 == 28'd201326592) ? 1'b1 : 1'b0);

assign icmp_ln731_13_fu_1289_p2 = ((and_ln731_12_fu_1281_p3 == 28'd201326592) ? 1'b1 : 1'b0);

assign icmp_ln731_14_fu_1345_p2 = ((trunc_ln726_s_fu_1329_p3 == 28'd201326592) ? 1'b1 : 1'b0);

assign icmp_ln731_15_fu_1381_p2 = ((b_frac_15_fu_1373_p3 == 29'd268435456) ? 1'b1 : 1'b0);

assign icmp_ln731_16_fu_1399_p2 = ((b_frac_16_fu_1391_p3 != 29'd0) ? 1'b1 : 1'b0);

assign icmp_ln731_1_fu_497_p2 = ((and_ln731_1_fu_489_p3 == 28'd201326592) ? 1'b1 : 1'b0);

assign icmp_ln731_2_fu_563_p2 = ((and_ln731_2_fu_555_p3 == 28'd201326592) ? 1'b1 : 1'b0);

assign icmp_ln731_3_fu_629_p2 = ((and_ln731_3_fu_621_p3 == 28'd201326592) ? 1'b1 : 1'b0);

assign icmp_ln731_4_fu_695_p2 = ((and_ln731_4_fu_687_p3 == 28'd201326592) ? 1'b1 : 1'b0);

assign icmp_ln731_5_fu_761_p2 = ((and_ln731_5_fu_753_p3 == 28'd201326592) ? 1'b1 : 1'b0);

assign icmp_ln731_6_fu_827_p2 = ((and_ln731_6_fu_819_p3 == 28'd201326592) ? 1'b1 : 1'b0);

assign icmp_ln731_7_fu_893_p2 = ((and_ln731_7_fu_885_p3 == 28'd201326592) ? 1'b1 : 1'b0);

assign icmp_ln731_8_fu_959_p2 = ((and_ln731_8_fu_951_p3 == 28'd201326592) ? 1'b1 : 1'b0);

assign icmp_ln731_9_fu_1025_p2 = ((and_ln731_9_fu_1017_p3 == 28'd201326592) ? 1'b1 : 1'b0);

assign icmp_ln731_fu_453_p2 = ((and_ln_fu_445_p3 == 28'd201326592) ? 1'b1 : 1'b0);

assign log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_address0 = zext_ln756_fu_1443_p1;

assign log_apfixed_reduce_log_inverse_lut_table_array_address0 = zext_ln756_fu_1443_p1;

assign log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_address0 = zext_ln186_fu_1549_p1;

assign log_base_1_fu_1699_p2 = ($signed(log_base_reg_1953) + $signed(sext_ln786_fu_1695_p1));

assign log_base_fu_1674_p2 = ($signed(add_ln779_1_fu_1668_p2) + $signed(sext_ln779_1_fu_1665_p1));

assign mul_ln739_fu_1566_p1 = 28'd2907269;

assign mul_ln776_fu_1594_p0 = zext_ln776_fu_1590_p1;

assign mul_ln776_fu_1594_p1 = zext_ln776_fu_1590_p1;

assign select_ln182_fu_1511_p3 = ((tmp_43_fu_1476_p3[0:0] == 1'b1) ? tmp_45_fu_1500_p3 : zext_ln182_fu_1507_p1);

assign select_ln731_10_fu_1177_p3 = ((tmp_30_fu_1131_p3[0:0] == 1'b1) ? xor_ln731_10_fu_1171_p2 : icmp_ln731_11_fu_1157_p2);

assign select_ln731_11_fu_1243_p3 = ((tmp_33_fu_1197_p3[0:0] == 1'b1) ? xor_ln731_11_fu_1237_p2 : icmp_ln731_12_fu_1223_p2);

assign select_ln731_12_fu_1309_p3 = ((tmp_36_fu_1263_p3[0:0] == 1'b1) ? xor_ln731_12_fu_1303_p2 : icmp_ln731_13_fu_1289_p2);

assign select_ln731_13_fu_1365_p3 = ((tmp_39_fu_1337_p3[0:0] == 1'b1) ? xor_ln731_13_fu_1359_p2 : icmp_ln731_14_fu_1345_p2);

assign select_ln731_14_fu_1405_p3 = ((icmp_ln731_16_fu_1399_p2[0:0] == 1'b1) ? 5'd24 : 5'd23);

assign select_ln731_1_fu_583_p3 = ((tmp_4_fu_537_p3[0:0] == 1'b1) ? xor_ln731_1_fu_577_p2 : icmp_ln731_2_fu_563_p2);

assign select_ln731_2_fu_649_p3 = ((tmp_7_fu_603_p3[0:0] == 1'b1) ? xor_ln731_2_fu_643_p2 : icmp_ln731_3_fu_629_p2);

assign select_ln731_3_fu_715_p3 = ((tmp_10_fu_669_p3[0:0] == 1'b1) ? xor_ln731_3_fu_709_p2 : icmp_ln731_4_fu_695_p2);

assign select_ln731_4_fu_781_p3 = ((tmp_12_fu_735_p3[0:0] == 1'b1) ? xor_ln731_4_fu_775_p2 : icmp_ln731_5_fu_761_p2);

assign select_ln731_5_fu_847_p3 = ((tmp_15_fu_801_p3[0:0] == 1'b1) ? xor_ln731_5_fu_841_p2 : icmp_ln731_6_fu_827_p2);

assign select_ln731_6_fu_913_p3 = ((tmp_18_fu_867_p3[0:0] == 1'b1) ? xor_ln731_6_fu_907_p2 : icmp_ln731_7_fu_893_p2);

assign select_ln731_7_fu_979_p3 = ((tmp_21_fu_933_p3[0:0] == 1'b1) ? xor_ln731_7_fu_973_p2 : icmp_ln731_8_fu_959_p2);

assign select_ln731_8_fu_1045_p3 = ((tmp_24_fu_999_p3[0:0] == 1'b1) ? xor_ln731_8_fu_1039_p2 : icmp_ln731_9_fu_1025_p2);

assign select_ln731_9_fu_1111_p3 = ((tmp_27_fu_1065_p3[0:0] == 1'b1) ? xor_ln731_9_fu_1105_p2 : icmp_ln731_10_fu_1091_p2);

assign select_ln731_fu_517_p3 = ((tmp_fu_471_p3[0:0] == 1'b1) ? xor_ln731_fu_511_p2 : icmp_ln731_1_fu_497_p2);

assign sext_ln776_fu_1650_p1 = $signed(trunc_ln776_1_fu_1640_p4);

assign sext_ln779_1_fu_1665_p1 = $signed(add_ln779_reg_1933_pp0_iter8_reg);

assign sext_ln779_fu_1661_p1 = $signed(shl_ln2_fu_1654_p3);

assign sext_ln786_fu_1695_p1 = $signed(shl_ln3_fu_1688_p3);

assign shl_ln1_fu_1620_p3 = {{tmp_47_reg_1938}, {10'd0}};

assign shl_ln2_fu_1654_p3 = {{tmp_49_reg_1948}, {6'd0}};

assign shl_ln3_fu_1688_p3 = {{tmp_50_reg_1958}, {14'd8192}};

assign shl_ln_fu_1528_p3 = {{tmp_46_fu_1519_p4}, {8'd0}};

assign sub_ln776_fu_1634_p2 = (zext_ln776_1_fu_1627_p1 - zext_ln776_2_fu_1631_p1);

assign tmp_10_fu_669_p3 = x_val[32'd12];

assign tmp_11_fu_701_p3 = x_val[32'd11];

assign tmp_12_fu_735_p3 = x_val[32'd11];

assign tmp_13_fu_743_p4 = {{x_val[10:9]}};

assign tmp_14_fu_767_p3 = x_val[32'd10];

assign tmp_15_fu_801_p3 = x_val[32'd10];

assign tmp_16_fu_809_p4 = {{x_val[9:8]}};

assign tmp_17_fu_833_p3 = x_val[32'd9];

assign tmp_18_fu_867_p3 = x_val[32'd9];

assign tmp_19_fu_875_p4 = {{x_val[8:7]}};

assign tmp_1_fu_435_p4 = {{x_val[15:14]}};

assign tmp_20_fu_899_p3 = x_val[32'd8];

assign tmp_21_fu_933_p3 = x_val[32'd8];

assign tmp_22_fu_941_p4 = {{x_val[7:6]}};

assign tmp_23_fu_965_p3 = x_val[32'd7];

assign tmp_24_fu_999_p3 = x_val[32'd7];

assign tmp_25_fu_1007_p4 = {{x_val[6:5]}};

assign tmp_26_fu_1031_p3 = x_val[32'd6];

assign tmp_27_fu_1065_p3 = x_val[32'd6];

assign tmp_28_fu_1073_p4 = {{x_val[5:4]}};

assign tmp_29_fu_1097_p3 = x_val[32'd5];

assign tmp_2_fu_503_p3 = x_val[32'd14];

assign tmp_30_fu_1131_p3 = x_val[32'd5];

assign tmp_31_fu_1139_p4 = {{x_val[4:3]}};

assign tmp_32_fu_1163_p3 = x_val[32'd4];

assign tmp_33_fu_1197_p3 = x_val[32'd4];

assign tmp_34_fu_1205_p4 = {{x_val[3:2]}};

assign tmp_35_fu_1229_p3 = x_val[32'd3];

assign tmp_36_fu_1263_p3 = x_val[32'd3];

assign tmp_37_fu_1271_p4 = {{x_val[2:1]}};

assign tmp_38_fu_1295_p3 = x_val[32'd2];

assign tmp_39_fu_1337_p3 = x_val[32'd2];

assign tmp_3_fu_479_p4 = {{x_val[14:13]}};

assign tmp_40_fu_1351_p3 = x_val[32'd1];

assign tmp_41_fu_1413_p3 = ap_phi_reg_pp0_iter1_b_frac_05_reg_279[32'd28];

assign tmp_43_fu_1476_p3 = mul_ln761_reg_1894[32'd28];

assign tmp_44_fu_1483_p4 = {{mul_ln761_reg_1894[28:6]}};

assign tmp_45_fu_1500_p3 = {{5'd16}, {tmp_42_reg_1901}};

assign tmp_46_fu_1519_p4 = {{mul_ln761_reg_1894[24:5]}};

assign tmp_48_fu_1581_p4 = {{grp_fu_1715_p3[28:20]}};

assign tmp_4_fu_537_p3 = x_val[32'd14];

assign tmp_5_fu_569_p3 = x_val[32'd13];

assign tmp_6_fu_545_p4 = {{x_val[13:12]}};

assign tmp_7_fu_603_p3 = x_val[32'd13];

assign tmp_8_fu_635_p3 = x_val[32'd12];

assign tmp_9_fu_611_p4 = {{x_val[12:11]}};

assign tmp_fu_471_p3 = x_val[32'd15];

assign tmp_s_fu_677_p4 = {{x_val[11:10]}};

assign trunc_ln726_10_fu_1127_p1 = x_val[4:0];

assign trunc_ln726_11_fu_1193_p1 = x_val[3:0];

assign trunc_ln726_13_fu_1259_p1 = x_val[2:0];

assign trunc_ln726_14_fu_1325_p1 = x_val[1:0];

assign trunc_ln726_1_fu_533_p1 = x_val[13:0];

assign trunc_ln726_2_fu_599_p1 = x_val[12:0];

assign trunc_ln726_3_fu_665_p1 = x_val[11:0];

assign trunc_ln726_4_fu_731_p1 = x_val[10:0];

assign trunc_ln726_5_fu_797_p1 = x_val[9:0];

assign trunc_ln726_6_fu_863_p1 = x_val[8:0];

assign trunc_ln726_7_fu_929_p1 = x_val[7:0];

assign trunc_ln726_8_fu_995_p1 = x_val[6:0];

assign trunc_ln726_9_fu_1061_p1 = x_val[5:0];

assign trunc_ln726_fu_467_p1 = x_val[14:0];

assign trunc_ln726_s_fu_1329_p3 = {{trunc_ln726_14_fu_1325_p1}, {26'd0}};

assign trunc_ln728_fu_421_p1 = x_val[15:0];

assign trunc_ln733_fu_1387_p1 = x_val[0:0];

assign trunc_ln776_1_fu_1640_p4 = {{sub_ln776_fu_1634_p2[25:10]}};

assign xor_ln731_10_fu_1171_p2 = (tmp_32_fu_1163_p3 ^ 1'd1);

assign xor_ln731_11_fu_1237_p2 = (tmp_35_fu_1229_p3 ^ 1'd1);

assign xor_ln731_12_fu_1303_p2 = (tmp_38_fu_1295_p3 ^ 1'd1);

assign xor_ln731_13_fu_1359_p2 = (tmp_40_fu_1351_p3 ^ 1'd1);

assign xor_ln731_1_fu_577_p2 = (tmp_5_fu_569_p3 ^ 1'd1);

assign xor_ln731_2_fu_643_p2 = (tmp_8_fu_635_p3 ^ 1'd1);

assign xor_ln731_3_fu_709_p2 = (tmp_11_fu_701_p3 ^ 1'd1);

assign xor_ln731_4_fu_775_p2 = (tmp_14_fu_767_p3 ^ 1'd1);

assign xor_ln731_5_fu_841_p2 = (tmp_17_fu_833_p3 ^ 1'd1);

assign xor_ln731_6_fu_907_p2 = (tmp_20_fu_899_p3 ^ 1'd1);

assign xor_ln731_7_fu_973_p2 = (tmp_23_fu_965_p3 ^ 1'd1);

assign xor_ln731_8_fu_1039_p2 = (tmp_26_fu_1031_p3 ^ 1'd1);

assign xor_ln731_9_fu_1105_p2 = (tmp_29_fu_1097_p3 ^ 1'd1);

assign xor_ln731_fu_511_p2 = (tmp_2_fu_503_p3 ^ 1'd1);

assign zext_ln182_cast_fu_1492_p3 = {{5'd16}, {tmp_44_fu_1483_p4}};

assign zext_ln182_fu_1507_p1 = zext_ln182_cast_fu_1492_p3;

assign zext_ln184_1_fu_1536_p1 = shl_ln_fu_1528_p3;

assign zext_ln186_fu_1549_p1 = a_reg_1907;

assign zext_ln251_fu_1553_p1 = log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_q0;

assign zext_ln756_fu_1443_p1 = ap_phi_mux_index0_2_phi_fu_322_p4;

assign zext_ln776_1_fu_1627_p1 = shl_ln1_fu_1620_p3;

assign zext_ln776_2_fu_1631_p1 = lshr_ln_reg_1943;

assign zext_ln776_fu_1590_p1 = tmp_48_fu_1581_p4;

endmodule //mfcc_log_17_9_s
