// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mfcc_mfcc_Pipeline_task_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_stream_TVALID,
        abs_spectrogram_14_address0,
        abs_spectrogram_14_ce0,
        abs_spectrogram_14_we0,
        abs_spectrogram_14_d0,
        abs_spectrogram_13_address0,
        abs_spectrogram_13_ce0,
        abs_spectrogram_13_we0,
        abs_spectrogram_13_d0,
        abs_spectrogram_12_address0,
        abs_spectrogram_12_ce0,
        abs_spectrogram_12_we0,
        abs_spectrogram_12_d0,
        abs_spectrogram_11_address0,
        abs_spectrogram_11_ce0,
        abs_spectrogram_11_we0,
        abs_spectrogram_11_d0,
        abs_spectrogram_10_address0,
        abs_spectrogram_10_ce0,
        abs_spectrogram_10_we0,
        abs_spectrogram_10_d0,
        abs_spectrogram_9_address0,
        abs_spectrogram_9_ce0,
        abs_spectrogram_9_we0,
        abs_spectrogram_9_d0,
        abs_spectrogram_8_address0,
        abs_spectrogram_8_ce0,
        abs_spectrogram_8_we0,
        abs_spectrogram_8_d0,
        abs_spectrogram_7_address0,
        abs_spectrogram_7_ce0,
        abs_spectrogram_7_we0,
        abs_spectrogram_7_d0,
        abs_spectrogram_6_address0,
        abs_spectrogram_6_ce0,
        abs_spectrogram_6_we0,
        abs_spectrogram_6_d0,
        abs_spectrogram_5_address0,
        abs_spectrogram_5_ce0,
        abs_spectrogram_5_we0,
        abs_spectrogram_5_d0,
        abs_spectrogram_4_address0,
        abs_spectrogram_4_ce0,
        abs_spectrogram_4_we0,
        abs_spectrogram_4_d0,
        abs_spectrogram_3_address0,
        abs_spectrogram_3_ce0,
        abs_spectrogram_3_we0,
        abs_spectrogram_3_d0,
        abs_spectrogram_2_address0,
        abs_spectrogram_2_ce0,
        abs_spectrogram_2_we0,
        abs_spectrogram_2_d0,
        abs_spectrogram_1_address0,
        abs_spectrogram_1_ce0,
        abs_spectrogram_1_we0,
        abs_spectrogram_1_d0,
        abs_spectrogram_address0,
        abs_spectrogram_ce0,
        abs_spectrogram_we0,
        abs_spectrogram_d0,
        in_stream_TDATA,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_stream_TVALID;
output  [4:0] abs_spectrogram_14_address0;
output   abs_spectrogram_14_ce0;
output   abs_spectrogram_14_we0;
output  [15:0] abs_spectrogram_14_d0;
output  [4:0] abs_spectrogram_13_address0;
output   abs_spectrogram_13_ce0;
output   abs_spectrogram_13_we0;
output  [15:0] abs_spectrogram_13_d0;
output  [4:0] abs_spectrogram_12_address0;
output   abs_spectrogram_12_ce0;
output   abs_spectrogram_12_we0;
output  [15:0] abs_spectrogram_12_d0;
output  [4:0] abs_spectrogram_11_address0;
output   abs_spectrogram_11_ce0;
output   abs_spectrogram_11_we0;
output  [15:0] abs_spectrogram_11_d0;
output  [4:0] abs_spectrogram_10_address0;
output   abs_spectrogram_10_ce0;
output   abs_spectrogram_10_we0;
output  [15:0] abs_spectrogram_10_d0;
output  [4:0] abs_spectrogram_9_address0;
output   abs_spectrogram_9_ce0;
output   abs_spectrogram_9_we0;
output  [15:0] abs_spectrogram_9_d0;
output  [4:0] abs_spectrogram_8_address0;
output   abs_spectrogram_8_ce0;
output   abs_spectrogram_8_we0;
output  [15:0] abs_spectrogram_8_d0;
output  [4:0] abs_spectrogram_7_address0;
output   abs_spectrogram_7_ce0;
output   abs_spectrogram_7_we0;
output  [15:0] abs_spectrogram_7_d0;
output  [4:0] abs_spectrogram_6_address0;
output   abs_spectrogram_6_ce0;
output   abs_spectrogram_6_we0;
output  [15:0] abs_spectrogram_6_d0;
output  [4:0] abs_spectrogram_5_address0;
output   abs_spectrogram_5_ce0;
output   abs_spectrogram_5_we0;
output  [15:0] abs_spectrogram_5_d0;
output  [4:0] abs_spectrogram_4_address0;
output   abs_spectrogram_4_ce0;
output   abs_spectrogram_4_we0;
output  [15:0] abs_spectrogram_4_d0;
output  [4:0] abs_spectrogram_3_address0;
output   abs_spectrogram_3_ce0;
output   abs_spectrogram_3_we0;
output  [15:0] abs_spectrogram_3_d0;
output  [4:0] abs_spectrogram_2_address0;
output   abs_spectrogram_2_ce0;
output   abs_spectrogram_2_we0;
output  [15:0] abs_spectrogram_2_d0;
output  [4:0] abs_spectrogram_1_address0;
output   abs_spectrogram_1_ce0;
output   abs_spectrogram_1_we0;
output  [15:0] abs_spectrogram_1_d0;
output  [4:0] abs_spectrogram_address0;
output   abs_spectrogram_ce0;
output   abs_spectrogram_we0;
output  [15:0] abs_spectrogram_d0;
input  [15:0] in_stream_TDATA;
output   in_stream_TREADY;
input  [1:0] in_stream_TKEEP;
input  [1:0] in_stream_TSTRB;
input  [0:0] in_stream_TLAST;

reg ap_idle;
reg abs_spectrogram_14_ce0;
reg abs_spectrogram_14_we0;
reg abs_spectrogram_13_ce0;
reg abs_spectrogram_13_we0;
reg abs_spectrogram_12_ce0;
reg abs_spectrogram_12_we0;
reg abs_spectrogram_11_ce0;
reg abs_spectrogram_11_we0;
reg abs_spectrogram_10_ce0;
reg abs_spectrogram_10_we0;
reg abs_spectrogram_9_ce0;
reg abs_spectrogram_9_we0;
reg abs_spectrogram_8_ce0;
reg abs_spectrogram_8_we0;
reg abs_spectrogram_7_ce0;
reg abs_spectrogram_7_we0;
reg abs_spectrogram_6_ce0;
reg abs_spectrogram_6_we0;
reg abs_spectrogram_5_ce0;
reg abs_spectrogram_5_we0;
reg abs_spectrogram_4_ce0;
reg abs_spectrogram_4_we0;
reg abs_spectrogram_3_ce0;
reg abs_spectrogram_3_we0;
reg abs_spectrogram_2_ce0;
reg abs_spectrogram_2_we0;
reg abs_spectrogram_1_ce0;
reg abs_spectrogram_1_we0;
reg abs_spectrogram_ce0;
reg abs_spectrogram_we0;
reg in_stream_TREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln41_fu_358_p2;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln44_fu_389_p1;
reg   [8:0] phi_urem_fu_118;
wire   [8:0] select_ln41_fu_443_p3;
reg    ap_block_pp0_stage0_11001;
wire    ap_loop_init;
reg   [17:0] phi_mul_fu_122;
wire   [17:0] add_ln44_fu_373_p2;
reg   [8:0] i_fu_126;
wire   [8:0] add_ln41_fu_364_p2;
wire   [3:0] trunc_ln44_fu_408_p1;
wire   [4:0] tmp_fu_379_p4;
wire   [8:0] add_ln41_1_fu_431_p2;
wire   [0:0] icmp_ln41_1_fu_437_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

mfcc_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_126 <= 9'd0;
        end else if (((icmp_ln41_fu_358_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_fu_126 <= add_ln41_fu_364_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            phi_mul_fu_122 <= 18'd0;
        end else if (((icmp_ln41_fu_358_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            phi_mul_fu_122 <= add_ln44_fu_373_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            phi_urem_fu_118 <= 9'd0;
        end else if (((icmp_ln41_fu_358_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            phi_urem_fu_118 <= select_ln41_fu_443_p3;
        end
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        abs_spectrogram_10_ce0 = 1'b1;
    end else begin
        abs_spectrogram_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln44_fu_408_p1 == 4'd10) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln41_fu_358_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        abs_spectrogram_10_we0 = 1'b1;
    end else begin
        abs_spectrogram_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        abs_spectrogram_11_ce0 = 1'b1;
    end else begin
        abs_spectrogram_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln44_fu_408_p1 == 4'd11) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln41_fu_358_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        abs_spectrogram_11_we0 = 1'b1;
    end else begin
        abs_spectrogram_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        abs_spectrogram_12_ce0 = 1'b1;
    end else begin
        abs_spectrogram_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln44_fu_408_p1 == 4'd12) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln41_fu_358_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        abs_spectrogram_12_we0 = 1'b1;
    end else begin
        abs_spectrogram_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        abs_spectrogram_13_ce0 = 1'b1;
    end else begin
        abs_spectrogram_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln44_fu_408_p1 == 4'd13) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln41_fu_358_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        abs_spectrogram_13_we0 = 1'b1;
    end else begin
        abs_spectrogram_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        abs_spectrogram_14_ce0 = 1'b1;
    end else begin
        abs_spectrogram_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((trunc_ln44_fu_408_p1 == 4'd14) & (icmp_ln41_fu_358_p2 == 1'd0)) | ((trunc_ln44_fu_408_p1 == 4'd15) & (icmp_ln41_fu_358_p2 == 1'd0))))) begin
        abs_spectrogram_14_we0 = 1'b1;
    end else begin
        abs_spectrogram_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        abs_spectrogram_1_ce0 = 1'b1;
    end else begin
        abs_spectrogram_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln44_fu_408_p1 == 4'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln41_fu_358_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        abs_spectrogram_1_we0 = 1'b1;
    end else begin
        abs_spectrogram_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        abs_spectrogram_2_ce0 = 1'b1;
    end else begin
        abs_spectrogram_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln44_fu_408_p1 == 4'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln41_fu_358_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        abs_spectrogram_2_we0 = 1'b1;
    end else begin
        abs_spectrogram_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        abs_spectrogram_3_ce0 = 1'b1;
    end else begin
        abs_spectrogram_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln44_fu_408_p1 == 4'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln41_fu_358_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        abs_spectrogram_3_we0 = 1'b1;
    end else begin
        abs_spectrogram_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        abs_spectrogram_4_ce0 = 1'b1;
    end else begin
        abs_spectrogram_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln44_fu_408_p1 == 4'd4) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln41_fu_358_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        abs_spectrogram_4_we0 = 1'b1;
    end else begin
        abs_spectrogram_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        abs_spectrogram_5_ce0 = 1'b1;
    end else begin
        abs_spectrogram_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln44_fu_408_p1 == 4'd5) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln41_fu_358_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        abs_spectrogram_5_we0 = 1'b1;
    end else begin
        abs_spectrogram_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        abs_spectrogram_6_ce0 = 1'b1;
    end else begin
        abs_spectrogram_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln44_fu_408_p1 == 4'd6) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln41_fu_358_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        abs_spectrogram_6_we0 = 1'b1;
    end else begin
        abs_spectrogram_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        abs_spectrogram_7_ce0 = 1'b1;
    end else begin
        abs_spectrogram_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln44_fu_408_p1 == 4'd7) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln41_fu_358_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        abs_spectrogram_7_we0 = 1'b1;
    end else begin
        abs_spectrogram_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        abs_spectrogram_8_ce0 = 1'b1;
    end else begin
        abs_spectrogram_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln44_fu_408_p1 == 4'd8) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln41_fu_358_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        abs_spectrogram_8_we0 = 1'b1;
    end else begin
        abs_spectrogram_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        abs_spectrogram_9_ce0 = 1'b1;
    end else begin
        abs_spectrogram_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln44_fu_408_p1 == 4'd9) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln41_fu_358_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        abs_spectrogram_9_we0 = 1'b1;
    end else begin
        abs_spectrogram_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        abs_spectrogram_ce0 = 1'b1;
    end else begin
        abs_spectrogram_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln44_fu_408_p1 == 4'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln41_fu_358_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        abs_spectrogram_we0 = 1'b1;
    end else begin
        abs_spectrogram_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln41_fu_358_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln41_fu_358_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln41_fu_358_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_TREADY = 1'b1;
    end else begin
        in_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign abs_spectrogram_10_address0 = zext_ln44_fu_389_p1;

assign abs_spectrogram_10_d0 = in_stream_TDATA;

assign abs_spectrogram_11_address0 = zext_ln44_fu_389_p1;

assign abs_spectrogram_11_d0 = in_stream_TDATA;

assign abs_spectrogram_12_address0 = zext_ln44_fu_389_p1;

assign abs_spectrogram_12_d0 = in_stream_TDATA;

assign abs_spectrogram_13_address0 = zext_ln44_fu_389_p1;

assign abs_spectrogram_13_d0 = in_stream_TDATA;

assign abs_spectrogram_14_address0 = zext_ln44_fu_389_p1;

assign abs_spectrogram_14_d0 = in_stream_TDATA;

assign abs_spectrogram_1_address0 = zext_ln44_fu_389_p1;

assign abs_spectrogram_1_d0 = in_stream_TDATA;

assign abs_spectrogram_2_address0 = zext_ln44_fu_389_p1;

assign abs_spectrogram_2_d0 = in_stream_TDATA;

assign abs_spectrogram_3_address0 = zext_ln44_fu_389_p1;

assign abs_spectrogram_3_d0 = in_stream_TDATA;

assign abs_spectrogram_4_address0 = zext_ln44_fu_389_p1;

assign abs_spectrogram_4_d0 = in_stream_TDATA;

assign abs_spectrogram_5_address0 = zext_ln44_fu_389_p1;

assign abs_spectrogram_5_d0 = in_stream_TDATA;

assign abs_spectrogram_6_address0 = zext_ln44_fu_389_p1;

assign abs_spectrogram_6_d0 = in_stream_TDATA;

assign abs_spectrogram_7_address0 = zext_ln44_fu_389_p1;

assign abs_spectrogram_7_d0 = in_stream_TDATA;

assign abs_spectrogram_8_address0 = zext_ln44_fu_389_p1;

assign abs_spectrogram_8_d0 = in_stream_TDATA;

assign abs_spectrogram_9_address0 = zext_ln44_fu_389_p1;

assign abs_spectrogram_9_d0 = in_stream_TDATA;

assign abs_spectrogram_address0 = zext_ln44_fu_389_p1;

assign abs_spectrogram_d0 = in_stream_TDATA;

assign add_ln41_1_fu_431_p2 = (phi_urem_fu_118 + 9'd1);

assign add_ln41_fu_364_p2 = (i_fu_126 + 9'd1);

assign add_ln44_fu_373_p2 = (phi_mul_fu_122 + 18'd547);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((icmp_ln41_fu_358_p2 == 1'd0) & (in_stream_TVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((icmp_ln41_fu_358_p2 == 1'd0) & (in_stream_TVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((icmp_ln41_fu_358_p2 == 1'd0) & (in_stream_TVALID == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign icmp_ln41_1_fu_437_p2 = ((add_ln41_1_fu_431_p2 < 9'd15) ? 1'b1 : 1'b0);

assign icmp_ln41_fu_358_p2 = ((i_fu_126 == 9'd257) ? 1'b1 : 1'b0);

assign select_ln41_fu_443_p3 = ((icmp_ln41_1_fu_437_p2[0:0] == 1'b1) ? add_ln41_1_fu_431_p2 : 9'd0);

assign tmp_fu_379_p4 = {{phi_mul_fu_122[17:13]}};

assign trunc_ln44_fu_408_p1 = phi_urem_fu_118[3:0];

assign zext_ln44_fu_389_p1 = tmp_fu_379_p4;

endmodule //mfcc_mfcc_Pipeline_task_3
