// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mfcc_mfcc_Pipeline_VITIS_LOOP_202_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mfcc_1_address0,
        mfcc_1_ce0,
        mfcc_1_we0,
        mfcc_1_d0,
        mel_filtered_address0,
        mel_filtered_ce0,
        mel_filtered_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] mfcc_1_address0;
output   mfcc_1_ce0;
output   mfcc_1_we0;
output  [14:0] mfcc_1_d0;
output  [5:0] mel_filtered_address0;
output   mel_filtered_ce0;
input  [15:0] mel_filtered_q0;

reg ap_idle;
reg mfcc_1_ce0;
reg mfcc_1_we0;
reg mel_filtered_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln202_fu_460_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [5:0] log_apfixed_reduce_log_inverse_lut_table_array_address0;
reg    log_apfixed_reduce_log_inverse_lut_table_array_ce0;
wire   [5:0] log_apfixed_reduce_log_inverse_lut_table_array_q0;
wire   [5:0] log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_address0;
reg    log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_ce0;
wire   [21:0] log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_q0;
wire   [3:0] log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_address0;
reg    log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_ce0;
wire   [17:0] log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_q0;
reg  signed [28:0] b_frac_05_i_reg_313;
reg  signed [28:0] b_frac_05_i_reg_313_pp0_iter4_reg;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln202_reg_1743;
reg   [0:0] icmp_ln202_reg_1743_pp0_iter1_reg;
reg   [0:0] icmp_ln202_reg_1743_pp0_iter2_reg;
reg   [0:0] icmp_ln202_reg_1743_pp0_iter3_reg;
reg   [0:0] icmp_ln202_reg_1743_pp0_iter4_reg;
reg   [0:0] icmp_ln202_reg_1743_pp0_iter5_reg;
reg   [0:0] icmp_ln202_reg_1743_pp0_iter6_reg;
reg   [0:0] icmp_ln202_reg_1743_pp0_iter7_reg;
reg   [0:0] icmp_ln202_reg_1743_pp0_iter8_reg;
reg   [0:0] icmp_ln202_reg_1743_pp0_iter9_reg;
reg   [0:0] icmp_ln202_reg_1743_pp0_iter10_reg;
reg   [0:0] icmp_ln202_reg_1743_pp0_iter11_reg;
wire   [63:0] zext_ln202_fu_472_p1;
reg   [63:0] zext_ln202_reg_1747;
reg   [63:0] zext_ln202_reg_1747_pp0_iter1_reg;
reg   [63:0] zext_ln202_reg_1747_pp0_iter2_reg;
reg   [63:0] zext_ln202_reg_1747_pp0_iter3_reg;
reg   [63:0] zext_ln202_reg_1747_pp0_iter4_reg;
reg   [63:0] zext_ln202_reg_1747_pp0_iter5_reg;
reg   [63:0] zext_ln202_reg_1747_pp0_iter6_reg;
reg   [63:0] zext_ln202_reg_1747_pp0_iter7_reg;
reg   [63:0] zext_ln202_reg_1747_pp0_iter8_reg;
reg   [63:0] zext_ln202_reg_1747_pp0_iter9_reg;
reg   [63:0] zext_ln202_reg_1747_pp0_iter10_reg;
reg   [63:0] zext_ln202_reg_1747_pp0_iter11_reg;
wire   [15:0] x_fu_482_p2;
reg   [15:0] x_reg_1757;
wire   [0:0] tmp_1_fu_488_p3;
reg   [0:0] tmp_1_reg_1820;
reg   [0:0] tmp_1_reg_1820_pp0_iter2_reg;
reg   [0:0] tmp_1_reg_1820_pp0_iter3_reg;
reg   [0:0] tmp_1_reg_1820_pp0_iter4_reg;
reg   [0:0] tmp_1_reg_1820_pp0_iter5_reg;
reg   [0:0] tmp_1_reg_1820_pp0_iter6_reg;
reg   [0:0] tmp_1_reg_1820_pp0_iter7_reg;
reg   [0:0] tmp_1_reg_1820_pp0_iter8_reg;
reg   [0:0] tmp_1_reg_1820_pp0_iter9_reg;
reg   [0:0] tmp_1_reg_1820_pp0_iter10_reg;
reg   [0:0] tmp_1_reg_1820_pp0_iter11_reg;
wire   [28:0] b_frac_fu_496_p4;
wire   [0:0] icmp_ln731_fu_522_p2;
wire   [28:0] b_frac_1_fu_528_p3;
wire   [0:0] select_ln731_fu_581_p3;
wire   [28:0] b_frac_2_fu_589_p3;
wire   [0:0] select_ln731_1_fu_643_p3;
wire   [28:0] b_frac_3_fu_651_p3;
wire   [0:0] select_ln731_2_fu_705_p3;
wire   [28:0] b_frac_4_fu_713_p3;
wire   [0:0] select_ln731_3_fu_767_p3;
wire   [28:0] b_frac_5_fu_775_p3;
wire   [0:0] select_ln731_4_fu_829_p3;
wire   [28:0] b_frac_6_fu_837_p3;
wire   [0:0] select_ln731_5_fu_891_p3;
wire   [28:0] b_frac_7_fu_899_p3;
wire   [0:0] select_ln731_6_fu_953_p3;
wire   [28:0] b_frac_8_fu_961_p3;
wire   [0:0] select_ln731_7_fu_1015_p3;
wire   [28:0] b_frac_9_fu_1023_p3;
wire   [0:0] select_ln731_8_fu_1077_p3;
wire   [28:0] b_frac_10_fu_1085_p3;
wire   [0:0] select_ln731_9_fu_1139_p3;
wire   [28:0] b_frac_11_fu_1147_p3;
wire   [0:0] select_ln731_10_fu_1201_p3;
wire   [28:0] b_frac_12_fu_1209_p3;
wire   [0:0] select_ln731_11_fu_1263_p3;
wire   [28:0] b_frac_13_fu_1271_p3;
wire   [0:0] select_ln731_12_fu_1325_p3;
wire   [28:0] b_frac_14_fu_1333_p3;
wire   [0:0] select_ln731_13_fu_1378_p3;
wire   [0:0] icmp_ln731_15_fu_1394_p2;
wire   [28:0] b_frac_16_fu_1403_p3;
wire   [4:0] select_ln731_14_fu_1417_p3;
wire   [0:0] tmp_44_fu_1425_p3;
reg   [5:0] b_frac_tilde_inverse_reg_1987;
reg   [21:0] log_sum_reg_1992;
reg   [21:0] log_sum_reg_1992_pp0_iter5_reg;
reg   [21:0] log_sum_reg_1992_pp0_iter6_reg;
reg   [21:0] log_sum_reg_1992_pp0_iter7_reg;
wire   [28:0] grp_fu_447_p2;
reg   [28:0] mul_ln761_reg_2002;
reg   [23:0] tmp_38_reg_2009;
reg   [3:0] a_reg_2015;
(* use_dsp48 = "no" *) wire   [28:0] add_ln184_fu_1552_p2;
reg   [28:0] add_ln184_reg_2026;
reg   [28:0] add_ln184_reg_2026_pp0_iter8_reg;
wire   [21:0] add_ln779_fu_1569_p2;
reg   [21:0] add_ln779_reg_2041;
reg   [21:0] add_ln779_reg_2041_pp0_iter9_reg;
reg   [21:0] add_ln779_reg_2041_pp0_iter10_reg;
reg   [14:0] tmp_47_reg_2046;
reg   [16:0] lshr_ln_reg_2051;
reg   [21:0] tmp_49_reg_2056;
wire   [28:0] log_base_fu_1686_p2;
reg   [28:0] log_base_reg_2061;
reg   [0:0] tmp_52_reg_2066;
wire  signed [28:0] ap_phi_reg_pp0_iter0_b_frac_05_i_reg_313;
reg  signed [28:0] ap_phi_reg_pp0_iter1_b_frac_05_i_reg_313;
reg  signed [28:0] ap_phi_reg_pp0_iter2_b_frac_05_i_reg_313;
reg  signed [28:0] ap_phi_reg_pp0_iter3_b_frac_05_i_reg_313;
reg   [5:0] ap_phi_mux_index0_2_phi_fu_358_p4;
wire   [5:0] ap_phi_reg_pp0_iter3_index0_2_reg_355;
wire   [4:0] ap_phi_reg_pp0_iter0_b_exp_07_i_reg_364;
reg   [4:0] ap_phi_reg_pp0_iter1_b_exp_07_i_reg_364;
reg   [4:0] ap_phi_reg_pp0_iter2_b_exp_07_i_reg_364;
reg   [4:0] ap_phi_reg_pp0_iter3_b_exp_07_i_reg_364;
reg   [4:0] ap_phi_reg_pp0_iter4_b_exp_07_i_reg_364;
reg   [4:0] ap_phi_reg_pp0_iter5_b_exp_07_i_reg_364;
reg   [4:0] ap_phi_reg_pp0_iter6_b_exp_07_i_reg_364;
reg   [4:0] ap_phi_reg_pp0_iter7_b_exp_07_i_reg_364;
reg   [4:0] ap_phi_reg_pp0_iter8_b_exp_07_i_reg_364;
reg   [4:0] ap_phi_reg_pp0_iter9_b_exp_07_i_reg_364;
reg  signed [4:0] ap_phi_reg_pp0_iter10_b_exp_07_i_reg_364;
reg   [14:0] ap_phi_mux_phi_ln205_phi_fu_439_p4;
reg   [14:0] ap_phi_reg_pp0_iter12_phi_ln205_reg_435;
wire   [14:0] ap_phi_reg_pp0_iter0_phi_ln205_reg_435;
reg   [14:0] ap_phi_reg_pp0_iter1_phi_ln205_reg_435;
reg   [14:0] ap_phi_reg_pp0_iter2_phi_ln205_reg_435;
reg   [14:0] ap_phi_reg_pp0_iter3_phi_ln205_reg_435;
reg   [14:0] ap_phi_reg_pp0_iter4_phi_ln205_reg_435;
reg   [14:0] ap_phi_reg_pp0_iter5_phi_ln205_reg_435;
reg   [14:0] ap_phi_reg_pp0_iter6_phi_ln205_reg_435;
reg   [14:0] ap_phi_reg_pp0_iter7_phi_ln205_reg_435;
reg   [14:0] ap_phi_reg_pp0_iter8_phi_ln205_reg_435;
reg   [14:0] ap_phi_reg_pp0_iter9_phi_ln205_reg_435;
reg   [14:0] ap_phi_reg_pp0_iter10_phi_ln205_reg_435;
reg   [14:0] ap_phi_reg_pp0_iter11_phi_ln205_reg_435;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln756_fu_1455_p1;
wire   [63:0] zext_ln186_fu_1561_p1;
reg   [5:0] m_fu_244;
wire   [5:0] add_ln202_fu_466_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_m_2;
wire   [5:0] grp_fu_447_p1;
wire   [1:0] tmp_fu_505_p4;
wire   [27:0] and_ln_fu_514_p3;
wire   [1:0] tmp_2_fu_545_p4;
wire   [27:0] and_ln731_1_fu_554_p3;
wire   [0:0] tmp_4_fu_568_p3;
wire   [0:0] tmp_3_fu_538_p3;
wire   [0:0] xor_ln731_fu_575_p2;
wire   [0:0] icmp_ln731_1_fu_562_p2;
wire   [14:0] trunc_ln726_fu_535_p1;
wire   [1:0] tmp_5_fu_607_p4;
wire   [27:0] and_ln731_2_fu_616_p3;
wire   [0:0] tmp_7_fu_630_p3;
wire   [0:0] tmp_6_fu_600_p3;
wire   [0:0] xor_ln731_1_fu_637_p2;
wire   [0:0] icmp_ln731_2_fu_624_p2;
wire   [13:0] trunc_ln726_1_fu_597_p1;
wire   [1:0] tmp_8_fu_669_p4;
wire   [27:0] and_ln731_3_fu_678_p3;
wire   [0:0] tmp_10_fu_692_p3;
wire   [0:0] tmp_9_fu_662_p3;
wire   [0:0] xor_ln731_2_fu_699_p2;
wire   [0:0] icmp_ln731_3_fu_686_p2;
wire   [12:0] trunc_ln726_2_fu_659_p1;
wire   [1:0] tmp_s_fu_731_p4;
wire   [27:0] and_ln731_4_fu_740_p3;
wire   [0:0] tmp_13_fu_754_p3;
wire   [0:0] tmp_12_fu_724_p3;
wire   [0:0] xor_ln731_3_fu_761_p2;
wire   [0:0] icmp_ln731_4_fu_748_p2;
wire   [11:0] trunc_ln726_3_fu_721_p1;
wire   [1:0] tmp_11_fu_793_p4;
wire   [27:0] and_ln731_5_fu_802_p3;
wire   [0:0] tmp_16_fu_816_p3;
wire   [0:0] tmp_15_fu_786_p3;
wire   [0:0] xor_ln731_4_fu_823_p2;
wire   [0:0] icmp_ln731_5_fu_810_p2;
wire   [10:0] trunc_ln726_4_fu_783_p1;
wire   [1:0] tmp_14_fu_855_p4;
wire   [27:0] and_ln731_6_fu_864_p3;
wire   [0:0] tmp_19_fu_878_p3;
wire   [0:0] tmp_18_fu_848_p3;
wire   [0:0] xor_ln731_5_fu_885_p2;
wire   [0:0] icmp_ln731_6_fu_872_p2;
wire   [9:0] trunc_ln726_5_fu_845_p1;
wire   [1:0] tmp_17_fu_917_p4;
wire   [27:0] and_ln731_7_fu_926_p3;
wire   [0:0] tmp_22_fu_940_p3;
wire   [0:0] tmp_21_fu_910_p3;
wire   [0:0] xor_ln731_6_fu_947_p2;
wire   [0:0] icmp_ln731_7_fu_934_p2;
wire   [8:0] trunc_ln726_6_fu_907_p1;
wire   [1:0] tmp_20_fu_979_p4;
wire   [27:0] and_ln731_8_fu_988_p3;
wire   [0:0] tmp_25_fu_1002_p3;
wire   [0:0] tmp_24_fu_972_p3;
wire   [0:0] xor_ln731_7_fu_1009_p2;
wire   [0:0] icmp_ln731_8_fu_996_p2;
wire   [7:0] trunc_ln726_7_fu_969_p1;
wire   [1:0] tmp_23_fu_1041_p4;
wire   [27:0] and_ln731_9_fu_1050_p3;
wire   [0:0] tmp_28_fu_1064_p3;
wire   [0:0] tmp_27_fu_1034_p3;
wire   [0:0] xor_ln731_8_fu_1071_p2;
wire   [0:0] icmp_ln731_9_fu_1058_p2;
wire   [6:0] trunc_ln726_8_fu_1031_p1;
wire   [1:0] tmp_26_fu_1103_p4;
wire   [27:0] and_ln731_s_fu_1112_p3;
wire   [0:0] tmp_31_fu_1126_p3;
wire   [0:0] tmp_30_fu_1096_p3;
wire   [0:0] xor_ln731_9_fu_1133_p2;
wire   [0:0] icmp_ln731_10_fu_1120_p2;
wire   [5:0] trunc_ln726_9_fu_1093_p1;
wire   [1:0] tmp_29_fu_1165_p4;
wire   [27:0] and_ln731_10_fu_1174_p3;
wire   [0:0] tmp_34_fu_1188_p3;
wire   [0:0] tmp_33_fu_1158_p3;
wire   [0:0] xor_ln731_10_fu_1195_p2;
wire   [0:0] icmp_ln731_11_fu_1182_p2;
wire   [4:0] trunc_ln726_10_fu_1155_p1;
wire   [1:0] tmp_32_fu_1227_p4;
wire   [27:0] and_ln731_11_fu_1236_p3;
wire   [0:0] tmp_37_fu_1250_p3;
wire   [0:0] tmp_36_fu_1220_p3;
wire   [0:0] xor_ln731_11_fu_1257_p2;
wire   [0:0] icmp_ln731_12_fu_1244_p2;
wire   [3:0] trunc_ln726_11_fu_1217_p1;
wire   [1:0] tmp_35_fu_1289_p4;
wire   [27:0] and_ln731_12_fu_1298_p3;
wire   [0:0] tmp_40_fu_1312_p3;
wire   [0:0] tmp_39_fu_1282_p3;
wire   [0:0] xor_ln731_12_fu_1319_p2;
wire   [0:0] icmp_ln731_13_fu_1306_p2;
wire   [2:0] trunc_ln726_13_fu_1279_p1;
wire   [1:0] trunc_ln726_14_fu_1341_p1;
wire   [27:0] trunc_ln726_s_fu_1344_p3;
wire   [0:0] tmp_42_fu_1365_p3;
wire   [0:0] tmp_41_fu_1352_p3;
wire   [0:0] xor_ln731_13_fu_1372_p2;
wire   [0:0] icmp_ln731_14_fu_1359_p2;
wire   [28:0] b_frac_15_fu_1386_p3;
wire   [0:0] trunc_ln733_fu_1400_p1;
wire   [0:0] icmp_ln731_16_fu_1411_p2;
wire   [22:0] tmp_43_fu_1495_p4;
wire   [27:0] zext_ln182_cast_fu_1504_p3;
wire   [0:0] tmp_51_fu_1488_p3;
wire   [28:0] tmp_45_fu_1512_p3;
wire   [28:0] zext_ln182_fu_1519_p1;
wire   [19:0] tmp_46_fu_1531_p4;
wire   [27:0] shl_ln_fu_1540_p3;
wire   [28:0] zext_ln184_1_fu_1548_p1;
wire   [28:0] select_ln182_fu_1523_p3;
wire   [21:0] zext_ln251_fu_1565_p1;
wire   [22:0] mul_ln739_fu_1578_p1;
wire   [28:0] grp_fu_1727_p3;
wire   [8:0] tmp_48_fu_1593_p4;
wire   [8:0] mul_ln776_fu_1606_p0;
wire   [17:0] zext_ln776_fu_1602_p1;
wire   [8:0] mul_ln776_fu_1606_p1;
wire   [17:0] mul_ln776_fu_1606_p2;
wire   [27:0] mul_ln739_fu_1578_p2;
wire   [24:0] shl_ln1_fu_1632_p3;
wire   [25:0] zext_ln776_1_fu_1639_p1;
wire   [25:0] zext_ln776_2_fu_1643_p1;
wire   [25:0] sub_ln776_fu_1646_p2;
wire   [15:0] trunc_ln776_1_fu_1652_p4;
wire   [27:0] shl_ln2_fu_1666_p3;
wire  signed [28:0] sext_ln779_fu_1673_p1;
wire  signed [28:0] sext_ln776_fu_1662_p1;
wire   [28:0] add_ln779_1_fu_1680_p2;
wire  signed [28:0] sext_ln779_1_fu_1677_p1;
wire   [14:0] shl_ln3_fu_1700_p3;
wire  signed [28:0] sext_ln786_fu_1707_p1;
wire   [28:0] log_base_1_fu_1711_p2;
wire   [23:0] grp_fu_1727_p0;
wire   [3:0] grp_fu_1727_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [27:0] grp_fu_1727_p00;
wire   [27:0] grp_fu_1727_p10;
wire   [28:0] grp_fu_447_p10;
reg    ap_condition_559;
reg    ap_condition_460;
reg    ap_condition_567;
reg    ap_condition_570;
reg    ap_condition_573;
reg    ap_condition_576;
reg    ap_condition_579;
reg    ap_condition_582;
reg    ap_condition_585;
reg    ap_condition_588;
reg    ap_condition_591;
reg    ap_condition_594;
reg    ap_condition_597;
reg    ap_condition_600;
reg    ap_condition_603;
reg    ap_condition_606;
reg    ap_condition_609;
reg    ap_condition_613;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_done_reg = 1'b0;
end

mfcc_mfcc_Pipeline_VITIS_LOOP_202_1_log_apfixed_reduce_log_inverse_lut_table_arraybkb #(
    .DataWidth( 6 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
log_apfixed_reduce_log_inverse_lut_table_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(log_apfixed_reduce_log_inverse_lut_table_array_address0),
    .ce0(log_apfixed_reduce_log_inverse_lut_table_array_ce0),
    .q0(log_apfixed_reduce_log_inverse_lut_table_array_q0)
);

mfcc_mfcc_Pipeline_VITIS_LOOP_202_1_log_apfixed_reduce_log0_lut_table_ap_fixed_0_5cud #(
    .DataWidth( 22 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_address0),
    .ce0(log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_ce0),
    .q0(log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_q0)
);

mfcc_mfcc_Pipeline_VITIS_LOOP_202_1_log_apfixed_reduce_log_lut_table_ap_fixed_4_4_dEe #(
    .DataWidth( 18 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_address0),
    .ce0(log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_ce0),
    .q0(log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_q0)
);

mfcc_mul_29s_6ns_29_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 29 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 29 ))
mul_29s_6ns_29_2_1_U169(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(b_frac_05_i_reg_313_pp0_iter4_reg),
    .din1(grp_fu_447_p1),
    .ce(1'b1),
    .dout(grp_fu_447_p2)
);

mfcc_mul_5s_23ns_28_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 23 ),
    .dout_WIDTH( 28 ))
mul_5s_23ns_28_1_1_U170(
    .din0(ap_phi_reg_pp0_iter10_b_exp_07_i_reg_364),
    .din1(mul_ln739_fu_1578_p1),
    .dout(mul_ln739_fu_1578_p2)
);

mfcc_mul_9ns_9ns_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 18 ))
mul_9ns_9ns_18_1_1_U171(
    .din0(mul_ln776_fu_1606_p0),
    .din1(mul_ln776_fu_1606_p1),
    .dout(mul_ln776_fu_1606_p2)
);

mfcc_mac_mulsub_24ns_4ns_29ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_mulsub_24ns_4ns_29ns_29_4_1_U172(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1727_p0),
    .din1(grp_fu_1727_p1),
    .din2(add_ln184_reg_2026_pp0_iter8_reg),
    .ce(1'b1),
    .dout(grp_fu_1727_p3)
);

mfcc_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter11_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_559)) begin
        if (((tmp_1_fu_488_p3 == 1'd1) & (icmp_ln202_reg_1743 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_phi_ln205_reg_435 <= 15'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_phi_ln205_reg_435 <= ap_phi_reg_pp0_iter1_phi_ln205_reg_435;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((1'b1 == ap_condition_613)) begin
            ap_phi_reg_pp0_iter3_b_exp_07_i_reg_364 <= 5'd25;
        end else if ((1'b1 == ap_condition_609)) begin
            ap_phi_reg_pp0_iter3_b_exp_07_i_reg_364 <= 5'd26;
        end else if ((1'b1 == ap_condition_606)) begin
            ap_phi_reg_pp0_iter3_b_exp_07_i_reg_364 <= 5'd27;
        end else if ((1'b1 == ap_condition_603)) begin
            ap_phi_reg_pp0_iter3_b_exp_07_i_reg_364 <= 5'd28;
        end else if ((1'b1 == ap_condition_600)) begin
            ap_phi_reg_pp0_iter3_b_exp_07_i_reg_364 <= 5'd29;
        end else if ((1'b1 == ap_condition_597)) begin
            ap_phi_reg_pp0_iter3_b_exp_07_i_reg_364 <= 5'd30;
        end else if ((1'b1 == ap_condition_594)) begin
            ap_phi_reg_pp0_iter3_b_exp_07_i_reg_364 <= 5'd31;
        end else if ((1'b1 == ap_condition_591)) begin
            ap_phi_reg_pp0_iter3_b_exp_07_i_reg_364 <= 5'd0;
        end else if ((1'b1 == ap_condition_588)) begin
            ap_phi_reg_pp0_iter3_b_exp_07_i_reg_364 <= 5'd1;
        end else if ((1'b1 == ap_condition_585)) begin
            ap_phi_reg_pp0_iter3_b_exp_07_i_reg_364 <= 5'd2;
        end else if ((1'b1 == ap_condition_582)) begin
            ap_phi_reg_pp0_iter3_b_exp_07_i_reg_364 <= 5'd3;
        end else if ((1'b1 == ap_condition_579)) begin
            ap_phi_reg_pp0_iter3_b_exp_07_i_reg_364 <= 5'd4;
        end else if ((1'b1 == ap_condition_576)) begin
            ap_phi_reg_pp0_iter3_b_exp_07_i_reg_364 <= 5'd5;
        end else if ((1'b1 == ap_condition_573)) begin
            ap_phi_reg_pp0_iter3_b_exp_07_i_reg_364 <= 5'd6;
        end else if ((1'b1 == ap_condition_570)) begin
            ap_phi_reg_pp0_iter3_b_exp_07_i_reg_364 <= 5'd7;
        end else if ((1'b1 == ap_condition_567)) begin
            ap_phi_reg_pp0_iter3_b_exp_07_i_reg_364 <= 5'd8;
        end else if ((1'b1 == ap_condition_460)) begin
            ap_phi_reg_pp0_iter3_b_exp_07_i_reg_364 <= select_ln731_14_fu_1417_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter3_b_exp_07_i_reg_364 <= ap_phi_reg_pp0_iter2_b_exp_07_i_reg_364;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((1'b1 == ap_condition_613)) begin
            ap_phi_reg_pp0_iter3_b_frac_05_i_reg_313 <= 29'd268435456;
        end else if ((1'b1 == ap_condition_609)) begin
            ap_phi_reg_pp0_iter3_b_frac_05_i_reg_313 <= b_frac_14_fu_1333_p3;
        end else if ((1'b1 == ap_condition_606)) begin
            ap_phi_reg_pp0_iter3_b_frac_05_i_reg_313 <= b_frac_13_fu_1271_p3;
        end else if ((1'b1 == ap_condition_603)) begin
            ap_phi_reg_pp0_iter3_b_frac_05_i_reg_313 <= b_frac_12_fu_1209_p3;
        end else if ((1'b1 == ap_condition_600)) begin
            ap_phi_reg_pp0_iter3_b_frac_05_i_reg_313 <= b_frac_11_fu_1147_p3;
        end else if ((1'b1 == ap_condition_597)) begin
            ap_phi_reg_pp0_iter3_b_frac_05_i_reg_313 <= b_frac_10_fu_1085_p3;
        end else if ((1'b1 == ap_condition_594)) begin
            ap_phi_reg_pp0_iter3_b_frac_05_i_reg_313 <= b_frac_9_fu_1023_p3;
        end else if ((1'b1 == ap_condition_591)) begin
            ap_phi_reg_pp0_iter3_b_frac_05_i_reg_313 <= b_frac_8_fu_961_p3;
        end else if ((1'b1 == ap_condition_588)) begin
            ap_phi_reg_pp0_iter3_b_frac_05_i_reg_313 <= b_frac_7_fu_899_p3;
        end else if ((1'b1 == ap_condition_585)) begin
            ap_phi_reg_pp0_iter3_b_frac_05_i_reg_313 <= b_frac_6_fu_837_p3;
        end else if ((1'b1 == ap_condition_582)) begin
            ap_phi_reg_pp0_iter3_b_frac_05_i_reg_313 <= b_frac_5_fu_775_p3;
        end else if ((1'b1 == ap_condition_579)) begin
            ap_phi_reg_pp0_iter3_b_frac_05_i_reg_313 <= b_frac_4_fu_713_p3;
        end else if ((1'b1 == ap_condition_576)) begin
            ap_phi_reg_pp0_iter3_b_frac_05_i_reg_313 <= b_frac_3_fu_651_p3;
        end else if ((1'b1 == ap_condition_573)) begin
            ap_phi_reg_pp0_iter3_b_frac_05_i_reg_313 <= b_frac_2_fu_589_p3;
        end else if ((1'b1 == ap_condition_570)) begin
            ap_phi_reg_pp0_iter3_b_frac_05_i_reg_313 <= b_frac_1_fu_528_p3;
        end else if ((1'b1 == ap_condition_567)) begin
            ap_phi_reg_pp0_iter3_b_frac_05_i_reg_313 <= b_frac_fu_496_p4;
        end else if ((1'b1 == ap_condition_460)) begin
            ap_phi_reg_pp0_iter3_b_frac_05_i_reg_313 <= b_frac_16_fu_1403_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter3_b_frac_05_i_reg_313 <= ap_phi_reg_pp0_iter2_b_frac_05_i_reg_313;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln202_fu_460_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            m_fu_244 <= add_ln202_fu_466_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            m_fu_244 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_1_reg_1820_pp0_iter5_reg == 1'd0) & (icmp_ln202_reg_1743_pp0_iter5_reg == 1'd0))) begin
        a_reg_2015 <= {{grp_fu_447_p2[28:25]}};
        mul_ln761_reg_2002 <= grp_fu_447_p2;
        tmp_38_reg_2009 <= {{grp_fu_447_p2[28:5]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_1_reg_1820_pp0_iter6_reg == 1'd0) & (icmp_ln202_reg_1743_pp0_iter6_reg == 1'd0))) begin
        add_ln184_reg_2026 <= add_ln184_fu_1552_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln184_reg_2026_pp0_iter8_reg <= add_ln184_reg_2026;
        add_ln779_reg_2041_pp0_iter10_reg <= add_ln779_reg_2041_pp0_iter9_reg;
        add_ln779_reg_2041_pp0_iter9_reg <= add_ln779_reg_2041;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        b_frac_05_i_reg_313_pp0_iter4_reg <= b_frac_05_i_reg_313;
        icmp_ln202_reg_1743_pp0_iter10_reg <= icmp_ln202_reg_1743_pp0_iter9_reg;
        icmp_ln202_reg_1743_pp0_iter11_reg <= icmp_ln202_reg_1743_pp0_iter10_reg;
        icmp_ln202_reg_1743_pp0_iter2_reg <= icmp_ln202_reg_1743_pp0_iter1_reg;
        icmp_ln202_reg_1743_pp0_iter3_reg <= icmp_ln202_reg_1743_pp0_iter2_reg;
        icmp_ln202_reg_1743_pp0_iter4_reg <= icmp_ln202_reg_1743_pp0_iter3_reg;
        icmp_ln202_reg_1743_pp0_iter5_reg <= icmp_ln202_reg_1743_pp0_iter4_reg;
        icmp_ln202_reg_1743_pp0_iter6_reg <= icmp_ln202_reg_1743_pp0_iter5_reg;
        icmp_ln202_reg_1743_pp0_iter7_reg <= icmp_ln202_reg_1743_pp0_iter6_reg;
        icmp_ln202_reg_1743_pp0_iter8_reg <= icmp_ln202_reg_1743_pp0_iter7_reg;
        icmp_ln202_reg_1743_pp0_iter9_reg <= icmp_ln202_reg_1743_pp0_iter8_reg;
        log_sum_reg_1992_pp0_iter5_reg <= log_sum_reg_1992;
        log_sum_reg_1992_pp0_iter6_reg <= log_sum_reg_1992_pp0_iter5_reg;
        log_sum_reg_1992_pp0_iter7_reg <= log_sum_reg_1992_pp0_iter6_reg;
        tmp_1_reg_1820_pp0_iter10_reg <= tmp_1_reg_1820_pp0_iter9_reg;
        tmp_1_reg_1820_pp0_iter11_reg <= tmp_1_reg_1820_pp0_iter10_reg;
        tmp_1_reg_1820_pp0_iter2_reg <= tmp_1_reg_1820;
        tmp_1_reg_1820_pp0_iter3_reg <= tmp_1_reg_1820_pp0_iter2_reg;
        tmp_1_reg_1820_pp0_iter4_reg <= tmp_1_reg_1820_pp0_iter3_reg;
        tmp_1_reg_1820_pp0_iter5_reg <= tmp_1_reg_1820_pp0_iter4_reg;
        tmp_1_reg_1820_pp0_iter6_reg <= tmp_1_reg_1820_pp0_iter5_reg;
        tmp_1_reg_1820_pp0_iter7_reg <= tmp_1_reg_1820_pp0_iter6_reg;
        tmp_1_reg_1820_pp0_iter8_reg <= tmp_1_reg_1820_pp0_iter7_reg;
        tmp_1_reg_1820_pp0_iter9_reg <= tmp_1_reg_1820_pp0_iter8_reg;
        zext_ln202_reg_1747_pp0_iter10_reg[5 : 0] <= zext_ln202_reg_1747_pp0_iter9_reg[5 : 0];
        zext_ln202_reg_1747_pp0_iter11_reg[5 : 0] <= zext_ln202_reg_1747_pp0_iter10_reg[5 : 0];
        zext_ln202_reg_1747_pp0_iter2_reg[5 : 0] <= zext_ln202_reg_1747_pp0_iter1_reg[5 : 0];
        zext_ln202_reg_1747_pp0_iter3_reg[5 : 0] <= zext_ln202_reg_1747_pp0_iter2_reg[5 : 0];
        zext_ln202_reg_1747_pp0_iter4_reg[5 : 0] <= zext_ln202_reg_1747_pp0_iter3_reg[5 : 0];
        zext_ln202_reg_1747_pp0_iter5_reg[5 : 0] <= zext_ln202_reg_1747_pp0_iter4_reg[5 : 0];
        zext_ln202_reg_1747_pp0_iter6_reg[5 : 0] <= zext_ln202_reg_1747_pp0_iter5_reg[5 : 0];
        zext_ln202_reg_1747_pp0_iter7_reg[5 : 0] <= zext_ln202_reg_1747_pp0_iter6_reg[5 : 0];
        zext_ln202_reg_1747_pp0_iter8_reg[5 : 0] <= zext_ln202_reg_1747_pp0_iter7_reg[5 : 0];
        zext_ln202_reg_1747_pp0_iter9_reg[5 : 0] <= zext_ln202_reg_1747_pp0_iter8_reg[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_1_reg_1820_pp0_iter7_reg == 1'd0) & (icmp_ln202_reg_1743_pp0_iter7_reg == 1'd0))) begin
        add_ln779_reg_2041 <= add_ln779_fu_1569_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln202_reg_1743 <= icmp_ln202_fu_460_p2;
        icmp_ln202_reg_1743_pp0_iter1_reg <= icmp_ln202_reg_1743;
        zext_ln202_reg_1747_pp0_iter1_reg[5 : 0] <= zext_ln202_reg_1747[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        ap_phi_reg_pp0_iter10_b_exp_07_i_reg_364 <= ap_phi_reg_pp0_iter9_b_exp_07_i_reg_364;
        ap_phi_reg_pp0_iter10_phi_ln205_reg_435 <= ap_phi_reg_pp0_iter9_phi_ln205_reg_435;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        ap_phi_reg_pp0_iter11_phi_ln205_reg_435 <= ap_phi_reg_pp0_iter10_phi_ln205_reg_435;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        ap_phi_reg_pp0_iter12_phi_ln205_reg_435 <= ap_phi_reg_pp0_iter11_phi_ln205_reg_435;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_b_exp_07_i_reg_364 <= ap_phi_reg_pp0_iter0_b_exp_07_i_reg_364;
        ap_phi_reg_pp0_iter1_b_frac_05_i_reg_313 <= ap_phi_reg_pp0_iter0_b_frac_05_i_reg_313;
        ap_phi_reg_pp0_iter1_phi_ln205_reg_435 <= ap_phi_reg_pp0_iter0_phi_ln205_reg_435;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_b_exp_07_i_reg_364 <= ap_phi_reg_pp0_iter1_b_exp_07_i_reg_364;
        ap_phi_reg_pp0_iter2_b_frac_05_i_reg_313 <= ap_phi_reg_pp0_iter1_b_frac_05_i_reg_313;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_phi_ln205_reg_435 <= ap_phi_reg_pp0_iter2_phi_ln205_reg_435;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_phi_reg_pp0_iter4_b_exp_07_i_reg_364 <= ap_phi_reg_pp0_iter3_b_exp_07_i_reg_364;
        ap_phi_reg_pp0_iter4_phi_ln205_reg_435 <= ap_phi_reg_pp0_iter3_phi_ln205_reg_435;
        b_frac_05_i_reg_313 <= ap_phi_reg_pp0_iter3_b_frac_05_i_reg_313;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_phi_reg_pp0_iter5_b_exp_07_i_reg_364 <= ap_phi_reg_pp0_iter4_b_exp_07_i_reg_364;
        ap_phi_reg_pp0_iter5_phi_ln205_reg_435 <= ap_phi_reg_pp0_iter4_phi_ln205_reg_435;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_phi_reg_pp0_iter6_b_exp_07_i_reg_364 <= ap_phi_reg_pp0_iter5_b_exp_07_i_reg_364;
        ap_phi_reg_pp0_iter6_phi_ln205_reg_435 <= ap_phi_reg_pp0_iter5_phi_ln205_reg_435;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        ap_phi_reg_pp0_iter7_b_exp_07_i_reg_364 <= ap_phi_reg_pp0_iter6_b_exp_07_i_reg_364;
        ap_phi_reg_pp0_iter7_phi_ln205_reg_435 <= ap_phi_reg_pp0_iter6_phi_ln205_reg_435;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_phi_reg_pp0_iter8_b_exp_07_i_reg_364 <= ap_phi_reg_pp0_iter7_b_exp_07_i_reg_364;
        ap_phi_reg_pp0_iter8_phi_ln205_reg_435 <= ap_phi_reg_pp0_iter7_phi_ln205_reg_435;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        ap_phi_reg_pp0_iter9_b_exp_07_i_reg_364 <= ap_phi_reg_pp0_iter8_b_exp_07_i_reg_364;
        ap_phi_reg_pp0_iter9_phi_ln205_reg_435 <= ap_phi_reg_pp0_iter8_phi_ln205_reg_435;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_1_reg_1820_pp0_iter3_reg == 1'd0) & (icmp_ln202_reg_1743_pp0_iter3_reg == 1'd0))) begin
        b_frac_tilde_inverse_reg_1987 <= log_apfixed_reduce_log_inverse_lut_table_array_q0;
        log_sum_reg_1992 <= log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_1_reg_1820_pp0_iter10_reg == 1'd0) & (icmp_ln202_reg_1743_pp0_iter10_reg == 1'd0))) begin
        log_base_reg_2061 <= log_base_fu_1686_p2;
        tmp_52_reg_2066 <= log_base_fu_1686_p2[32'd28];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_1_reg_1820_pp0_iter9_reg == 1'd0) & (icmp_ln202_reg_1743_pp0_iter9_reg == 1'd0))) begin
        lshr_ln_reg_2051 <= {{mul_ln776_fu_1606_p2[17:1]}};
        tmp_47_reg_2046 <= {{grp_fu_1727_p3[28:14]}};
        tmp_49_reg_2056 <= {{mul_ln739_fu_1578_p2[27:6]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln202_reg_1743 == 1'd0))) begin
        tmp_1_reg_1820 <= mel_filtered_q0[32'd15];
        x_reg_1757 <= x_fu_482_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln202_fu_460_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        zext_ln202_reg_1747[5 : 0] <= zext_ln202_fu_472_p1[5 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln202_fu_460_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter11_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_1_reg_1820_pp0_iter2_reg == 1'd0) & (icmp_ln202_reg_1743_pp0_iter2_reg == 1'd0))) begin
        if ((tmp_44_fu_1425_p3 == 1'd0)) begin
            ap_phi_mux_index0_2_phi_fu_358_p4 = {{ap_phi_reg_pp0_iter3_b_frac_05_i_reg_313[26:21]}};
        end else if ((tmp_44_fu_1425_p3 == 1'd1)) begin
            ap_phi_mux_index0_2_phi_fu_358_p4 = {{ap_phi_reg_pp0_iter3_b_frac_05_i_reg_313[27:22]}};
        end else begin
            ap_phi_mux_index0_2_phi_fu_358_p4 = ap_phi_reg_pp0_iter3_index0_2_reg_355;
        end
    end else begin
        ap_phi_mux_index0_2_phi_fu_358_p4 = ap_phi_reg_pp0_iter3_index0_2_reg_355;
    end
end

always @ (*) begin
    if (((tmp_1_reg_1820_pp0_iter11_reg == 1'd0) & (icmp_ln202_reg_1743_pp0_iter11_reg == 1'd0))) begin
        ap_phi_mux_phi_ln205_phi_fu_439_p4 = {{log_base_1_fu_1711_p2[28:14]}};
    end else begin
        ap_phi_mux_phi_ln205_phi_fu_439_p4 = ap_phi_reg_pp0_iter12_phi_ln205_reg_435;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_m_2 = 6'd0;
    end else begin
        ap_sig_allocacmp_m_2 = m_fu_244;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_ce0 = 1'b1;
    end else begin
        log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        log_apfixed_reduce_log_inverse_lut_table_array_ce0 = 1'b1;
    end else begin
        log_apfixed_reduce_log_inverse_lut_table_array_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_ce0 = 1'b1;
    end else begin
        log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_filtered_ce0 = 1'b1;
    end else begin
        mel_filtered_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        mfcc_1_ce0 = 1'b1;
    end else begin
        mfcc_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        mfcc_1_we0 = 1'b1;
    end else begin
        mfcc_1_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln184_fu_1552_p2 = (zext_ln184_1_fu_1548_p1 + select_ln182_fu_1523_p3);

assign add_ln202_fu_466_p2 = (ap_sig_allocacmp_m_2 + 6'd1);

assign add_ln779_1_fu_1680_p2 = ($signed(sext_ln779_fu_1673_p1) + $signed(sext_ln776_fu_1662_p1));

assign add_ln779_fu_1569_p2 = (zext_ln251_fu_1565_p1 + log_sum_reg_1992_pp0_iter7_reg);

assign and_ln731_10_fu_1174_p3 = {{tmp_29_fu_1165_p4}, {26'd0}};

assign and_ln731_11_fu_1236_p3 = {{tmp_32_fu_1227_p4}, {26'd0}};

assign and_ln731_12_fu_1298_p3 = {{tmp_35_fu_1289_p4}, {26'd0}};

assign and_ln731_1_fu_554_p3 = {{tmp_2_fu_545_p4}, {26'd0}};

assign and_ln731_2_fu_616_p3 = {{tmp_5_fu_607_p4}, {26'd0}};

assign and_ln731_3_fu_678_p3 = {{tmp_8_fu_669_p4}, {26'd0}};

assign and_ln731_4_fu_740_p3 = {{tmp_s_fu_731_p4}, {26'd0}};

assign and_ln731_5_fu_802_p3 = {{tmp_11_fu_793_p4}, {26'd0}};

assign and_ln731_6_fu_864_p3 = {{tmp_14_fu_855_p4}, {26'd0}};

assign and_ln731_7_fu_926_p3 = {{tmp_17_fu_917_p4}, {26'd0}};

assign and_ln731_8_fu_988_p3 = {{tmp_20_fu_979_p4}, {26'd0}};

assign and_ln731_9_fu_1050_p3 = {{tmp_23_fu_1041_p4}, {26'd0}};

assign and_ln731_s_fu_1112_p3 = {{tmp_26_fu_1103_p4}, {26'd0}};

assign and_ln_fu_514_p3 = {{tmp_fu_505_p4}, {26'd0}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_460 = ((icmp_ln731_15_fu_1394_p2 == 1'd0) & (select_ln731_13_fu_1378_p3 == 1'd0) & (select_ln731_12_fu_1325_p3 == 1'd0) & (select_ln731_11_fu_1263_p3 == 1'd0) & (select_ln731_10_fu_1201_p3 == 1'd0) & (select_ln731_9_fu_1139_p3 == 1'd0) & (select_ln731_8_fu_1077_p3 == 1'd0) & (select_ln731_7_fu_1015_p3 == 1'd0) & (select_ln731_6_fu_953_p3 == 1'd0) & (select_ln731_5_fu_891_p3 == 1'd0) & (select_ln731_4_fu_829_p3 == 1'd0) & (select_ln731_3_fu_767_p3 == 1'd0) & (select_ln731_2_fu_705_p3 == 1'd0) & (select_ln731_1_fu_643_p3 == 1'd0) & (select_ln731_fu_581_p3 == 1'd0) & (icmp_ln731_fu_522_p2 == 1'd0) & (tmp_1_reg_1820 == 1'd0) & (icmp_ln202_reg_1743_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_condition_559 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_567 = ((icmp_ln731_fu_522_p2 == 1'd1) & (tmp_1_reg_1820 == 1'd0) & (icmp_ln202_reg_1743_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_condition_570 = ((select_ln731_fu_581_p3 == 1'd1) & (icmp_ln731_fu_522_p2 == 1'd0) & (tmp_1_reg_1820 == 1'd0) & (icmp_ln202_reg_1743_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_condition_573 = ((select_ln731_1_fu_643_p3 == 1'd1) & (select_ln731_fu_581_p3 == 1'd0) & (icmp_ln731_fu_522_p2 == 1'd0) & (tmp_1_reg_1820 == 1'd0) & (icmp_ln202_reg_1743_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_condition_576 = ((select_ln731_2_fu_705_p3 == 1'd1) & (select_ln731_1_fu_643_p3 == 1'd0) & (select_ln731_fu_581_p3 == 1'd0) & (icmp_ln731_fu_522_p2 == 1'd0) & (tmp_1_reg_1820 == 1'd0) & (icmp_ln202_reg_1743_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_condition_579 = ((select_ln731_3_fu_767_p3 == 1'd1) & (select_ln731_2_fu_705_p3 == 1'd0) & (select_ln731_1_fu_643_p3 == 1'd0) & (select_ln731_fu_581_p3 == 1'd0) & (icmp_ln731_fu_522_p2 == 1'd0) & (tmp_1_reg_1820 == 1'd0) & (icmp_ln202_reg_1743_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_condition_582 = ((select_ln731_4_fu_829_p3 == 1'd1) & (select_ln731_3_fu_767_p3 == 1'd0) & (select_ln731_2_fu_705_p3 == 1'd0) & (select_ln731_1_fu_643_p3 == 1'd0) & (select_ln731_fu_581_p3 == 1'd0) & (icmp_ln731_fu_522_p2 == 1'd0) & (tmp_1_reg_1820 == 1'd0) & (icmp_ln202_reg_1743_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_condition_585 = ((select_ln731_5_fu_891_p3 == 1'd1) & (select_ln731_4_fu_829_p3 == 1'd0) & (select_ln731_3_fu_767_p3 == 1'd0) & (select_ln731_2_fu_705_p3 == 1'd0) & (select_ln731_1_fu_643_p3 == 1'd0) & (select_ln731_fu_581_p3 == 1'd0) & (icmp_ln731_fu_522_p2 == 1'd0) & (tmp_1_reg_1820 == 1'd0) & (icmp_ln202_reg_1743_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_condition_588 = ((select_ln731_6_fu_953_p3 == 1'd1) & (select_ln731_5_fu_891_p3 == 1'd0) & (select_ln731_4_fu_829_p3 == 1'd0) & (select_ln731_3_fu_767_p3 == 1'd0) & (select_ln731_2_fu_705_p3 == 1'd0) & (select_ln731_1_fu_643_p3 == 1'd0) & (select_ln731_fu_581_p3 == 1'd0) & (icmp_ln731_fu_522_p2 == 1'd0) & (tmp_1_reg_1820 == 1'd0) & (icmp_ln202_reg_1743_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_condition_591 = ((select_ln731_7_fu_1015_p3 == 1'd1) & (select_ln731_6_fu_953_p3 == 1'd0) & (select_ln731_5_fu_891_p3 == 1'd0) & (select_ln731_4_fu_829_p3 == 1'd0) & (select_ln731_3_fu_767_p3 == 1'd0) & (select_ln731_2_fu_705_p3 == 1'd0) & (select_ln731_1_fu_643_p3 == 1'd0) & (select_ln731_fu_581_p3 == 1'd0) & (icmp_ln731_fu_522_p2 == 1'd0) & (tmp_1_reg_1820 == 1'd0) & (icmp_ln202_reg_1743_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_condition_594 = ((select_ln731_8_fu_1077_p3 == 1'd1) & (select_ln731_7_fu_1015_p3 == 1'd0) & (select_ln731_6_fu_953_p3 == 1'd0) & (select_ln731_5_fu_891_p3 == 1'd0) & (select_ln731_4_fu_829_p3 == 1'd0) & (select_ln731_3_fu_767_p3 == 1'd0) & (select_ln731_2_fu_705_p3 == 1'd0) & (select_ln731_1_fu_643_p3 == 1'd0) & (select_ln731_fu_581_p3 == 1'd0) & (icmp_ln731_fu_522_p2 == 1'd0) & (tmp_1_reg_1820 == 1'd0) & (icmp_ln202_reg_1743_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_condition_597 = ((select_ln731_9_fu_1139_p3 == 1'd1) & (select_ln731_8_fu_1077_p3 == 1'd0) & (select_ln731_7_fu_1015_p3 == 1'd0) & (select_ln731_6_fu_953_p3 == 1'd0) & (select_ln731_5_fu_891_p3 == 1'd0) & (select_ln731_4_fu_829_p3 == 1'd0) & (select_ln731_3_fu_767_p3 == 1'd0) & (select_ln731_2_fu_705_p3 == 1'd0) & (select_ln731_1_fu_643_p3 == 1'd0) & (select_ln731_fu_581_p3 == 1'd0) & (icmp_ln731_fu_522_p2 == 1'd0) & (tmp_1_reg_1820 == 1'd0) & (icmp_ln202_reg_1743_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_condition_600 = ((select_ln731_10_fu_1201_p3 == 1'd1) & (select_ln731_9_fu_1139_p3 == 1'd0) & (select_ln731_8_fu_1077_p3 == 1'd0) & (select_ln731_7_fu_1015_p3 == 1'd0) & (select_ln731_6_fu_953_p3 == 1'd0) & (select_ln731_5_fu_891_p3 == 1'd0) & (select_ln731_4_fu_829_p3 == 1'd0) & (select_ln731_3_fu_767_p3 == 1'd0) & (select_ln731_2_fu_705_p3 == 1'd0) & (select_ln731_1_fu_643_p3 == 1'd0) & (select_ln731_fu_581_p3 == 1'd0) & (icmp_ln731_fu_522_p2 == 1'd0) & (tmp_1_reg_1820 == 1'd0) & (icmp_ln202_reg_1743_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_condition_603 = ((select_ln731_11_fu_1263_p3 == 1'd1) & (select_ln731_10_fu_1201_p3 == 1'd0) & (select_ln731_9_fu_1139_p3 == 1'd0) & (select_ln731_8_fu_1077_p3 == 1'd0) & (select_ln731_7_fu_1015_p3 == 1'd0) & (select_ln731_6_fu_953_p3 == 1'd0) & (select_ln731_5_fu_891_p3 == 1'd0) & (select_ln731_4_fu_829_p3 == 1'd0) & (select_ln731_3_fu_767_p3 == 1'd0) & (select_ln731_2_fu_705_p3 == 1'd0) & (select_ln731_1_fu_643_p3 == 1'd0) & (select_ln731_fu_581_p3 == 1'd0) & (icmp_ln731_fu_522_p2 == 1'd0) & (tmp_1_reg_1820 == 1'd0) & (icmp_ln202_reg_1743_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_condition_606 = ((select_ln731_12_fu_1325_p3 == 1'd1) & (select_ln731_11_fu_1263_p3 == 1'd0) & (select_ln731_10_fu_1201_p3 == 1'd0) & (select_ln731_9_fu_1139_p3 == 1'd0) & (select_ln731_8_fu_1077_p3 == 1'd0) & (select_ln731_7_fu_1015_p3 == 1'd0) & (select_ln731_6_fu_953_p3 == 1'd0) & (select_ln731_5_fu_891_p3 == 1'd0) & (select_ln731_4_fu_829_p3 == 1'd0) & (select_ln731_3_fu_767_p3 == 1'd0) & (select_ln731_2_fu_705_p3 == 1'd0) & (select_ln731_1_fu_643_p3 == 1'd0) & (select_ln731_fu_581_p3 == 1'd0) & (icmp_ln731_fu_522_p2 == 1'd0) & (tmp_1_reg_1820 == 1'd0) & (icmp_ln202_reg_1743_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_condition_609 = ((select_ln731_13_fu_1378_p3 == 1'd1) & (select_ln731_12_fu_1325_p3 == 1'd0) & (select_ln731_11_fu_1263_p3 == 1'd0) & (select_ln731_10_fu_1201_p3 == 1'd0) & (select_ln731_9_fu_1139_p3 == 1'd0) & (select_ln731_8_fu_1077_p3 == 1'd0) & (select_ln731_7_fu_1015_p3 == 1'd0) & (select_ln731_6_fu_953_p3 == 1'd0) & (select_ln731_5_fu_891_p3 == 1'd0) & (select_ln731_4_fu_829_p3 == 1'd0) & (select_ln731_3_fu_767_p3 == 1'd0) & (select_ln731_2_fu_705_p3 == 1'd0) & (select_ln731_1_fu_643_p3 == 1'd0) & (select_ln731_fu_581_p3 == 1'd0) & (icmp_ln731_fu_522_p2 == 1'd0) & (tmp_1_reg_1820 == 1'd0) & (icmp_ln202_reg_1743_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_condition_613 = ((icmp_ln731_15_fu_1394_p2 == 1'd1) & (select_ln731_13_fu_1378_p3 == 1'd0) & (select_ln731_12_fu_1325_p3 == 1'd0) & (select_ln731_11_fu_1263_p3 == 1'd0) & (select_ln731_10_fu_1201_p3 == 1'd0) & (select_ln731_9_fu_1139_p3 == 1'd0) & (select_ln731_8_fu_1077_p3 == 1'd0) & (select_ln731_7_fu_1015_p3 == 1'd0) & (select_ln731_6_fu_953_p3 == 1'd0) & (select_ln731_5_fu_891_p3 == 1'd0) & (select_ln731_4_fu_829_p3 == 1'd0) & (select_ln731_3_fu_767_p3 == 1'd0) & (select_ln731_2_fu_705_p3 == 1'd0) & (select_ln731_1_fu_643_p3 == 1'd0) & (select_ln731_fu_581_p3 == 1'd0) & (icmp_ln731_fu_522_p2 == 1'd0) & (tmp_1_reg_1820 == 1'd0) & (icmp_ln202_reg_1743_pp0_iter1_reg == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_b_exp_07_i_reg_364 = 'bx;

assign ap_phi_reg_pp0_iter0_b_frac_05_i_reg_313 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln205_reg_435 = 'bx;

assign ap_phi_reg_pp0_iter3_index0_2_reg_355 = 'bx;

assign b_frac_10_fu_1085_p3 = {{trunc_ln726_8_fu_1031_p1}, {22'd0}};

assign b_frac_11_fu_1147_p3 = {{trunc_ln726_9_fu_1093_p1}, {23'd0}};

assign b_frac_12_fu_1209_p3 = {{trunc_ln726_10_fu_1155_p1}, {24'd0}};

assign b_frac_13_fu_1271_p3 = {{trunc_ln726_11_fu_1217_p1}, {25'd0}};

assign b_frac_14_fu_1333_p3 = {{trunc_ln726_13_fu_1279_p1}, {26'd0}};

assign b_frac_15_fu_1386_p3 = {{trunc_ln726_14_fu_1341_p1}, {27'd0}};

assign b_frac_16_fu_1403_p3 = {{trunc_ln733_fu_1400_p1}, {28'd0}};

assign b_frac_1_fu_528_p3 = {{x_reg_1757}, {13'd0}};

assign b_frac_2_fu_589_p3 = {{trunc_ln726_fu_535_p1}, {14'd0}};

assign b_frac_3_fu_651_p3 = {{trunc_ln726_1_fu_597_p1}, {15'd0}};

assign b_frac_4_fu_713_p3 = {{trunc_ln726_2_fu_659_p1}, {16'd0}};

assign b_frac_5_fu_775_p3 = {{trunc_ln726_3_fu_721_p1}, {17'd0}};

assign b_frac_6_fu_837_p3 = {{trunc_ln726_4_fu_783_p1}, {18'd0}};

assign b_frac_7_fu_899_p3 = {{trunc_ln726_5_fu_845_p1}, {19'd0}};

assign b_frac_8_fu_961_p3 = {{trunc_ln726_6_fu_907_p1}, {20'd0}};

assign b_frac_9_fu_1023_p3 = {{trunc_ln726_7_fu_969_p1}, {21'd0}};

assign b_frac_fu_496_p4 = {{{{1'd0}, {x_reg_1757}}}, {12'd0}};

assign grp_fu_1727_p0 = grp_fu_1727_p00;

assign grp_fu_1727_p00 = tmp_38_reg_2009;

assign grp_fu_1727_p1 = grp_fu_1727_p10;

assign grp_fu_1727_p10 = a_reg_2015;

assign grp_fu_447_p1 = grp_fu_447_p10;

assign grp_fu_447_p10 = b_frac_tilde_inverse_reg_1987;

assign icmp_ln202_fu_460_p2 = ((ap_sig_allocacmp_m_2 == 6'd42) ? 1'b1 : 1'b0);

assign icmp_ln731_10_fu_1120_p2 = ((and_ln731_s_fu_1112_p3 == 28'd201326592) ? 1'b1 : 1'b0);

assign icmp_ln731_11_fu_1182_p2 = ((and_ln731_10_fu_1174_p3 == 28'd201326592) ? 1'b1 : 1'b0);

assign icmp_ln731_12_fu_1244_p2 = ((and_ln731_11_fu_1236_p3 == 28'd201326592) ? 1'b1 : 1'b0);

assign icmp_ln731_13_fu_1306_p2 = ((and_ln731_12_fu_1298_p3 == 28'd201326592) ? 1'b1 : 1'b0);

assign icmp_ln731_14_fu_1359_p2 = ((trunc_ln726_s_fu_1344_p3 == 28'd201326592) ? 1'b1 : 1'b0);

assign icmp_ln731_15_fu_1394_p2 = ((b_frac_15_fu_1386_p3 == 29'd268435456) ? 1'b1 : 1'b0);

assign icmp_ln731_16_fu_1411_p2 = ((b_frac_16_fu_1403_p3 != 29'd0) ? 1'b1 : 1'b0);

assign icmp_ln731_1_fu_562_p2 = ((and_ln731_1_fu_554_p3 == 28'd201326592) ? 1'b1 : 1'b0);

assign icmp_ln731_2_fu_624_p2 = ((and_ln731_2_fu_616_p3 == 28'd201326592) ? 1'b1 : 1'b0);

assign icmp_ln731_3_fu_686_p2 = ((and_ln731_3_fu_678_p3 == 28'd201326592) ? 1'b1 : 1'b0);

assign icmp_ln731_4_fu_748_p2 = ((and_ln731_4_fu_740_p3 == 28'd201326592) ? 1'b1 : 1'b0);

assign icmp_ln731_5_fu_810_p2 = ((and_ln731_5_fu_802_p3 == 28'd201326592) ? 1'b1 : 1'b0);

assign icmp_ln731_6_fu_872_p2 = ((and_ln731_6_fu_864_p3 == 28'd201326592) ? 1'b1 : 1'b0);

assign icmp_ln731_7_fu_934_p2 = ((and_ln731_7_fu_926_p3 == 28'd201326592) ? 1'b1 : 1'b0);

assign icmp_ln731_8_fu_996_p2 = ((and_ln731_8_fu_988_p3 == 28'd201326592) ? 1'b1 : 1'b0);

assign icmp_ln731_9_fu_1058_p2 = ((and_ln731_9_fu_1050_p3 == 28'd201326592) ? 1'b1 : 1'b0);

assign icmp_ln731_fu_522_p2 = ((and_ln_fu_514_p3 == 28'd201326592) ? 1'b1 : 1'b0);

assign log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_address0 = zext_ln756_fu_1455_p1;

assign log_apfixed_reduce_log_inverse_lut_table_array_address0 = zext_ln756_fu_1455_p1;

assign log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_address0 = zext_ln186_fu_1561_p1;

assign log_base_1_fu_1711_p2 = ($signed(log_base_reg_2061) + $signed(sext_ln786_fu_1707_p1));

assign log_base_fu_1686_p2 = ($signed(add_ln779_1_fu_1680_p2) + $signed(sext_ln779_1_fu_1677_p1));

assign mel_filtered_address0 = zext_ln202_fu_472_p1;

assign mfcc_1_address0 = zext_ln202_reg_1747_pp0_iter11_reg;

assign mfcc_1_d0 = ap_phi_mux_phi_ln205_phi_fu_439_p4;

assign mul_ln739_fu_1578_p1 = 28'd2907269;

assign mul_ln776_fu_1606_p0 = zext_ln776_fu_1602_p1;

assign mul_ln776_fu_1606_p1 = zext_ln776_fu_1602_p1;

assign select_ln182_fu_1523_p3 = ((tmp_51_fu_1488_p3[0:0] == 1'b1) ? tmp_45_fu_1512_p3 : zext_ln182_fu_1519_p1);

assign select_ln731_10_fu_1201_p3 = ((tmp_33_fu_1158_p3[0:0] == 1'b1) ? xor_ln731_10_fu_1195_p2 : icmp_ln731_11_fu_1182_p2);

assign select_ln731_11_fu_1263_p3 = ((tmp_36_fu_1220_p3[0:0] == 1'b1) ? xor_ln731_11_fu_1257_p2 : icmp_ln731_12_fu_1244_p2);

assign select_ln731_12_fu_1325_p3 = ((tmp_39_fu_1282_p3[0:0] == 1'b1) ? xor_ln731_12_fu_1319_p2 : icmp_ln731_13_fu_1306_p2);

assign select_ln731_13_fu_1378_p3 = ((tmp_41_fu_1352_p3[0:0] == 1'b1) ? xor_ln731_13_fu_1372_p2 : icmp_ln731_14_fu_1359_p2);

assign select_ln731_14_fu_1417_p3 = ((icmp_ln731_16_fu_1411_p2[0:0] == 1'b1) ? 5'd24 : 5'd23);

assign select_ln731_1_fu_643_p3 = ((tmp_6_fu_600_p3[0:0] == 1'b1) ? xor_ln731_1_fu_637_p2 : icmp_ln731_2_fu_624_p2);

assign select_ln731_2_fu_705_p3 = ((tmp_9_fu_662_p3[0:0] == 1'b1) ? xor_ln731_2_fu_699_p2 : icmp_ln731_3_fu_686_p2);

assign select_ln731_3_fu_767_p3 = ((tmp_12_fu_724_p3[0:0] == 1'b1) ? xor_ln731_3_fu_761_p2 : icmp_ln731_4_fu_748_p2);

assign select_ln731_4_fu_829_p3 = ((tmp_15_fu_786_p3[0:0] == 1'b1) ? xor_ln731_4_fu_823_p2 : icmp_ln731_5_fu_810_p2);

assign select_ln731_5_fu_891_p3 = ((tmp_18_fu_848_p3[0:0] == 1'b1) ? xor_ln731_5_fu_885_p2 : icmp_ln731_6_fu_872_p2);

assign select_ln731_6_fu_953_p3 = ((tmp_21_fu_910_p3[0:0] == 1'b1) ? xor_ln731_6_fu_947_p2 : icmp_ln731_7_fu_934_p2);

assign select_ln731_7_fu_1015_p3 = ((tmp_24_fu_972_p3[0:0] == 1'b1) ? xor_ln731_7_fu_1009_p2 : icmp_ln731_8_fu_996_p2);

assign select_ln731_8_fu_1077_p3 = ((tmp_27_fu_1034_p3[0:0] == 1'b1) ? xor_ln731_8_fu_1071_p2 : icmp_ln731_9_fu_1058_p2);

assign select_ln731_9_fu_1139_p3 = ((tmp_30_fu_1096_p3[0:0] == 1'b1) ? xor_ln731_9_fu_1133_p2 : icmp_ln731_10_fu_1120_p2);

assign select_ln731_fu_581_p3 = ((tmp_3_fu_538_p3[0:0] == 1'b1) ? xor_ln731_fu_575_p2 : icmp_ln731_1_fu_562_p2);

assign sext_ln776_fu_1662_p1 = $signed(trunc_ln776_1_fu_1652_p4);

assign sext_ln779_1_fu_1677_p1 = $signed(add_ln779_reg_2041_pp0_iter10_reg);

assign sext_ln779_fu_1673_p1 = $signed(shl_ln2_fu_1666_p3);

assign sext_ln786_fu_1707_p1 = $signed(shl_ln3_fu_1700_p3);

assign shl_ln1_fu_1632_p3 = {{tmp_47_reg_2046}, {10'd0}};

assign shl_ln2_fu_1666_p3 = {{tmp_49_reg_2056}, {6'd0}};

assign shl_ln3_fu_1700_p3 = {{tmp_52_reg_2066}, {14'd8192}};

assign shl_ln_fu_1540_p3 = {{tmp_46_fu_1531_p4}, {8'd0}};

assign sub_ln776_fu_1646_p2 = (zext_ln776_1_fu_1639_p1 - zext_ln776_2_fu_1643_p1);

assign tmp_10_fu_692_p3 = x_reg_1757[32'd12];

assign tmp_11_fu_793_p4 = {{x_reg_1757[10:9]}};

assign tmp_12_fu_724_p3 = x_reg_1757[32'd12];

assign tmp_13_fu_754_p3 = x_reg_1757[32'd11];

assign tmp_14_fu_855_p4 = {{x_reg_1757[9:8]}};

assign tmp_15_fu_786_p3 = x_reg_1757[32'd11];

assign tmp_16_fu_816_p3 = x_reg_1757[32'd10];

assign tmp_17_fu_917_p4 = {{x_reg_1757[8:7]}};

assign tmp_18_fu_848_p3 = x_reg_1757[32'd10];

assign tmp_19_fu_878_p3 = x_reg_1757[32'd9];

assign tmp_1_fu_488_p3 = mel_filtered_q0[32'd15];

assign tmp_20_fu_979_p4 = {{x_reg_1757[7:6]}};

assign tmp_21_fu_910_p3 = x_reg_1757[32'd9];

assign tmp_22_fu_940_p3 = x_reg_1757[32'd8];

assign tmp_23_fu_1041_p4 = {{x_reg_1757[6:5]}};

assign tmp_24_fu_972_p3 = x_reg_1757[32'd8];

assign tmp_25_fu_1002_p3 = x_reg_1757[32'd7];

assign tmp_26_fu_1103_p4 = {{x_reg_1757[5:4]}};

assign tmp_27_fu_1034_p3 = x_reg_1757[32'd7];

assign tmp_28_fu_1064_p3 = x_reg_1757[32'd6];

assign tmp_29_fu_1165_p4 = {{x_reg_1757[4:3]}};

assign tmp_2_fu_545_p4 = {{x_reg_1757[14:13]}};

assign tmp_30_fu_1096_p3 = x_reg_1757[32'd6];

assign tmp_31_fu_1126_p3 = x_reg_1757[32'd5];

assign tmp_32_fu_1227_p4 = {{x_reg_1757[3:2]}};

assign tmp_33_fu_1158_p3 = x_reg_1757[32'd5];

assign tmp_34_fu_1188_p3 = x_reg_1757[32'd4];

assign tmp_35_fu_1289_p4 = {{x_reg_1757[2:1]}};

assign tmp_36_fu_1220_p3 = x_reg_1757[32'd4];

assign tmp_37_fu_1250_p3 = x_reg_1757[32'd3];

assign tmp_39_fu_1282_p3 = x_reg_1757[32'd3];

assign tmp_3_fu_538_p3 = x_reg_1757[32'd15];

assign tmp_40_fu_1312_p3 = x_reg_1757[32'd2];

assign tmp_41_fu_1352_p3 = x_reg_1757[32'd2];

assign tmp_42_fu_1365_p3 = x_reg_1757[32'd1];

assign tmp_43_fu_1495_p4 = {{mul_ln761_reg_2002[28:6]}};

assign tmp_44_fu_1425_p3 = ap_phi_reg_pp0_iter3_b_frac_05_i_reg_313[32'd28];

assign tmp_45_fu_1512_p3 = {{5'd16}, {tmp_38_reg_2009}};

assign tmp_46_fu_1531_p4 = {{mul_ln761_reg_2002[24:5]}};

assign tmp_48_fu_1593_p4 = {{grp_fu_1727_p3[28:20]}};

assign tmp_4_fu_568_p3 = x_reg_1757[32'd14];

assign tmp_51_fu_1488_p3 = mul_ln761_reg_2002[32'd28];

assign tmp_5_fu_607_p4 = {{x_reg_1757[13:12]}};

assign tmp_6_fu_600_p3 = x_reg_1757[32'd14];

assign tmp_7_fu_630_p3 = x_reg_1757[32'd13];

assign tmp_8_fu_669_p4 = {{x_reg_1757[12:11]}};

assign tmp_9_fu_662_p3 = x_reg_1757[32'd13];

assign tmp_fu_505_p4 = {{x_reg_1757[15:14]}};

assign tmp_s_fu_731_p4 = {{x_reg_1757[11:10]}};

assign trunc_ln726_10_fu_1155_p1 = x_reg_1757[4:0];

assign trunc_ln726_11_fu_1217_p1 = x_reg_1757[3:0];

assign trunc_ln726_13_fu_1279_p1 = x_reg_1757[2:0];

assign trunc_ln726_14_fu_1341_p1 = x_reg_1757[1:0];

assign trunc_ln726_1_fu_597_p1 = x_reg_1757[13:0];

assign trunc_ln726_2_fu_659_p1 = x_reg_1757[12:0];

assign trunc_ln726_3_fu_721_p1 = x_reg_1757[11:0];

assign trunc_ln726_4_fu_783_p1 = x_reg_1757[10:0];

assign trunc_ln726_5_fu_845_p1 = x_reg_1757[9:0];

assign trunc_ln726_6_fu_907_p1 = x_reg_1757[8:0];

assign trunc_ln726_7_fu_969_p1 = x_reg_1757[7:0];

assign trunc_ln726_8_fu_1031_p1 = x_reg_1757[6:0];

assign trunc_ln726_9_fu_1093_p1 = x_reg_1757[5:0];

assign trunc_ln726_fu_535_p1 = x_reg_1757[14:0];

assign trunc_ln726_s_fu_1344_p3 = {{trunc_ln726_14_fu_1341_p1}, {26'd0}};

assign trunc_ln733_fu_1400_p1 = x_reg_1757[0:0];

assign trunc_ln776_1_fu_1652_p4 = {{sub_ln776_fu_1646_p2[25:10]}};

assign x_fu_482_p2 = (mel_filtered_q0 + 16'd1);

assign xor_ln731_10_fu_1195_p2 = (tmp_34_fu_1188_p3 ^ 1'd1);

assign xor_ln731_11_fu_1257_p2 = (tmp_37_fu_1250_p3 ^ 1'd1);

assign xor_ln731_12_fu_1319_p2 = (tmp_40_fu_1312_p3 ^ 1'd1);

assign xor_ln731_13_fu_1372_p2 = (tmp_42_fu_1365_p3 ^ 1'd1);

assign xor_ln731_1_fu_637_p2 = (tmp_7_fu_630_p3 ^ 1'd1);

assign xor_ln731_2_fu_699_p2 = (tmp_10_fu_692_p3 ^ 1'd1);

assign xor_ln731_3_fu_761_p2 = (tmp_13_fu_754_p3 ^ 1'd1);

assign xor_ln731_4_fu_823_p2 = (tmp_16_fu_816_p3 ^ 1'd1);

assign xor_ln731_5_fu_885_p2 = (tmp_19_fu_878_p3 ^ 1'd1);

assign xor_ln731_6_fu_947_p2 = (tmp_22_fu_940_p3 ^ 1'd1);

assign xor_ln731_7_fu_1009_p2 = (tmp_25_fu_1002_p3 ^ 1'd1);

assign xor_ln731_8_fu_1071_p2 = (tmp_28_fu_1064_p3 ^ 1'd1);

assign xor_ln731_9_fu_1133_p2 = (tmp_31_fu_1126_p3 ^ 1'd1);

assign xor_ln731_fu_575_p2 = (tmp_4_fu_568_p3 ^ 1'd1);

assign zext_ln182_cast_fu_1504_p3 = {{5'd16}, {tmp_43_fu_1495_p4}};

assign zext_ln182_fu_1519_p1 = zext_ln182_cast_fu_1504_p3;

assign zext_ln184_1_fu_1548_p1 = shl_ln_fu_1540_p3;

assign zext_ln186_fu_1561_p1 = a_reg_2015;

assign zext_ln202_fu_472_p1 = ap_sig_allocacmp_m_2;

assign zext_ln251_fu_1565_p1 = log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_q0;

assign zext_ln756_fu_1455_p1 = ap_phi_mux_index0_2_phi_fu_358_p4;

assign zext_ln776_1_fu_1639_p1 = shl_ln1_fu_1632_p3;

assign zext_ln776_2_fu_1643_p1 = lshr_ln_reg_2051;

assign zext_ln776_fu_1602_p1 = tmp_48_fu_1593_p4;

always @ (posedge ap_clk) begin
    zext_ln202_reg_1747[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln202_reg_1747_pp0_iter1_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln202_reg_1747_pp0_iter2_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln202_reg_1747_pp0_iter3_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln202_reg_1747_pp0_iter4_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln202_reg_1747_pp0_iter5_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln202_reg_1747_pp0_iter6_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln202_reg_1747_pp0_iter7_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln202_reg_1747_pp0_iter8_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln202_reg_1747_pp0_iter9_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln202_reg_1747_pp0_iter10_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln202_reg_1747_pp0_iter11_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
end

endmodule //mfcc_mfcc_Pipeline_VITIS_LOOP_202_1
