-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_27_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 6; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 42
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_27_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "000000", 1 => "000000", 2 => "000000", 3 => "000000", 
    4 => "000000", 5 => "000000", 6 => "000000", 7 => "000000", 
    8 => "000000", 9 => "000000", 10 => "000000", 11 => "000000", 
    12 => "000000", 13 => "000000", 14 => "000000", 15 => "000000", 
    16 => "000000", 17 => "000000", 18 => "000000", 19 => "000000", 
    20 => "000000", 21 => "000000", 22 => "000000", 23 => "000000", 
    24 => "000000", 25 => "000000", 26 => "000000", 27 => "000000", 
    28 => "000000", 29 => "000000", 30 => "000000", 31 => "000000", 
    32 => "000000", 33 => "000000", 34 => "000000", 35 => "000000", 
    36 => "000000", 37 => "000000", 38 => "000000", 39 => "000000", 
    40 => "010110", 41 => "110000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

