-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_1_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 42
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_1_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11111101", 1 => "10100111", 2 => "11111110", 3 => "11001011", 
    4 => "11001001", 5 => "11100010", 6 => "11101011", 7 => "11100100", 
    8 => "11010001", 9 => "10110001", 10 => "10000110", 11 => "10110100", 
    12 => "01110011", 13 => "10000010", 14 => "10000001", 15 => "01110011", 
    16 => "01011000", 17 => "01111000", 18 => "01000100", 19 => "01000110", 
    20 => "01110101", 21 => "01011010", 22 => "01101000", 23 => "00110100", 
    24 => "01010110", 25 => "00111010", 26 => "00111101", 27 => "00110010", 
    28 => "00111111", 29 => "00111101", 30 => "00101101", 31 => "00110000", 
    32 => "00100101", 33 => "00101001", 34 => "00011110", 35 => "00100000", 
    36 => "00101011", 37 => "00100111", 38 => "00010110", 39 => "00100000", 
    40 => "00011011", 41 => "00011010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

