# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/the5t/OneDrive/Documents/GitHub/rwth-lab-fpga-WIP/exp_2/exp_2.srcs/sources_1/ip/sqrt_cordic/sqrt_cordic.xci
# IP: The module: 'sqrt_cordic' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/the5t/OneDrive/Documents/GitHub/rwth-lab-fpga-WIP/exp_2/exp_2.gen/sources_1/ip/sqrt_cordic/sqrt_cordic_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sqrt_cordic'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/the5t/OneDrive/Documents/GitHub/rwth-lab-fpga-WIP/exp_2/exp_2.srcs/sources_1/ip/sqrt_cordic/sqrt_cordic.xci
# IP: The module: 'sqrt_cordic' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/the5t/OneDrive/Documents/GitHub/rwth-lab-fpga-WIP/exp_2/exp_2.gen/sources_1/ip/sqrt_cordic/sqrt_cordic_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sqrt_cordic'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
