// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mfcc_mfcc_Pipeline_VITIS_LOOP_180_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        abs_spectrogram_address0,
        abs_spectrogram_ce0,
        abs_spectrogram_q0,
        abs_spectrogram_address1,
        abs_spectrogram_ce1,
        abs_spectrogram_q1,
        abs_spectrogram_address2,
        abs_spectrogram_ce2,
        abs_spectrogram_q2,
        abs_spectrogram_address3,
        abs_spectrogram_ce3,
        abs_spectrogram_q3,
        abs_spectrogram_address4,
        abs_spectrogram_ce4,
        abs_spectrogram_q4,
        abs_spectrogram_address5,
        abs_spectrogram_ce5,
        abs_spectrogram_q5,
        abs_spectrogram_address6,
        abs_spectrogram_ce6,
        abs_spectrogram_q6,
        abs_spectrogram_address7,
        abs_spectrogram_ce7,
        abs_spectrogram_q7,
        abs_spectrogram_address8,
        abs_spectrogram_ce8,
        abs_spectrogram_q8,
        abs_spectrogram_address9,
        abs_spectrogram_ce9,
        abs_spectrogram_q9,
        abs_spectrogram_address10,
        abs_spectrogram_ce10,
        abs_spectrogram_q10,
        abs_spectrogram_address11,
        abs_spectrogram_ce11,
        abs_spectrogram_q11,
        abs_spectrogram_address12,
        abs_spectrogram_ce12,
        abs_spectrogram_q12,
        abs_spectrogram_address13,
        abs_spectrogram_ce13,
        abs_spectrogram_q13,
        abs_spectrogram_address14,
        abs_spectrogram_ce14,
        abs_spectrogram_q14,
        mel_filtered_address0,
        mel_filtered_ce0,
        mel_filtered_we0,
        mel_filtered_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] abs_spectrogram_address0;
output   abs_spectrogram_ce0;
input  [15:0] abs_spectrogram_q0;
output  [8:0] abs_spectrogram_address1;
output   abs_spectrogram_ce1;
input  [15:0] abs_spectrogram_q1;
output  [8:0] abs_spectrogram_address2;
output   abs_spectrogram_ce2;
input  [15:0] abs_spectrogram_q2;
output  [8:0] abs_spectrogram_address3;
output   abs_spectrogram_ce3;
input  [15:0] abs_spectrogram_q3;
output  [8:0] abs_spectrogram_address4;
output   abs_spectrogram_ce4;
input  [15:0] abs_spectrogram_q4;
output  [8:0] abs_spectrogram_address5;
output   abs_spectrogram_ce5;
input  [15:0] abs_spectrogram_q5;
output  [8:0] abs_spectrogram_address6;
output   abs_spectrogram_ce6;
input  [15:0] abs_spectrogram_q6;
output  [8:0] abs_spectrogram_address7;
output   abs_spectrogram_ce7;
input  [15:0] abs_spectrogram_q7;
output  [8:0] abs_spectrogram_address8;
output   abs_spectrogram_ce8;
input  [15:0] abs_spectrogram_q8;
output  [8:0] abs_spectrogram_address9;
output   abs_spectrogram_ce9;
input  [15:0] abs_spectrogram_q9;
output  [8:0] abs_spectrogram_address10;
output   abs_spectrogram_ce10;
input  [15:0] abs_spectrogram_q10;
output  [8:0] abs_spectrogram_address11;
output   abs_spectrogram_ce11;
input  [15:0] abs_spectrogram_q11;
output  [8:0] abs_spectrogram_address12;
output   abs_spectrogram_ce12;
input  [15:0] abs_spectrogram_q12;
output  [8:0] abs_spectrogram_address13;
output   abs_spectrogram_ce13;
input  [15:0] abs_spectrogram_q13;
output  [8:0] abs_spectrogram_address14;
output   abs_spectrogram_ce14;
input  [15:0] abs_spectrogram_q14;
output  [5:0] mel_filtered_address0;
output   mel_filtered_ce0;
output   mel_filtered_we0;
output  [15:0] mel_filtered_d0;

reg ap_idle;
reg[8:0] abs_spectrogram_address0;
reg abs_spectrogram_ce0;
reg[8:0] abs_spectrogram_address1;
reg abs_spectrogram_ce1;
reg[8:0] abs_spectrogram_address2;
reg abs_spectrogram_ce2;
reg[8:0] abs_spectrogram_address3;
reg abs_spectrogram_ce3;
reg[8:0] abs_spectrogram_address4;
reg abs_spectrogram_ce4;
reg[8:0] abs_spectrogram_address5;
reg abs_spectrogram_ce5;
reg[8:0] abs_spectrogram_address6;
reg abs_spectrogram_ce6;
reg[8:0] abs_spectrogram_address7;
reg abs_spectrogram_ce7;
reg[8:0] abs_spectrogram_address8;
reg abs_spectrogram_ce8;
reg[8:0] abs_spectrogram_address9;
reg abs_spectrogram_ce9;
reg[8:0] abs_spectrogram_address10;
reg abs_spectrogram_ce10;
reg[8:0] abs_spectrogram_address11;
reg abs_spectrogram_ce11;
reg[8:0] abs_spectrogram_address12;
reg abs_spectrogram_ce12;
reg[8:0] abs_spectrogram_address13;
reg abs_spectrogram_ce13;
reg[8:0] abs_spectrogram_address14;
reg abs_spectrogram_ce14;
reg mel_filtered_ce0;
reg mel_filtered_we0;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state4_pp0_stage1_iter1;
wire    ap_block_state6_pp0_stage1_iter2;
wire    ap_block_state8_pp0_stage1_iter3;
wire    ap_block_pp0_stage1_subdone;
reg   [0:0] icmp_ln180_reg_2158;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [5:0] first_ind_address0;
reg    first_ind_ce0;
wire   [7:0] first_ind_q0;
wire   [5:0] mel_filterbank_0_address0;
reg    mel_filterbank_0_ce0;
wire   [7:0] mel_filterbank_0_q0;
wire   [5:0] mel_filterbank_1_address0;
reg    mel_filterbank_1_ce0;
wire   [7:0] mel_filterbank_1_q0;
wire   [5:0] mel_filterbank_2_address0;
reg    mel_filterbank_2_ce0;
wire   [7:0] mel_filterbank_2_q0;
wire   [5:0] mel_filterbank_3_address0;
reg    mel_filterbank_3_ce0;
wire   [7:0] mel_filterbank_3_q0;
wire   [5:0] mel_filterbank_4_address0;
reg    mel_filterbank_4_ce0;
wire   [7:0] mel_filterbank_4_q0;
wire   [5:0] mel_filterbank_5_address0;
reg    mel_filterbank_5_ce0;
wire   [7:0] mel_filterbank_5_q0;
wire   [5:0] mel_filterbank_6_address0;
reg    mel_filterbank_6_ce0;
wire   [7:0] mel_filterbank_6_q0;
wire   [5:0] mel_filterbank_7_address0;
reg    mel_filterbank_7_ce0;
wire   [7:0] mel_filterbank_7_q0;
wire   [5:0] mel_filterbank_8_address0;
reg    mel_filterbank_8_ce0;
wire   [7:0] mel_filterbank_8_q0;
wire   [5:0] mel_filterbank_9_address0;
reg    mel_filterbank_9_ce0;
wire   [7:0] mel_filterbank_9_q0;
wire   [5:0] mel_filterbank_10_address0;
reg    mel_filterbank_10_ce0;
wire   [7:0] mel_filterbank_10_q0;
wire   [5:0] mel_filterbank_11_address0;
reg    mel_filterbank_11_ce0;
wire   [7:0] mel_filterbank_11_q0;
wire   [5:0] mel_filterbank_12_address0;
reg    mel_filterbank_12_ce0;
wire   [7:0] mel_filterbank_12_q0;
wire   [5:0] mel_filterbank_13_address0;
reg    mel_filterbank_13_ce0;
wire   [7:0] mel_filterbank_13_q0;
wire   [5:0] mel_filterbank_14_address0;
reg    mel_filterbank_14_ce0;
wire   [7:0] mel_filterbank_14_q0;
wire   [5:0] mel_filterbank_15_address0;
reg    mel_filterbank_15_ce0;
wire   [7:0] mel_filterbank_15_q0;
wire   [5:0] mel_filterbank_16_address0;
reg    mel_filterbank_16_ce0;
wire   [7:0] mel_filterbank_16_q0;
wire   [5:0] mel_filterbank_17_address0;
reg    mel_filterbank_17_ce0;
wire   [7:0] mel_filterbank_17_q0;
wire   [5:0] mel_filterbank_18_address0;
reg    mel_filterbank_18_ce0;
wire   [7:0] mel_filterbank_18_q0;
wire   [5:0] mel_filterbank_19_address0;
reg    mel_filterbank_19_ce0;
wire   [7:0] mel_filterbank_19_q0;
wire   [5:0] mel_filterbank_20_address0;
reg    mel_filterbank_20_ce0;
wire   [7:0] mel_filterbank_20_q0;
wire   [5:0] mel_filterbank_21_address0;
reg    mel_filterbank_21_ce0;
wire   [7:0] mel_filterbank_21_q0;
wire   [5:0] mel_filterbank_22_address0;
reg    mel_filterbank_22_ce0;
wire   [7:0] mel_filterbank_22_q0;
wire   [5:0] mel_filterbank_23_address0;
reg    mel_filterbank_23_ce0;
wire   [6:0] mel_filterbank_23_q0;
wire   [5:0] mel_filterbank_24_address0;
reg    mel_filterbank_24_ce0;
wire   [6:0] mel_filterbank_24_q0;
wire   [5:0] mel_filterbank_25_address0;
reg    mel_filterbank_25_ce0;
wire   [6:0] mel_filterbank_25_q0;
wire   [5:0] mel_filterbank_26_address0;
reg    mel_filterbank_26_ce0;
wire   [6:0] mel_filterbank_26_q0;
wire   [5:0] mel_filterbank_27_address0;
reg    mel_filterbank_27_ce0;
wire   [5:0] mel_filterbank_27_q0;
wire   [5:0] mel_filterbank_28_address0;
reg    mel_filterbank_28_ce0;
wire   [5:0] mel_filterbank_28_q0;
wire   [5:0] mel_filterbank_29_address0;
reg    mel_filterbank_29_ce0;
wire   [4:0] mel_filterbank_29_q0;
reg  signed [15:0] reg_889;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state7_pp0_stage0_iter3;
wire    ap_block_state9_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_11001;
wire    ap_block_pp0_stage1_11001;
reg  signed [15:0] reg_893;
reg  signed [15:0] reg_897;
reg  signed [15:0] reg_901;
reg  signed [15:0] reg_905;
reg  signed [15:0] reg_909;
reg  signed [15:0] reg_913;
reg  signed [15:0] reg_917;
reg  signed [15:0] reg_921;
reg  signed [15:0] reg_925;
reg  signed [15:0] reg_929;
reg  signed [15:0] reg_933;
reg  signed [15:0] reg_937;
reg  signed [15:0] reg_941;
reg  signed [15:0] reg_945;
wire   [0:0] icmp_ln180_fu_957_p2;
reg   [0:0] icmp_ln180_reg_2158_pp0_iter1_reg;
reg   [0:0] icmp_ln180_reg_2158_pp0_iter2_reg;
wire   [63:0] m_cast_fu_969_p1;
reg   [63:0] m_cast_reg_2162;
reg   [63:0] m_cast_reg_2162_pp0_iter1_reg;
reg   [63:0] m_cast_reg_2162_pp0_iter2_reg;
reg   [63:0] m_cast_reg_2162_pp0_iter3_reg;
reg   [7:0] first_ind_load_reg_2206;
reg   [7:0] mel_filterbank_0_load_reg_2216;
wire   [8:0] zext_ln187_fu_985_p1;
reg   [8:0] zext_ln187_reg_2221;
reg   [15:0] trunc_ln1_reg_2459;
reg   [15:0] trunc_ln1_reg_2459_pp0_iter2_reg;
reg   [7:0] mel_filterbank_1_load_reg_2469;
reg   [7:0] mel_filterbank_2_load_reg_2479;
reg   [7:0] mel_filterbank_3_load_reg_2484;
reg   [7:0] mel_filterbank_4_load_reg_2489;
reg   [7:0] mel_filterbank_5_load_reg_2494;
reg   [7:0] mel_filterbank_6_load_reg_2499;
reg   [7:0] mel_filterbank_7_load_reg_2509;
reg   [7:0] mel_filterbank_8_load_reg_2519;
reg   [7:0] mel_filterbank_9_load_reg_2529;
reg   [7:0] mel_filterbank_10_load_reg_2539;
reg   [7:0] mel_filterbank_11_load_reg_2544;
reg   [7:0] mel_filterbank_12_load_reg_2549;
reg   [7:0] mel_filterbank_13_load_reg_2554;
reg   [7:0] mel_filterbank_14_load_reg_2559;
reg   [7:0] mel_filterbank_15_load_reg_2564;
reg   [7:0] mel_filterbank_16_load_reg_2569;
reg   [7:0] mel_filterbank_17_load_reg_2574;
reg   [7:0] mel_filterbank_18_load_reg_2584;
reg   [7:0] mel_filterbank_19_load_reg_2594;
reg   [7:0] mel_filterbank_20_load_reg_2604;
reg   [7:0] mel_filterbank_21_load_reg_2614;
reg   [7:0] mel_filterbank_22_load_reg_2624;
reg   [6:0] mel_filterbank_23_load_reg_2634;
reg   [6:0] mel_filterbank_24_load_reg_2644;
reg   [6:0] mel_filterbank_25_load_reg_2654;
reg   [6:0] mel_filterbank_26_load_reg_2659;
reg   [5:0] mel_filterbank_27_load_reg_2664;
reg   [5:0] mel_filterbank_28_load_reg_2669;
reg   [4:0] mel_filterbank_29_load_reg_2674;
reg   [15:0] trunc_ln187_3_reg_2679;
reg   [15:0] trunc_ln187_4_reg_2684;
reg   [15:0] trunc_ln187_5_reg_2689;
reg   [15:0] trunc_ln187_6_reg_2694;
reg   [15:0] trunc_ln187_10_reg_2699;
reg   [15:0] trunc_ln187_11_reg_2704;
reg   [15:0] trunc_ln187_12_reg_2709;
reg   [15:0] trunc_ln187_13_reg_2714;
reg   [15:0] trunc_ln187_14_reg_2719;
reg   [15:0] trunc_ln187_15_reg_2724;
reg   [15:0] trunc_ln187_16_reg_2729;
reg   [14:0] trunc_ln187_25_reg_2734;
reg   [13:0] trunc_ln187_26_reg_2739;
reg   [13:0] trunc_ln187_27_reg_2744;
reg   [12:0] trunc_ln187_28_reg_2749;
reg   [15:0] trunc_ln187_1_reg_2754;
reg   [15:0] trunc_ln187_2_reg_2759;
reg   [15:0] trunc_ln187_7_reg_2764;
reg   [15:0] trunc_ln187_8_reg_2769;
reg   [15:0] trunc_ln187_9_reg_2774;
reg   [15:0] trunc_ln187_s_reg_2779;
reg   [15:0] trunc_ln187_17_reg_2784;
reg   [15:0] trunc_ln187_18_reg_2789;
reg   [15:0] trunc_ln187_19_reg_2794;
reg   [15:0] trunc_ln187_20_reg_2799;
reg   [15:0] trunc_ln187_21_reg_2804;
reg   [14:0] trunc_ln187_22_reg_2809;
reg   [14:0] trunc_ln187_23_reg_2814;
reg   [14:0] trunc_ln187_24_reg_2819;
wire   [15:0] add_ln187_33_fu_2003_p2;
reg   [15:0] add_ln187_33_reg_2824;
wire   [15:0] add_ln187_40_fu_2017_p2;
reg   [15:0] add_ln187_40_reg_2829;
wire   [15:0] add_ln187_44_fu_2027_p2;
reg   [15:0] add_ln187_44_reg_2834;
wire   [15:0] add_ln187_54_fu_2048_p2;
reg   [15:0] add_ln187_54_reg_2839;
wire   [15:0] add_ln187_34_fu_2072_p2;
reg   [15:0] add_ln187_34_reg_2844;
wire   [15:0] add_ln187_41_fu_2091_p2;
reg   [15:0] add_ln187_41_reg_2849;
wire   [15:0] add_ln187_47_fu_2104_p2;
reg   [15:0] add_ln187_47_reg_2854;
wire   [15:0] add_ln187_55_fu_2127_p2;
reg   [15:0] add_ln187_55_reg_2859;
wire   [15:0] add_ln187_56_fu_2136_p2;
reg   [15:0] add_ln187_56_reg_2864;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage0_subdone;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln186_fu_980_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln187_6_fu_994_p1;
wire   [63:0] zext_ln187_8_fu_1005_p1;
wire   [63:0] zext_ln187_10_fu_1016_p1;
wire   [63:0] zext_ln187_12_fu_1027_p1;
wire   [63:0] zext_ln187_22_fu_1038_p1;
wire   [63:0] zext_ln187_24_fu_1049_p1;
wire   [63:0] zext_ln187_26_fu_1060_p1;
wire   [63:0] zext_ln187_28_fu_1071_p1;
wire   [63:0] zext_ln187_30_fu_1082_p1;
wire   [63:0] zext_ln187_32_fu_1093_p1;
wire   [63:0] zext_ln187_34_fu_1104_p1;
wire   [63:0] zext_ln187_52_fu_1115_p1;
wire   [63:0] zext_ln187_54_fu_1126_p1;
wire   [63:0] zext_ln187_56_fu_1137_p1;
wire   [63:0] zext_ln187_58_fu_1148_p1;
wire   [63:0] zext_ln187_2_fu_1181_p1;
wire   [63:0] zext_ln187_4_fu_1191_p1;
wire   [63:0] zext_ln187_14_fu_1201_p1;
wire   [63:0] zext_ln187_16_fu_1211_p1;
wire   [63:0] zext_ln187_18_fu_1221_p1;
wire   [63:0] zext_ln187_20_fu_1231_p1;
wire   [63:0] zext_ln187_36_fu_1241_p1;
wire   [63:0] zext_ln187_38_fu_1251_p1;
wire   [63:0] zext_ln187_40_fu_1261_p1;
wire   [63:0] zext_ln187_42_fu_1271_p1;
wire   [63:0] zext_ln187_44_fu_1281_p1;
wire   [63:0] zext_ln187_46_fu_1291_p1;
wire   [63:0] zext_ln187_48_fu_1301_p1;
wire   [63:0] zext_ln187_50_fu_1311_p1;
reg   [5:0] m_fu_168;
wire   [5:0] add_ln180_fu_963_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_m_2;
wire   [8:0] add_ln187_2_fu_988_p2;
wire   [8:0] add_ln187_3_fu_999_p2;
wire   [8:0] add_ln187_4_fu_1010_p2;
wire   [8:0] add_ln187_5_fu_1021_p2;
wire   [8:0] add_ln187_10_fu_1032_p2;
wire   [8:0] add_ln187_11_fu_1043_p2;
wire   [8:0] add_ln187_12_fu_1054_p2;
wire   [8:0] add_ln187_13_fu_1065_p2;
wire   [8:0] add_ln187_14_fu_1076_p2;
wire   [8:0] add_ln187_15_fu_1087_p2;
wire   [8:0] add_ln187_16_fu_1098_p2;
wire   [8:0] add_ln187_25_fu_1109_p2;
wire   [8:0] add_ln187_26_fu_1120_p2;
wire   [8:0] add_ln187_27_fu_1131_p2;
wire   [8:0] add_ln187_28_fu_1142_p2;
wire   [7:0] mul_ln187_fu_1160_p0;
wire   [23:0] mul_ln187_fu_1160_p2;
wire   [8:0] add_ln187_fu_1176_p2;
wire   [8:0] add_ln187_1_fu_1186_p2;
wire   [8:0] add_ln187_6_fu_1196_p2;
wire   [8:0] add_ln187_7_fu_1206_p2;
wire   [8:0] add_ln187_8_fu_1216_p2;
wire   [8:0] add_ln187_9_fu_1226_p2;
wire   [8:0] add_ln187_17_fu_1236_p2;
wire   [8:0] add_ln187_18_fu_1246_p2;
wire   [8:0] add_ln187_19_fu_1256_p2;
wire   [8:0] add_ln187_20_fu_1266_p2;
wire   [8:0] add_ln187_21_fu_1276_p2;
wire   [8:0] add_ln187_22_fu_1286_p2;
wire   [8:0] add_ln187_23_fu_1296_p2;
wire   [8:0] add_ln187_24_fu_1306_p2;
wire   [7:0] mul_ln187_3_fu_1323_p0;
wire   [23:0] mul_ln187_3_fu_1323_p2;
wire   [7:0] mul_ln187_4_fu_1346_p0;
wire   [23:0] mul_ln187_4_fu_1346_p2;
wire   [7:0] mul_ln187_5_fu_1369_p0;
wire   [23:0] mul_ln187_5_fu_1369_p2;
wire   [7:0] mul_ln187_6_fu_1392_p0;
wire   [23:0] mul_ln187_6_fu_1392_p2;
wire   [7:0] mul_ln187_11_fu_1415_p0;
wire   [23:0] mul_ln187_11_fu_1415_p2;
wire   [7:0] mul_ln187_12_fu_1438_p0;
wire   [23:0] mul_ln187_12_fu_1438_p2;
wire   [7:0] mul_ln187_13_fu_1461_p0;
wire   [23:0] mul_ln187_13_fu_1461_p2;
wire   [7:0] mul_ln187_14_fu_1484_p0;
wire   [23:0] mul_ln187_14_fu_1484_p2;
wire   [7:0] mul_ln187_15_fu_1507_p0;
wire   [23:0] mul_ln187_15_fu_1507_p2;
wire   [7:0] mul_ln187_16_fu_1530_p0;
wire   [23:0] mul_ln187_16_fu_1530_p2;
wire   [7:0] mul_ln187_17_fu_1553_p0;
wire   [23:0] mul_ln187_17_fu_1553_p2;
wire   [6:0] mul_ln187_26_fu_1576_p0;
wire   [22:0] mul_ln187_26_fu_1576_p2;
wire   [5:0] mul_ln187_27_fu_1599_p0;
wire   [21:0] mul_ln187_27_fu_1599_p2;
wire   [5:0] mul_ln187_28_fu_1622_p0;
wire   [21:0] mul_ln187_28_fu_1622_p2;
wire   [4:0] mul_ln187_29_fu_1645_p0;
wire   [20:0] mul_ln187_29_fu_1645_p2;
wire   [7:0] mul_ln187_1_fu_1668_p0;
wire   [23:0] mul_ln187_1_fu_1668_p2;
wire   [7:0] mul_ln187_2_fu_1691_p0;
wire   [23:0] mul_ln187_2_fu_1691_p2;
wire   [7:0] mul_ln187_7_fu_1714_p0;
wire   [23:0] mul_ln187_7_fu_1714_p2;
wire   [7:0] mul_ln187_8_fu_1737_p0;
wire   [23:0] mul_ln187_8_fu_1737_p2;
wire   [7:0] mul_ln187_9_fu_1760_p0;
wire   [23:0] mul_ln187_9_fu_1760_p2;
wire   [7:0] mul_ln187_10_fu_1783_p0;
wire   [23:0] mul_ln187_10_fu_1783_p2;
wire   [7:0] mul_ln187_18_fu_1806_p0;
wire   [23:0] mul_ln187_18_fu_1806_p2;
wire   [7:0] mul_ln187_19_fu_1829_p0;
wire   [23:0] mul_ln187_19_fu_1829_p2;
wire   [7:0] mul_ln187_20_fu_1852_p0;
wire   [23:0] mul_ln187_20_fu_1852_p2;
wire   [7:0] mul_ln187_21_fu_1875_p0;
wire   [23:0] mul_ln187_21_fu_1875_p2;
wire   [7:0] mul_ln187_22_fu_1898_p0;
wire   [23:0] mul_ln187_22_fu_1898_p2;
wire   [6:0] mul_ln187_23_fu_1921_p0;
wire   [22:0] mul_ln187_23_fu_1921_p2;
wire   [6:0] mul_ln187_24_fu_1944_p0;
wire   [22:0] mul_ln187_24_fu_1944_p2;
wire   [6:0] mul_ln187_25_fu_1967_p0;
wire   [22:0] mul_ln187_25_fu_1967_p2;
wire   [15:0] add_ln187_32_fu_1999_p2;
wire   [15:0] add_ln187_31_fu_1995_p2;
wire   [15:0] add_ln187_39_fu_2013_p2;
wire   [15:0] add_ln187_38_fu_2009_p2;
wire   [15:0] add_ln187_43_fu_2023_p2;
wire  signed [15:0] sext_ln187_30_fu_1983_p1;
wire  signed [15:0] sext_ln187_32_fu_1986_p1;
wire  signed [14:0] sext_ln187_34_fu_1989_p1;
wire  signed [14:0] sext_ln187_36_fu_1992_p1;
wire   [14:0] add_ln187_53_fu_2038_p2;
wire  signed [15:0] sext_ln187_37_fu_2044_p1;
wire   [15:0] add_ln187_52_fu_2032_p2;
wire   [15:0] add_ln187_29_fu_2063_p2;
wire   [15:0] add_ln187_30_fu_2067_p2;
wire   [15:0] add_ln187_36_fu_2081_p2;
wire   [15:0] add_ln187_35_fu_2077_p2;
wire   [15:0] add_ln187_37_fu_2085_p2;
wire   [15:0] add_ln187_46_fu_2100_p2;
wire   [15:0] add_ln187_45_fu_2096_p2;
wire  signed [15:0] sext_ln187_24_fu_2054_p1;
wire  signed [15:0] sext_ln187_26_fu_2057_p1;
wire  signed [15:0] sext_ln187_28_fu_2060_p1;
wire   [15:0] add_ln187_50_fu_2115_p2;
wire   [15:0] add_ln187_49_fu_2110_p2;
wire   [15:0] add_ln187_51_fu_2121_p2;
wire   [15:0] add_ln187_48_fu_2132_p2;
wire   [15:0] add_ln187_42_fu_2141_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter3_stage0;
reg    ap_idle_pp0_0to2;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_1to4;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [23:0] mul_ln187_10_fu_1783_p00;
wire   [23:0] mul_ln187_11_fu_1415_p00;
wire   [23:0] mul_ln187_12_fu_1438_p00;
wire   [23:0] mul_ln187_13_fu_1461_p00;
wire   [23:0] mul_ln187_14_fu_1484_p00;
wire   [23:0] mul_ln187_15_fu_1507_p00;
wire   [23:0] mul_ln187_16_fu_1530_p00;
wire   [23:0] mul_ln187_17_fu_1553_p00;
wire   [23:0] mul_ln187_18_fu_1806_p00;
wire   [23:0] mul_ln187_19_fu_1829_p00;
wire   [23:0] mul_ln187_1_fu_1668_p00;
wire   [23:0] mul_ln187_20_fu_1852_p00;
wire   [23:0] mul_ln187_21_fu_1875_p00;
wire   [23:0] mul_ln187_22_fu_1898_p00;
wire   [22:0] mul_ln187_23_fu_1921_p00;
wire   [22:0] mul_ln187_24_fu_1944_p00;
wire   [22:0] mul_ln187_25_fu_1967_p00;
wire   [22:0] mul_ln187_26_fu_1576_p00;
wire   [21:0] mul_ln187_27_fu_1599_p00;
wire   [21:0] mul_ln187_28_fu_1622_p00;
wire   [20:0] mul_ln187_29_fu_1645_p00;
wire   [23:0] mul_ln187_2_fu_1691_p00;
wire   [23:0] mul_ln187_3_fu_1323_p00;
wire   [23:0] mul_ln187_4_fu_1346_p00;
wire   [23:0] mul_ln187_5_fu_1369_p00;
wire   [23:0] mul_ln187_6_fu_1392_p00;
wire   [23:0] mul_ln187_7_fu_1714_p00;
wire   [23:0] mul_ln187_8_fu_1737_p00;
wire   [23:0] mul_ln187_9_fu_1760_p00;
wire   [23:0] mul_ln187_fu_1160_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_first_ind_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 42 ),
    .AddressWidth( 6 ))
first_ind_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(first_ind_address0),
    .ce0(first_ind_ce0),
    .q0(first_ind_q0)
);

mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_0_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 42 ),
    .AddressWidth( 6 ))
mel_filterbank_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mel_filterbank_0_address0),
    .ce0(mel_filterbank_0_ce0),
    .q0(mel_filterbank_0_q0)
);

mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_1_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 42 ),
    .AddressWidth( 6 ))
mel_filterbank_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mel_filterbank_1_address0),
    .ce0(mel_filterbank_1_ce0),
    .q0(mel_filterbank_1_q0)
);

mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_2_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 42 ),
    .AddressWidth( 6 ))
mel_filterbank_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mel_filterbank_2_address0),
    .ce0(mel_filterbank_2_ce0),
    .q0(mel_filterbank_2_q0)
);

mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_3_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 42 ),
    .AddressWidth( 6 ))
mel_filterbank_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mel_filterbank_3_address0),
    .ce0(mel_filterbank_3_ce0),
    .q0(mel_filterbank_3_q0)
);

mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_4_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 42 ),
    .AddressWidth( 6 ))
mel_filterbank_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mel_filterbank_4_address0),
    .ce0(mel_filterbank_4_ce0),
    .q0(mel_filterbank_4_q0)
);

mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_5_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 42 ),
    .AddressWidth( 6 ))
mel_filterbank_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mel_filterbank_5_address0),
    .ce0(mel_filterbank_5_ce0),
    .q0(mel_filterbank_5_q0)
);

mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_6_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 42 ),
    .AddressWidth( 6 ))
mel_filterbank_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mel_filterbank_6_address0),
    .ce0(mel_filterbank_6_ce0),
    .q0(mel_filterbank_6_q0)
);

mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_7_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 42 ),
    .AddressWidth( 6 ))
mel_filterbank_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mel_filterbank_7_address0),
    .ce0(mel_filterbank_7_ce0),
    .q0(mel_filterbank_7_q0)
);

mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_8_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 42 ),
    .AddressWidth( 6 ))
mel_filterbank_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mel_filterbank_8_address0),
    .ce0(mel_filterbank_8_ce0),
    .q0(mel_filterbank_8_q0)
);

mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_9_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 42 ),
    .AddressWidth( 6 ))
mel_filterbank_9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mel_filterbank_9_address0),
    .ce0(mel_filterbank_9_ce0),
    .q0(mel_filterbank_9_q0)
);

mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_10_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 42 ),
    .AddressWidth( 6 ))
mel_filterbank_10_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mel_filterbank_10_address0),
    .ce0(mel_filterbank_10_ce0),
    .q0(mel_filterbank_10_q0)
);

mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_11_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 42 ),
    .AddressWidth( 6 ))
mel_filterbank_11_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mel_filterbank_11_address0),
    .ce0(mel_filterbank_11_ce0),
    .q0(mel_filterbank_11_q0)
);

mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_12_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 42 ),
    .AddressWidth( 6 ))
mel_filterbank_12_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mel_filterbank_12_address0),
    .ce0(mel_filterbank_12_ce0),
    .q0(mel_filterbank_12_q0)
);

mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_13_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 42 ),
    .AddressWidth( 6 ))
mel_filterbank_13_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mel_filterbank_13_address0),
    .ce0(mel_filterbank_13_ce0),
    .q0(mel_filterbank_13_q0)
);

mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_14_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 42 ),
    .AddressWidth( 6 ))
mel_filterbank_14_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mel_filterbank_14_address0),
    .ce0(mel_filterbank_14_ce0),
    .q0(mel_filterbank_14_q0)
);

mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_15_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 42 ),
    .AddressWidth( 6 ))
mel_filterbank_15_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mel_filterbank_15_address0),
    .ce0(mel_filterbank_15_ce0),
    .q0(mel_filterbank_15_q0)
);

mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_16_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 42 ),
    .AddressWidth( 6 ))
mel_filterbank_16_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mel_filterbank_16_address0),
    .ce0(mel_filterbank_16_ce0),
    .q0(mel_filterbank_16_q0)
);

mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_17_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 42 ),
    .AddressWidth( 6 ))
mel_filterbank_17_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mel_filterbank_17_address0),
    .ce0(mel_filterbank_17_ce0),
    .q0(mel_filterbank_17_q0)
);

mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_18_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 42 ),
    .AddressWidth( 6 ))
mel_filterbank_18_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mel_filterbank_18_address0),
    .ce0(mel_filterbank_18_ce0),
    .q0(mel_filterbank_18_q0)
);

mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_19_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 42 ),
    .AddressWidth( 6 ))
mel_filterbank_19_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mel_filterbank_19_address0),
    .ce0(mel_filterbank_19_ce0),
    .q0(mel_filterbank_19_q0)
);

mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_20_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 42 ),
    .AddressWidth( 6 ))
mel_filterbank_20_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mel_filterbank_20_address0),
    .ce0(mel_filterbank_20_ce0),
    .q0(mel_filterbank_20_q0)
);

mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_21_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 42 ),
    .AddressWidth( 6 ))
mel_filterbank_21_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mel_filterbank_21_address0),
    .ce0(mel_filterbank_21_ce0),
    .q0(mel_filterbank_21_q0)
);

mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_22_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 42 ),
    .AddressWidth( 6 ))
mel_filterbank_22_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mel_filterbank_22_address0),
    .ce0(mel_filterbank_22_ce0),
    .q0(mel_filterbank_22_q0)
);

mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_23_ROM_AUTO_1R #(
    .DataWidth( 7 ),
    .AddressRange( 42 ),
    .AddressWidth( 6 ))
mel_filterbank_23_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mel_filterbank_23_address0),
    .ce0(mel_filterbank_23_ce0),
    .q0(mel_filterbank_23_q0)
);

mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_24_ROM_AUTO_1R #(
    .DataWidth( 7 ),
    .AddressRange( 42 ),
    .AddressWidth( 6 ))
mel_filterbank_24_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mel_filterbank_24_address0),
    .ce0(mel_filterbank_24_ce0),
    .q0(mel_filterbank_24_q0)
);

mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_25_ROM_AUTO_1R #(
    .DataWidth( 7 ),
    .AddressRange( 42 ),
    .AddressWidth( 6 ))
mel_filterbank_25_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mel_filterbank_25_address0),
    .ce0(mel_filterbank_25_ce0),
    .q0(mel_filterbank_25_q0)
);

mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_26_ROM_AUTO_1R #(
    .DataWidth( 7 ),
    .AddressRange( 42 ),
    .AddressWidth( 6 ))
mel_filterbank_26_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mel_filterbank_26_address0),
    .ce0(mel_filterbank_26_ce0),
    .q0(mel_filterbank_26_q0)
);

mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_27_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 42 ),
    .AddressWidth( 6 ))
mel_filterbank_27_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mel_filterbank_27_address0),
    .ce0(mel_filterbank_27_ce0),
    .q0(mel_filterbank_27_q0)
);

mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_28_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 42 ),
    .AddressWidth( 6 ))
mel_filterbank_28_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mel_filterbank_28_address0),
    .ce0(mel_filterbank_28_ce0),
    .q0(mel_filterbank_28_q0)
);

mfcc_mfcc_Pipeline_VITIS_LOOP_180_1_mel_filterbank_29_ROM_AUTO_1R #(
    .DataWidth( 5 ),
    .AddressRange( 42 ),
    .AddressWidth( 6 ))
mel_filterbank_29_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mel_filterbank_29_address0),
    .ce0(mel_filterbank_29_ce0),
    .q0(mel_filterbank_29_q0)
);

mfcc_mul_8ns_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_1_1_U6(
    .din0(mul_ln187_fu_1160_p0),
    .din1(reg_889),
    .dout(mul_ln187_fu_1160_p2)
);

mfcc_mul_8ns_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_1_1_U7(
    .din0(mul_ln187_3_fu_1323_p0),
    .din1(reg_889),
    .dout(mul_ln187_3_fu_1323_p2)
);

mfcc_mul_8ns_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_1_1_U8(
    .din0(mul_ln187_4_fu_1346_p0),
    .din1(reg_893),
    .dout(mul_ln187_4_fu_1346_p2)
);

mfcc_mul_8ns_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_1_1_U9(
    .din0(mul_ln187_5_fu_1369_p0),
    .din1(reg_897),
    .dout(mul_ln187_5_fu_1369_p2)
);

mfcc_mul_8ns_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_1_1_U10(
    .din0(mul_ln187_6_fu_1392_p0),
    .din1(reg_901),
    .dout(mul_ln187_6_fu_1392_p2)
);

mfcc_mul_8ns_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_1_1_U11(
    .din0(mul_ln187_11_fu_1415_p0),
    .din1(reg_905),
    .dout(mul_ln187_11_fu_1415_p2)
);

mfcc_mul_8ns_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_1_1_U12(
    .din0(mul_ln187_12_fu_1438_p0),
    .din1(reg_909),
    .dout(mul_ln187_12_fu_1438_p2)
);

mfcc_mul_8ns_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_1_1_U13(
    .din0(mul_ln187_13_fu_1461_p0),
    .din1(reg_913),
    .dout(mul_ln187_13_fu_1461_p2)
);

mfcc_mul_8ns_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_1_1_U14(
    .din0(mul_ln187_14_fu_1484_p0),
    .din1(reg_917),
    .dout(mul_ln187_14_fu_1484_p2)
);

mfcc_mul_8ns_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_1_1_U15(
    .din0(mul_ln187_15_fu_1507_p0),
    .din1(reg_921),
    .dout(mul_ln187_15_fu_1507_p2)
);

mfcc_mul_8ns_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_1_1_U16(
    .din0(mul_ln187_16_fu_1530_p0),
    .din1(reg_925),
    .dout(mul_ln187_16_fu_1530_p2)
);

mfcc_mul_8ns_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_1_1_U17(
    .din0(mul_ln187_17_fu_1553_p0),
    .din1(reg_929),
    .dout(mul_ln187_17_fu_1553_p2)
);

mfcc_mul_7ns_16s_23_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 23 ))
mul_7ns_16s_23_1_1_U18(
    .din0(mul_ln187_26_fu_1576_p0),
    .din1(reg_933),
    .dout(mul_ln187_26_fu_1576_p2)
);

mfcc_mul_6ns_16s_22_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 22 ))
mul_6ns_16s_22_1_1_U19(
    .din0(mul_ln187_27_fu_1599_p0),
    .din1(reg_937),
    .dout(mul_ln187_27_fu_1599_p2)
);

mfcc_mul_6ns_16s_22_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 22 ))
mul_6ns_16s_22_1_1_U20(
    .din0(mul_ln187_28_fu_1622_p0),
    .din1(reg_941),
    .dout(mul_ln187_28_fu_1622_p2)
);

mfcc_mul_5ns_16s_21_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
mul_5ns_16s_21_1_1_U21(
    .din0(mul_ln187_29_fu_1645_p0),
    .din1(reg_945),
    .dout(mul_ln187_29_fu_1645_p2)
);

mfcc_mul_8ns_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_1_1_U22(
    .din0(mul_ln187_1_fu_1668_p0),
    .din1(reg_893),
    .dout(mul_ln187_1_fu_1668_p2)
);

mfcc_mul_8ns_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_1_1_U23(
    .din0(mul_ln187_2_fu_1691_p0),
    .din1(reg_897),
    .dout(mul_ln187_2_fu_1691_p2)
);

mfcc_mul_8ns_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_1_1_U24(
    .din0(mul_ln187_7_fu_1714_p0),
    .din1(reg_901),
    .dout(mul_ln187_7_fu_1714_p2)
);

mfcc_mul_8ns_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_1_1_U25(
    .din0(mul_ln187_8_fu_1737_p0),
    .din1(reg_905),
    .dout(mul_ln187_8_fu_1737_p2)
);

mfcc_mul_8ns_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_1_1_U26(
    .din0(mul_ln187_9_fu_1760_p0),
    .din1(reg_909),
    .dout(mul_ln187_9_fu_1760_p2)
);

mfcc_mul_8ns_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_1_1_U27(
    .din0(mul_ln187_10_fu_1783_p0),
    .din1(reg_913),
    .dout(mul_ln187_10_fu_1783_p2)
);

mfcc_mul_8ns_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_1_1_U28(
    .din0(mul_ln187_18_fu_1806_p0),
    .din1(reg_917),
    .dout(mul_ln187_18_fu_1806_p2)
);

mfcc_mul_8ns_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_1_1_U29(
    .din0(mul_ln187_19_fu_1829_p0),
    .din1(reg_921),
    .dout(mul_ln187_19_fu_1829_p2)
);

mfcc_mul_8ns_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_1_1_U30(
    .din0(mul_ln187_20_fu_1852_p0),
    .din1(reg_925),
    .dout(mul_ln187_20_fu_1852_p2)
);

mfcc_mul_8ns_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_1_1_U31(
    .din0(mul_ln187_21_fu_1875_p0),
    .din1(reg_929),
    .dout(mul_ln187_21_fu_1875_p2)
);

mfcc_mul_8ns_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_1_1_U32(
    .din0(mul_ln187_22_fu_1898_p0),
    .din1(reg_933),
    .dout(mul_ln187_22_fu_1898_p2)
);

mfcc_mul_7ns_16s_23_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 23 ))
mul_7ns_16s_23_1_1_U33(
    .din0(mul_ln187_23_fu_1921_p0),
    .din1(reg_937),
    .dout(mul_ln187_23_fu_1921_p2)
);

mfcc_mul_7ns_16s_23_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 23 ))
mul_7ns_16s_23_1_1_U34(
    .din0(mul_ln187_24_fu_1944_p0),
    .din1(reg_941),
    .dout(mul_ln187_24_fu_1944_p2)
);

mfcc_mul_7ns_16s_23_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 23 ))
mul_7ns_16s_23_1_1_U35(
    .din0(mul_ln187_25_fu_1967_p0),
    .din1(reg_945),
    .dout(mul_ln187_25_fu_1967_p2)
);

mfcc_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter3_stage0) & (ap_idle_pp0_0to2 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter3_stage0) & (ap_idle_pp0_0to2 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter3_stage0) & (ap_idle_pp0_0to2 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln180_fu_957_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            m_fu_168 <= add_ln180_fu_963_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            m_fu_168 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln187_33_reg_2824 <= add_ln187_33_fu_2003_p2;
        add_ln187_40_reg_2829 <= add_ln187_40_fu_2017_p2;
        add_ln187_44_reg_2834 <= add_ln187_44_fu_2027_p2;
        add_ln187_54_reg_2839 <= add_ln187_54_fu_2048_p2;
        add_ln187_56_reg_2864 <= add_ln187_56_fu_2136_p2;
        mel_filterbank_10_load_reg_2539 <= mel_filterbank_10_q0;
        mel_filterbank_11_load_reg_2544 <= mel_filterbank_11_q0;
        mel_filterbank_12_load_reg_2549 <= mel_filterbank_12_q0;
        mel_filterbank_13_load_reg_2554 <= mel_filterbank_13_q0;
        mel_filterbank_14_load_reg_2559 <= mel_filterbank_14_q0;
        mel_filterbank_15_load_reg_2564 <= mel_filterbank_15_q0;
        mel_filterbank_16_load_reg_2569 <= mel_filterbank_16_q0;
        mel_filterbank_17_load_reg_2574 <= mel_filterbank_17_q0;
        mel_filterbank_18_load_reg_2584 <= mel_filterbank_18_q0;
        mel_filterbank_19_load_reg_2594 <= mel_filterbank_19_q0;
        mel_filterbank_1_load_reg_2469 <= mel_filterbank_1_q0;
        mel_filterbank_20_load_reg_2604 <= mel_filterbank_20_q0;
        mel_filterbank_21_load_reg_2614 <= mel_filterbank_21_q0;
        mel_filterbank_22_load_reg_2624 <= mel_filterbank_22_q0;
        mel_filterbank_23_load_reg_2634 <= mel_filterbank_23_q0;
        mel_filterbank_24_load_reg_2644 <= mel_filterbank_24_q0;
        mel_filterbank_25_load_reg_2654 <= mel_filterbank_25_q0;
        mel_filterbank_26_load_reg_2659 <= mel_filterbank_26_q0;
        mel_filterbank_27_load_reg_2664 <= mel_filterbank_27_q0;
        mel_filterbank_28_load_reg_2669 <= mel_filterbank_28_q0;
        mel_filterbank_29_load_reg_2674 <= mel_filterbank_29_q0;
        mel_filterbank_2_load_reg_2479 <= mel_filterbank_2_q0;
        mel_filterbank_3_load_reg_2484 <= mel_filterbank_3_q0;
        mel_filterbank_4_load_reg_2489 <= mel_filterbank_4_q0;
        mel_filterbank_5_load_reg_2494 <= mel_filterbank_5_q0;
        mel_filterbank_6_load_reg_2499 <= mel_filterbank_6_q0;
        mel_filterbank_7_load_reg_2509 <= mel_filterbank_7_q0;
        mel_filterbank_8_load_reg_2519 <= mel_filterbank_8_q0;
        mel_filterbank_9_load_reg_2529 <= mel_filterbank_9_q0;
        trunc_ln187_17_reg_2784 <= {{mul_ln187_18_fu_1806_p2[23:8]}};
        trunc_ln187_18_reg_2789 <= {{mul_ln187_19_fu_1829_p2[23:8]}};
        trunc_ln187_19_reg_2794 <= {{mul_ln187_20_fu_1852_p2[23:8]}};
        trunc_ln187_1_reg_2754 <= {{mul_ln187_1_fu_1668_p2[23:8]}};
        trunc_ln187_20_reg_2799 <= {{mul_ln187_21_fu_1875_p2[23:8]}};
        trunc_ln187_21_reg_2804 <= {{mul_ln187_22_fu_1898_p2[23:8]}};
        trunc_ln187_22_reg_2809 <= {{mul_ln187_23_fu_1921_p2[22:8]}};
        trunc_ln187_23_reg_2814 <= {{mul_ln187_24_fu_1944_p2[22:8]}};
        trunc_ln187_24_reg_2819 <= {{mul_ln187_25_fu_1967_p2[22:8]}};
        trunc_ln187_2_reg_2759 <= {{mul_ln187_2_fu_1691_p2[23:8]}};
        trunc_ln187_7_reg_2764 <= {{mul_ln187_7_fu_1714_p2[23:8]}};
        trunc_ln187_8_reg_2769 <= {{mul_ln187_8_fu_1737_p2[23:8]}};
        trunc_ln187_9_reg_2774 <= {{mul_ln187_9_fu_1760_p2[23:8]}};
        trunc_ln187_s_reg_2779 <= {{mul_ln187_10_fu_1783_p2[23:8]}};
        trunc_ln1_reg_2459 <= {{mul_ln187_fu_1160_p2[23:8]}};
        trunc_ln1_reg_2459_pp0_iter2_reg <= trunc_ln1_reg_2459;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln187_34_reg_2844 <= add_ln187_34_fu_2072_p2;
        add_ln187_41_reg_2849 <= add_ln187_41_fu_2091_p2;
        add_ln187_47_reg_2854 <= add_ln187_47_fu_2104_p2;
        add_ln187_55_reg_2859 <= add_ln187_55_fu_2127_p2;
        icmp_ln180_reg_2158 <= icmp_ln180_fu_957_p2;
        icmp_ln180_reg_2158_pp0_iter1_reg <= icmp_ln180_reg_2158;
        icmp_ln180_reg_2158_pp0_iter2_reg <= icmp_ln180_reg_2158_pp0_iter1_reg;
        m_cast_reg_2162_pp0_iter1_reg[5 : 0] <= m_cast_reg_2162[5 : 0];
        m_cast_reg_2162_pp0_iter2_reg[5 : 0] <= m_cast_reg_2162_pp0_iter1_reg[5 : 0];
        m_cast_reg_2162_pp0_iter3_reg[5 : 0] <= m_cast_reg_2162_pp0_iter2_reg[5 : 0];
        trunc_ln187_10_reg_2699 <= {{mul_ln187_11_fu_1415_p2[23:8]}};
        trunc_ln187_11_reg_2704 <= {{mul_ln187_12_fu_1438_p2[23:8]}};
        trunc_ln187_12_reg_2709 <= {{mul_ln187_13_fu_1461_p2[23:8]}};
        trunc_ln187_13_reg_2714 <= {{mul_ln187_14_fu_1484_p2[23:8]}};
        trunc_ln187_14_reg_2719 <= {{mul_ln187_15_fu_1507_p2[23:8]}};
        trunc_ln187_15_reg_2724 <= {{mul_ln187_16_fu_1530_p2[23:8]}};
        trunc_ln187_16_reg_2729 <= {{mul_ln187_17_fu_1553_p2[23:8]}};
        trunc_ln187_25_reg_2734 <= {{mul_ln187_26_fu_1576_p2[22:8]}};
        trunc_ln187_26_reg_2739 <= {{mul_ln187_27_fu_1599_p2[21:8]}};
        trunc_ln187_27_reg_2744 <= {{mul_ln187_28_fu_1622_p2[21:8]}};
        trunc_ln187_28_reg_2749 <= {{mul_ln187_29_fu_1645_p2[20:8]}};
        trunc_ln187_3_reg_2679 <= {{mul_ln187_3_fu_1323_p2[23:8]}};
        trunc_ln187_4_reg_2684 <= {{mul_ln187_4_fu_1346_p2[23:8]}};
        trunc_ln187_5_reg_2689 <= {{mul_ln187_5_fu_1369_p2[23:8]}};
        trunc_ln187_6_reg_2694 <= {{mul_ln187_6_fu_1392_p2[23:8]}};
        zext_ln187_reg_2221[7 : 0] <= zext_ln187_fu_985_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln180_reg_2158 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        first_ind_load_reg_2206 <= first_ind_q0;
        mel_filterbank_0_load_reg_2216 <= mel_filterbank_0_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln180_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_cast_reg_2162[5 : 0] <= m_cast_fu_969_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        reg_889 <= abs_spectrogram_q14;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        reg_893 <= abs_spectrogram_q13;
        reg_897 <= abs_spectrogram_q12;
        reg_901 <= abs_spectrogram_q11;
        reg_905 <= abs_spectrogram_q10;
        reg_909 <= abs_spectrogram_q9;
        reg_913 <= abs_spectrogram_q8;
        reg_917 <= abs_spectrogram_q7;
        reg_921 <= abs_spectrogram_q6;
        reg_925 <= abs_spectrogram_q5;
        reg_929 <= abs_spectrogram_q4;
        reg_933 <= abs_spectrogram_q3;
        reg_937 <= abs_spectrogram_q2;
        reg_941 <= abs_spectrogram_q1;
        reg_945 <= abs_spectrogram_q0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            abs_spectrogram_address0 = zext_ln187_50_fu_1311_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            abs_spectrogram_address0 = zext_ln187_58_fu_1148_p1;
        end else begin
            abs_spectrogram_address0 = 'bx;
        end
    end else begin
        abs_spectrogram_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            abs_spectrogram_address1 = zext_ln187_48_fu_1301_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            abs_spectrogram_address1 = zext_ln187_56_fu_1137_p1;
        end else begin
            abs_spectrogram_address1 = 'bx;
        end
    end else begin
        abs_spectrogram_address1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            abs_spectrogram_address10 = zext_ln187_16_fu_1211_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            abs_spectrogram_address10 = zext_ln187_22_fu_1038_p1;
        end else begin
            abs_spectrogram_address10 = 'bx;
        end
    end else begin
        abs_spectrogram_address10 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            abs_spectrogram_address11 = zext_ln187_14_fu_1201_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            abs_spectrogram_address11 = zext_ln187_12_fu_1027_p1;
        end else begin
            abs_spectrogram_address11 = 'bx;
        end
    end else begin
        abs_spectrogram_address11 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            abs_spectrogram_address12 = zext_ln187_4_fu_1191_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            abs_spectrogram_address12 = zext_ln187_10_fu_1016_p1;
        end else begin
            abs_spectrogram_address12 = 'bx;
        end
    end else begin
        abs_spectrogram_address12 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            abs_spectrogram_address13 = zext_ln187_2_fu_1181_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            abs_spectrogram_address13 = zext_ln187_8_fu_1005_p1;
        end else begin
            abs_spectrogram_address13 = 'bx;
        end
    end else begin
        abs_spectrogram_address13 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        abs_spectrogram_address14 = zext_ln187_6_fu_994_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        abs_spectrogram_address14 = zext_ln186_fu_980_p1;
    end else begin
        abs_spectrogram_address14 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            abs_spectrogram_address2 = zext_ln187_46_fu_1291_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            abs_spectrogram_address2 = zext_ln187_54_fu_1126_p1;
        end else begin
            abs_spectrogram_address2 = 'bx;
        end
    end else begin
        abs_spectrogram_address2 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            abs_spectrogram_address3 = zext_ln187_44_fu_1281_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            abs_spectrogram_address3 = zext_ln187_52_fu_1115_p1;
        end else begin
            abs_spectrogram_address3 = 'bx;
        end
    end else begin
        abs_spectrogram_address3 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            abs_spectrogram_address4 = zext_ln187_42_fu_1271_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            abs_spectrogram_address4 = zext_ln187_34_fu_1104_p1;
        end else begin
            abs_spectrogram_address4 = 'bx;
        end
    end else begin
        abs_spectrogram_address4 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            abs_spectrogram_address5 = zext_ln187_40_fu_1261_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            abs_spectrogram_address5 = zext_ln187_32_fu_1093_p1;
        end else begin
            abs_spectrogram_address5 = 'bx;
        end
    end else begin
        abs_spectrogram_address5 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            abs_spectrogram_address6 = zext_ln187_38_fu_1251_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            abs_spectrogram_address6 = zext_ln187_30_fu_1082_p1;
        end else begin
            abs_spectrogram_address6 = 'bx;
        end
    end else begin
        abs_spectrogram_address6 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            abs_spectrogram_address7 = zext_ln187_36_fu_1241_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            abs_spectrogram_address7 = zext_ln187_28_fu_1071_p1;
        end else begin
            abs_spectrogram_address7 = 'bx;
        end
    end else begin
        abs_spectrogram_address7 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            abs_spectrogram_address8 = zext_ln187_20_fu_1231_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            abs_spectrogram_address8 = zext_ln187_26_fu_1060_p1;
        end else begin
            abs_spectrogram_address8 = 'bx;
        end
    end else begin
        abs_spectrogram_address8 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            abs_spectrogram_address9 = zext_ln187_18_fu_1221_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            abs_spectrogram_address9 = zext_ln187_24_fu_1049_p1;
        end else begin
            abs_spectrogram_address9 = 'bx;
        end
    end else begin
        abs_spectrogram_address9 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        abs_spectrogram_ce0 = 1'b1;
    end else begin
        abs_spectrogram_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        abs_spectrogram_ce1 = 1'b1;
    end else begin
        abs_spectrogram_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        abs_spectrogram_ce10 = 1'b1;
    end else begin
        abs_spectrogram_ce10 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        abs_spectrogram_ce11 = 1'b1;
    end else begin
        abs_spectrogram_ce11 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        abs_spectrogram_ce12 = 1'b1;
    end else begin
        abs_spectrogram_ce12 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        abs_spectrogram_ce13 = 1'b1;
    end else begin
        abs_spectrogram_ce13 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        abs_spectrogram_ce14 = 1'b1;
    end else begin
        abs_spectrogram_ce14 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        abs_spectrogram_ce2 = 1'b1;
    end else begin
        abs_spectrogram_ce2 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        abs_spectrogram_ce3 = 1'b1;
    end else begin
        abs_spectrogram_ce3 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        abs_spectrogram_ce4 = 1'b1;
    end else begin
        abs_spectrogram_ce4 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        abs_spectrogram_ce5 = 1'b1;
    end else begin
        abs_spectrogram_ce5 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        abs_spectrogram_ce6 = 1'b1;
    end else begin
        abs_spectrogram_ce6 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        abs_spectrogram_ce7 = 1'b1;
    end else begin
        abs_spectrogram_ce7 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        abs_spectrogram_ce8 = 1'b1;
    end else begin
        abs_spectrogram_ce8 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        abs_spectrogram_ce9 = 1'b1;
    end else begin
        abs_spectrogram_ce9 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln180_reg_2158 == 1'd1) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln180_reg_2158_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to4 = 1'b1;
    end else begin
        ap_idle_pp0_1to4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_m_2 = 6'd0;
    end else begin
        ap_sig_allocacmp_m_2 = m_fu_168;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        first_ind_ce0 = 1'b1;
    end else begin
        first_ind_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_filterbank_0_ce0 = 1'b1;
    end else begin
        mel_filterbank_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_filterbank_10_ce0 = 1'b1;
    end else begin
        mel_filterbank_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_filterbank_11_ce0 = 1'b1;
    end else begin
        mel_filterbank_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_filterbank_12_ce0 = 1'b1;
    end else begin
        mel_filterbank_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_filterbank_13_ce0 = 1'b1;
    end else begin
        mel_filterbank_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_filterbank_14_ce0 = 1'b1;
    end else begin
        mel_filterbank_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_filterbank_15_ce0 = 1'b1;
    end else begin
        mel_filterbank_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_filterbank_16_ce0 = 1'b1;
    end else begin
        mel_filterbank_16_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_filterbank_17_ce0 = 1'b1;
    end else begin
        mel_filterbank_17_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_filterbank_18_ce0 = 1'b1;
    end else begin
        mel_filterbank_18_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_filterbank_19_ce0 = 1'b1;
    end else begin
        mel_filterbank_19_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_filterbank_1_ce0 = 1'b1;
    end else begin
        mel_filterbank_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_filterbank_20_ce0 = 1'b1;
    end else begin
        mel_filterbank_20_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_filterbank_21_ce0 = 1'b1;
    end else begin
        mel_filterbank_21_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_filterbank_22_ce0 = 1'b1;
    end else begin
        mel_filterbank_22_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_filterbank_23_ce0 = 1'b1;
    end else begin
        mel_filterbank_23_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_filterbank_24_ce0 = 1'b1;
    end else begin
        mel_filterbank_24_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_filterbank_25_ce0 = 1'b1;
    end else begin
        mel_filterbank_25_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_filterbank_26_ce0 = 1'b1;
    end else begin
        mel_filterbank_26_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_filterbank_27_ce0 = 1'b1;
    end else begin
        mel_filterbank_27_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_filterbank_28_ce0 = 1'b1;
    end else begin
        mel_filterbank_28_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_filterbank_29_ce0 = 1'b1;
    end else begin
        mel_filterbank_29_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_filterbank_2_ce0 = 1'b1;
    end else begin
        mel_filterbank_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_filterbank_3_ce0 = 1'b1;
    end else begin
        mel_filterbank_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_filterbank_4_ce0 = 1'b1;
    end else begin
        mel_filterbank_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_filterbank_5_ce0 = 1'b1;
    end else begin
        mel_filterbank_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_filterbank_6_ce0 = 1'b1;
    end else begin
        mel_filterbank_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_filterbank_7_ce0 = 1'b1;
    end else begin
        mel_filterbank_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_filterbank_8_ce0 = 1'b1;
    end else begin
        mel_filterbank_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_filterbank_9_ce0 = 1'b1;
    end else begin
        mel_filterbank_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_filtered_ce0 = 1'b1;
    end else begin
        mel_filtered_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_filtered_we0 = 1'b1;
    end else begin
        mel_filtered_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((1'b1 == ap_condition_exit_pp0_iter3_stage0) & (ap_idle_pp0_0to2 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to4 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln180_fu_963_p2 = (ap_sig_allocacmp_m_2 + 6'd1);

assign add_ln187_10_fu_1032_p2 = (zext_ln187_fu_985_p1 + 9'd11);

assign add_ln187_11_fu_1043_p2 = (zext_ln187_fu_985_p1 + 9'd12);

assign add_ln187_12_fu_1054_p2 = (zext_ln187_fu_985_p1 + 9'd13);

assign add_ln187_13_fu_1065_p2 = (zext_ln187_fu_985_p1 + 9'd14);

assign add_ln187_14_fu_1076_p2 = (zext_ln187_fu_985_p1 + 9'd15);

assign add_ln187_15_fu_1087_p2 = (zext_ln187_fu_985_p1 + 9'd16);

assign add_ln187_16_fu_1098_p2 = (zext_ln187_fu_985_p1 + 9'd17);

assign add_ln187_17_fu_1236_p2 = (zext_ln187_reg_2221 + 9'd18);

assign add_ln187_18_fu_1246_p2 = (zext_ln187_reg_2221 + 9'd19);

assign add_ln187_19_fu_1256_p2 = (zext_ln187_reg_2221 + 9'd20);

assign add_ln187_1_fu_1186_p2 = (zext_ln187_reg_2221 + 9'd2);

assign add_ln187_20_fu_1266_p2 = (zext_ln187_reg_2221 + 9'd21);

assign add_ln187_21_fu_1276_p2 = (zext_ln187_reg_2221 + 9'd22);

assign add_ln187_22_fu_1286_p2 = (zext_ln187_reg_2221 + 9'd23);

assign add_ln187_23_fu_1296_p2 = (zext_ln187_reg_2221 + 9'd24);

assign add_ln187_24_fu_1306_p2 = (zext_ln187_reg_2221 + 9'd25);

assign add_ln187_25_fu_1109_p2 = (zext_ln187_fu_985_p1 + 9'd26);

assign add_ln187_26_fu_1120_p2 = (zext_ln187_fu_985_p1 + 9'd27);

assign add_ln187_27_fu_1131_p2 = (zext_ln187_fu_985_p1 + 9'd28);

assign add_ln187_28_fu_1142_p2 = (zext_ln187_fu_985_p1 + 9'd29);

assign add_ln187_29_fu_2063_p2 = (trunc_ln1_reg_2459_pp0_iter2_reg + trunc_ln187_2_reg_2759);

assign add_ln187_2_fu_988_p2 = (zext_ln187_fu_985_p1 + 9'd3);

assign add_ln187_30_fu_2067_p2 = (add_ln187_29_fu_2063_p2 + trunc_ln187_1_reg_2754);

assign add_ln187_31_fu_1995_p2 = (trunc_ln187_3_reg_2679 + trunc_ln187_4_reg_2684);

assign add_ln187_32_fu_1999_p2 = (trunc_ln187_5_reg_2689 + trunc_ln187_6_reg_2694);

assign add_ln187_33_fu_2003_p2 = (add_ln187_32_fu_1999_p2 + add_ln187_31_fu_1995_p2);

assign add_ln187_34_fu_2072_p2 = (add_ln187_33_reg_2824 + add_ln187_30_fu_2067_p2);

assign add_ln187_35_fu_2077_p2 = (trunc_ln187_7_reg_2764 + trunc_ln187_8_reg_2769);

assign add_ln187_36_fu_2081_p2 = (trunc_ln187_9_reg_2774 + trunc_ln187_s_reg_2779);

assign add_ln187_37_fu_2085_p2 = (add_ln187_36_fu_2081_p2 + add_ln187_35_fu_2077_p2);

assign add_ln187_38_fu_2009_p2 = (trunc_ln187_10_reg_2699 + trunc_ln187_11_reg_2704);

assign add_ln187_39_fu_2013_p2 = (trunc_ln187_12_reg_2709 + trunc_ln187_13_reg_2714);

assign add_ln187_3_fu_999_p2 = (zext_ln187_fu_985_p1 + 9'd4);

assign add_ln187_40_fu_2017_p2 = (add_ln187_39_fu_2013_p2 + add_ln187_38_fu_2009_p2);

assign add_ln187_41_fu_2091_p2 = (add_ln187_40_reg_2829 + add_ln187_37_fu_2085_p2);

assign add_ln187_42_fu_2141_p2 = (add_ln187_41_reg_2849 + add_ln187_34_reg_2844);

assign add_ln187_43_fu_2023_p2 = (trunc_ln187_15_reg_2724 + trunc_ln187_16_reg_2729);

assign add_ln187_44_fu_2027_p2 = (add_ln187_43_fu_2023_p2 + trunc_ln187_14_reg_2719);

assign add_ln187_45_fu_2096_p2 = (trunc_ln187_17_reg_2784 + trunc_ln187_18_reg_2789);

assign add_ln187_46_fu_2100_p2 = (trunc_ln187_19_reg_2794 + trunc_ln187_20_reg_2799);

assign add_ln187_47_fu_2104_p2 = (add_ln187_46_fu_2100_p2 + add_ln187_45_fu_2096_p2);

assign add_ln187_48_fu_2132_p2 = (add_ln187_47_reg_2854 + add_ln187_44_reg_2834);

assign add_ln187_49_fu_2110_p2 = ($signed(trunc_ln187_21_reg_2804) + $signed(sext_ln187_24_fu_2054_p1));

assign add_ln187_4_fu_1010_p2 = (zext_ln187_fu_985_p1 + 9'd5);

assign add_ln187_50_fu_2115_p2 = ($signed(sext_ln187_26_fu_2057_p1) + $signed(sext_ln187_28_fu_2060_p1));

assign add_ln187_51_fu_2121_p2 = (add_ln187_50_fu_2115_p2 + add_ln187_49_fu_2110_p2);

assign add_ln187_52_fu_2032_p2 = ($signed(sext_ln187_30_fu_1983_p1) + $signed(sext_ln187_32_fu_1986_p1));

assign add_ln187_53_fu_2038_p2 = ($signed(sext_ln187_34_fu_1989_p1) + $signed(sext_ln187_36_fu_1992_p1));

assign add_ln187_54_fu_2048_p2 = ($signed(sext_ln187_37_fu_2044_p1) + $signed(add_ln187_52_fu_2032_p2));

assign add_ln187_55_fu_2127_p2 = (add_ln187_54_reg_2839 + add_ln187_51_fu_2121_p2);

assign add_ln187_56_fu_2136_p2 = (add_ln187_55_reg_2859 + add_ln187_48_fu_2132_p2);

assign add_ln187_5_fu_1021_p2 = (zext_ln187_fu_985_p1 + 9'd6);

assign add_ln187_6_fu_1196_p2 = (zext_ln187_reg_2221 + 9'd7);

assign add_ln187_7_fu_1206_p2 = (zext_ln187_reg_2221 + 9'd8);

assign add_ln187_8_fu_1216_p2 = (zext_ln187_reg_2221 + 9'd9);

assign add_ln187_9_fu_1226_p2 = (zext_ln187_reg_2221 + 9'd10);

assign add_ln187_fu_1176_p2 = (zext_ln187_reg_2221 + 9'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign first_ind_address0 = m_cast_fu_969_p1;

assign icmp_ln180_fu_957_p2 = ((ap_sig_allocacmp_m_2 == 6'd42) ? 1'b1 : 1'b0);

assign m_cast_fu_969_p1 = ap_sig_allocacmp_m_2;

assign mel_filterbank_0_address0 = m_cast_fu_969_p1;

assign mel_filterbank_10_address0 = m_cast_reg_2162;

assign mel_filterbank_11_address0 = m_cast_reg_2162;

assign mel_filterbank_12_address0 = m_cast_reg_2162;

assign mel_filterbank_13_address0 = m_cast_reg_2162;

assign mel_filterbank_14_address0 = m_cast_reg_2162;

assign mel_filterbank_15_address0 = m_cast_reg_2162;

assign mel_filterbank_16_address0 = m_cast_reg_2162;

assign mel_filterbank_17_address0 = m_cast_reg_2162;

assign mel_filterbank_18_address0 = m_cast_reg_2162;

assign mel_filterbank_19_address0 = m_cast_reg_2162;

assign mel_filterbank_1_address0 = m_cast_reg_2162;

assign mel_filterbank_20_address0 = m_cast_reg_2162;

assign mel_filterbank_21_address0 = m_cast_reg_2162;

assign mel_filterbank_22_address0 = m_cast_reg_2162;

assign mel_filterbank_23_address0 = m_cast_reg_2162;

assign mel_filterbank_24_address0 = m_cast_reg_2162;

assign mel_filterbank_25_address0 = m_cast_reg_2162;

assign mel_filterbank_26_address0 = m_cast_reg_2162;

assign mel_filterbank_27_address0 = m_cast_reg_2162;

assign mel_filterbank_28_address0 = m_cast_reg_2162;

assign mel_filterbank_29_address0 = m_cast_reg_2162;

assign mel_filterbank_2_address0 = m_cast_reg_2162;

assign mel_filterbank_3_address0 = m_cast_reg_2162;

assign mel_filterbank_4_address0 = m_cast_reg_2162;

assign mel_filterbank_5_address0 = m_cast_reg_2162;

assign mel_filterbank_6_address0 = m_cast_reg_2162;

assign mel_filterbank_7_address0 = m_cast_reg_2162;

assign mel_filterbank_8_address0 = m_cast_reg_2162;

assign mel_filterbank_9_address0 = m_cast_reg_2162;

assign mel_filtered_address0 = m_cast_reg_2162_pp0_iter3_reg;

assign mel_filtered_d0 = (add_ln187_56_reg_2864 + add_ln187_42_fu_2141_p2);

assign mul_ln187_10_fu_1783_p0 = mul_ln187_10_fu_1783_p00;

assign mul_ln187_10_fu_1783_p00 = mel_filterbank_10_load_reg_2539;

assign mul_ln187_11_fu_1415_p0 = mul_ln187_11_fu_1415_p00;

assign mul_ln187_11_fu_1415_p00 = mel_filterbank_11_load_reg_2544;

assign mul_ln187_12_fu_1438_p0 = mul_ln187_12_fu_1438_p00;

assign mul_ln187_12_fu_1438_p00 = mel_filterbank_12_load_reg_2549;

assign mul_ln187_13_fu_1461_p0 = mul_ln187_13_fu_1461_p00;

assign mul_ln187_13_fu_1461_p00 = mel_filterbank_13_load_reg_2554;

assign mul_ln187_14_fu_1484_p0 = mul_ln187_14_fu_1484_p00;

assign mul_ln187_14_fu_1484_p00 = mel_filterbank_14_load_reg_2559;

assign mul_ln187_15_fu_1507_p0 = mul_ln187_15_fu_1507_p00;

assign mul_ln187_15_fu_1507_p00 = mel_filterbank_15_load_reg_2564;

assign mul_ln187_16_fu_1530_p0 = mul_ln187_16_fu_1530_p00;

assign mul_ln187_16_fu_1530_p00 = mel_filterbank_16_load_reg_2569;

assign mul_ln187_17_fu_1553_p0 = mul_ln187_17_fu_1553_p00;

assign mul_ln187_17_fu_1553_p00 = mel_filterbank_17_load_reg_2574;

assign mul_ln187_18_fu_1806_p0 = mul_ln187_18_fu_1806_p00;

assign mul_ln187_18_fu_1806_p00 = mel_filterbank_18_load_reg_2584;

assign mul_ln187_19_fu_1829_p0 = mul_ln187_19_fu_1829_p00;

assign mul_ln187_19_fu_1829_p00 = mel_filterbank_19_load_reg_2594;

assign mul_ln187_1_fu_1668_p0 = mul_ln187_1_fu_1668_p00;

assign mul_ln187_1_fu_1668_p00 = mel_filterbank_1_load_reg_2469;

assign mul_ln187_20_fu_1852_p0 = mul_ln187_20_fu_1852_p00;

assign mul_ln187_20_fu_1852_p00 = mel_filterbank_20_load_reg_2604;

assign mul_ln187_21_fu_1875_p0 = mul_ln187_21_fu_1875_p00;

assign mul_ln187_21_fu_1875_p00 = mel_filterbank_21_load_reg_2614;

assign mul_ln187_22_fu_1898_p0 = mul_ln187_22_fu_1898_p00;

assign mul_ln187_22_fu_1898_p00 = mel_filterbank_22_load_reg_2624;

assign mul_ln187_23_fu_1921_p0 = mul_ln187_23_fu_1921_p00;

assign mul_ln187_23_fu_1921_p00 = mel_filterbank_23_load_reg_2634;

assign mul_ln187_24_fu_1944_p0 = mul_ln187_24_fu_1944_p00;

assign mul_ln187_24_fu_1944_p00 = mel_filterbank_24_load_reg_2644;

assign mul_ln187_25_fu_1967_p0 = mul_ln187_25_fu_1967_p00;

assign mul_ln187_25_fu_1967_p00 = mel_filterbank_25_load_reg_2654;

assign mul_ln187_26_fu_1576_p0 = mul_ln187_26_fu_1576_p00;

assign mul_ln187_26_fu_1576_p00 = mel_filterbank_26_load_reg_2659;

assign mul_ln187_27_fu_1599_p0 = mul_ln187_27_fu_1599_p00;

assign mul_ln187_27_fu_1599_p00 = mel_filterbank_27_load_reg_2664;

assign mul_ln187_28_fu_1622_p0 = mul_ln187_28_fu_1622_p00;

assign mul_ln187_28_fu_1622_p00 = mel_filterbank_28_load_reg_2669;

assign mul_ln187_29_fu_1645_p0 = mul_ln187_29_fu_1645_p00;

assign mul_ln187_29_fu_1645_p00 = mel_filterbank_29_load_reg_2674;

assign mul_ln187_2_fu_1691_p0 = mul_ln187_2_fu_1691_p00;

assign mul_ln187_2_fu_1691_p00 = mel_filterbank_2_load_reg_2479;

assign mul_ln187_3_fu_1323_p0 = mul_ln187_3_fu_1323_p00;

assign mul_ln187_3_fu_1323_p00 = mel_filterbank_3_load_reg_2484;

assign mul_ln187_4_fu_1346_p0 = mul_ln187_4_fu_1346_p00;

assign mul_ln187_4_fu_1346_p00 = mel_filterbank_4_load_reg_2489;

assign mul_ln187_5_fu_1369_p0 = mul_ln187_5_fu_1369_p00;

assign mul_ln187_5_fu_1369_p00 = mel_filterbank_5_load_reg_2494;

assign mul_ln187_6_fu_1392_p0 = mul_ln187_6_fu_1392_p00;

assign mul_ln187_6_fu_1392_p00 = mel_filterbank_6_load_reg_2499;

assign mul_ln187_7_fu_1714_p0 = mul_ln187_7_fu_1714_p00;

assign mul_ln187_7_fu_1714_p00 = mel_filterbank_7_load_reg_2509;

assign mul_ln187_8_fu_1737_p0 = mul_ln187_8_fu_1737_p00;

assign mul_ln187_8_fu_1737_p00 = mel_filterbank_8_load_reg_2519;

assign mul_ln187_9_fu_1760_p0 = mul_ln187_9_fu_1760_p00;

assign mul_ln187_9_fu_1760_p00 = mel_filterbank_9_load_reg_2529;

assign mul_ln187_fu_1160_p0 = mul_ln187_fu_1160_p00;

assign mul_ln187_fu_1160_p00 = mel_filterbank_0_load_reg_2216;

assign sext_ln187_24_fu_2054_p1 = $signed(trunc_ln187_22_reg_2809);

assign sext_ln187_26_fu_2057_p1 = $signed(trunc_ln187_23_reg_2814);

assign sext_ln187_28_fu_2060_p1 = $signed(trunc_ln187_24_reg_2819);

assign sext_ln187_30_fu_1983_p1 = $signed(trunc_ln187_25_reg_2734);

assign sext_ln187_32_fu_1986_p1 = $signed(trunc_ln187_26_reg_2739);

assign sext_ln187_34_fu_1989_p1 = $signed(trunc_ln187_27_reg_2744);

assign sext_ln187_36_fu_1992_p1 = $signed(trunc_ln187_28_reg_2749);

assign sext_ln187_37_fu_2044_p1 = $signed(add_ln187_53_fu_2038_p2);

assign zext_ln186_fu_980_p1 = first_ind_q0;

assign zext_ln187_10_fu_1016_p1 = add_ln187_4_fu_1010_p2;

assign zext_ln187_12_fu_1027_p1 = add_ln187_5_fu_1021_p2;

assign zext_ln187_14_fu_1201_p1 = add_ln187_6_fu_1196_p2;

assign zext_ln187_16_fu_1211_p1 = add_ln187_7_fu_1206_p2;

assign zext_ln187_18_fu_1221_p1 = add_ln187_8_fu_1216_p2;

assign zext_ln187_20_fu_1231_p1 = add_ln187_9_fu_1226_p2;

assign zext_ln187_22_fu_1038_p1 = add_ln187_10_fu_1032_p2;

assign zext_ln187_24_fu_1049_p1 = add_ln187_11_fu_1043_p2;

assign zext_ln187_26_fu_1060_p1 = add_ln187_12_fu_1054_p2;

assign zext_ln187_28_fu_1071_p1 = add_ln187_13_fu_1065_p2;

assign zext_ln187_2_fu_1181_p1 = add_ln187_fu_1176_p2;

assign zext_ln187_30_fu_1082_p1 = add_ln187_14_fu_1076_p2;

assign zext_ln187_32_fu_1093_p1 = add_ln187_15_fu_1087_p2;

assign zext_ln187_34_fu_1104_p1 = add_ln187_16_fu_1098_p2;

assign zext_ln187_36_fu_1241_p1 = add_ln187_17_fu_1236_p2;

assign zext_ln187_38_fu_1251_p1 = add_ln187_18_fu_1246_p2;

assign zext_ln187_40_fu_1261_p1 = add_ln187_19_fu_1256_p2;

assign zext_ln187_42_fu_1271_p1 = add_ln187_20_fu_1266_p2;

assign zext_ln187_44_fu_1281_p1 = add_ln187_21_fu_1276_p2;

assign zext_ln187_46_fu_1291_p1 = add_ln187_22_fu_1286_p2;

assign zext_ln187_48_fu_1301_p1 = add_ln187_23_fu_1296_p2;

assign zext_ln187_4_fu_1191_p1 = add_ln187_1_fu_1186_p2;

assign zext_ln187_50_fu_1311_p1 = add_ln187_24_fu_1306_p2;

assign zext_ln187_52_fu_1115_p1 = add_ln187_25_fu_1109_p2;

assign zext_ln187_54_fu_1126_p1 = add_ln187_26_fu_1120_p2;

assign zext_ln187_56_fu_1137_p1 = add_ln187_27_fu_1131_p2;

assign zext_ln187_58_fu_1148_p1 = add_ln187_28_fu_1142_p2;

assign zext_ln187_6_fu_994_p1 = add_ln187_2_fu_988_p2;

assign zext_ln187_8_fu_1005_p1 = add_ln187_3_fu_999_p2;

assign zext_ln187_fu_985_p1 = first_ind_load_reg_2206;

always @ (posedge ap_clk) begin
    m_cast_reg_2162[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    m_cast_reg_2162_pp0_iter1_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    m_cast_reg_2162_pp0_iter2_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    m_cast_reg_2162_pp0_iter3_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln187_reg_2221[8] <= 1'b0;
end

endmodule //mfcc_mfcc_Pipeline_VITIS_LOOP_180_1
